'use client';

import { useEffect, useMemo, useState } from 'react';
import { Pencil, Plus, RefreshCw, ShieldCheck, Trash2, X } from 'lucide-react';
import { systemFetch } from '../../../lib/system-api';
import { Button, EmptyState, ErrorState, LoadingState } from '../../../components/ui';
import { ConfirmDialog } from '../../../components/confirm-dialog';
import { Modal, ModalBody } from '../../../components/modal';
import { PermissionChip, PermissionPickerItem, permissionMeta } from '../../../components/rbac/PermissionPresentation';
import { useToast } from '../../../components/toast';

type Permission={id:string;key:string;name?:string|null;description?:string|null};
type Role={id:string;name:string;isSystem:boolean;permissions:{permissionId:string;permissionKey:string}[]};

export default function SystemRolesPage(){
 const {toast}=useToast();const [roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [modal,setModal]=useState<'create'|'edit'|null>(null),[selected,setSelected]=useState<Role|null>(null),[name,setName]=useState(''),[selectedKeys,setSelectedKeys]=useState<string[]>([]),[confirm,setConfirm]=useState<Role|null>(null);
 async function load(){setLoading(true);setError('');try{const [r,p]=await Promise.all([systemFetch('/system/roles'),systemFetch('/system/roles/permissions')]);setRoles(Array.isArray(r)?r:[]);setPermissions(Array.isArray(p)?p:[])}catch(e:any){setError(e?.message??'Unable to load platform roles.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const groups=useMemo(()=>{const m=new Map<string,Permission[]>();for(const p of permissions){const g=permissionMeta(p.key).group;const a=m.get(g)||[];a.push(p);m.set(g,a)}return [...m.entries()].sort(([a],[b])=>a.localeCompare(b))},[permissions]);
 function openCreate(){setSelected(null);setName('');setSelectedKeys([]);setModal('create')}
 function openEdit(r:Role){setSelected(r);setName(r.name);setSelectedKeys(r.permissions.map(p=>p.permissionKey));setModal('edit')}
 function toggle(key:string){setSelectedKeys(k=>k.includes(key)?k.filter(x=>x!==key):[...k,key])}
 async function save(){if(name.trim().length<2||!selectedKeys.length){setError('Role name and at least one platform permission are required.');return}setSaving(true);setError('');try{if(modal==='create'){await systemFetch('/system/roles',{method:'POST',body:JSON.stringify({name:name.trim(),permissionKeys:selectedKeys})});toast({title:'Platform role created',message:name.trim(),tone:'success'})}else if(selected){await systemFetch(`/system/roles/${selected.id}`,{method:'PATCH',body:JSON.stringify({name:name.trim(),permissionKeys:selectedKeys})});toast({title:'Platform role updated',message:name.trim(),tone:'success'})}setModal(null);await load()}catch(e:any){setError(e?.message??'Unable to save platform role.');toast({title:'Role update failed',message:e?.message??'Unable to save platform role.',tone:'error'})}finally{setSaving(false)}}
 async function remove(){if(!confirm)return;setSaving(true);try{await systemFetch(`/system/roles/${confirm.id}`,{method:'DELETE'});toast({title:'Platform role deleted',message:confirm.name,tone:'success'});setConfirm(null);await load()}catch(e:any){toast({title:'Role deletion failed',message:e?.message??'Unable to delete platform role.',tone:'error'})}finally{setSaving(false)}}
 if(loading)return <LoadingState label="Loading platform roles…"/>;
 if(error&&roles.length===0)return <ErrorState title="Unable to load platform roles" message={error} onRetry={()=>void load()}/>;
 return <div className="space-y-6">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-600">Platform administration</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Roles &amp; Permissions</h1><p className="mt-2 text-sm text-slate-500">Create and maintain platform access policies. Built-in roles are protected.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>void load()} loading={loading} icon={<RefreshCw size={15}/>}>Refresh</Button><Button onClick={openCreate} icon={<Plus size={16}/>}>Create role</Button></div></header>
  {error?<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
  {roles.length===0?<EmptyState title="No platform roles" text="Create the first custom platform role." action="Create role" onAction={openCreate}/>:<section className="panel overflow-hidden"><div className="border-b border-slate-100 p-4"><p className="font-semibold text-slate-900">Platform roles</p><p className="mt-1 text-xs text-slate-500">{roles.length} roles configured</p></div><div className="divide-y divide-slate-100">{roles.map(r=><div key={r.id} className="p-5 ui-table-row"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-950">{r.name}</p><span className={r.isSystem?'badge badge-warning':'badge badge-brand'}>{r.isSystem?'Built-in':'Custom'}</span></div><p className="mt-1 text-xs text-slate-500">{r.permissions.length} permission{r.permissions.length===1?'':'s'}</p><div className="mt-3 flex flex-wrap gap-1.5">{r.permissions.map(p=><PermissionChip key={p.permissionId} permissionKey={p.permissionKey}/>)}</div></div><div className="flex gap-2">{!r.isSystem?<><Button size="sm" variant="secondary" onClick={()=>openEdit(r)} icon={<Pencil size={14}/>}>Edit</Button><Button size="sm" variant="danger" onClick={()=>setConfirm(r)} icon={<Trash2 size={14}/>}>Delete</Button></>:<span className="inline-flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-800"><ShieldCheck size={14}/>Protected</span>}</div></div></div>)}</div></section>}
  {modal?<Modal open title={modal==='create'?'Create platform role':'Edit platform role'} description="Choose only platform permissions for this role." onClose={()=>!saving&&setModal(null)} size="lg"><ModalBody><label className="block text-sm font-semibold text-slate-700">Role name<input value={name} onChange={e=>setName(e.target.value)} className="field mt-2 h-11 w-full" placeholder="Security Operations"/></label><div className="mt-6 flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-900">Permissions</p><p className="mt-1 text-xs text-slate-500">{selectedKeys.length} selected</p></div><button type="button" onClick={()=>setSelectedKeys(selectedKeys.length===permissions.length?[]:permissions.map(p=>p.key))} className="text-xs font-semibold text-[var(--theme-link)]">{selectedKeys.length===permissions.length?'Clear all':'Select all'}</button></div><div className="mt-3 grid gap-4 lg:grid-cols-2">{groups.map(([group,list])=><div key={group} className="rounded-2xl border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold text-slate-800">{group}</p><span className="badge badge-neutral">{list.length}</span></div><div className="space-y-2">{list.map(p=><PermissionPickerItem key={p.key} permissionKey={p.key} selected={selectedKeys.includes(p.key)} onToggle={()=>toggle(p.key)}/>)}</div></div>)}</div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setModal(null)} disabled={saving}>Cancel</Button><Button loading={saving} disabled={name.trim().length<2||!selectedKeys.length} onClick={()=>void save()}>{modal==='create'?'Create role':'Save changes'}</Button></div></ModalBody></Modal>:null}
  <ConfirmDialog open={!!confirm} title="Delete platform role" message={confirm?`Delete “${confirm.name}”? The role must not be assigned to any platform user.`:undefined} confirmLabel="Delete role" danger loading={saving} onCancel={()=>!saving&&setConfirm(null)} onConfirm={()=>void remove()}/>
 </div>;
}
