'use client';

import { FormEvent, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { KeyRound, ShieldCheck } from 'lucide-react';
import { apiFetch } from '../../lib/api-client';
import { PasswordInput } from '../../components/password-input';

export default function AcceptInvitePage(){
 const params=useSearchParams();const router=useRouter();const token=params.get('token')??'';const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [done,setDone]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError(null);if(password.length<8)return setError('Password must be at least 8 characters.');if(password!==confirm)return setError('Passwords do not match.');setBusy(true);try{await apiFetch('/auth/invite/accept',{method:'POST',body:JSON.stringify({token,password})});setDone(true);}catch(err:any){setError(err?.message??'This invitation link is invalid or expired.')}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-950 grid place-items-center px-4"><div className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl"><div className="grid h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><ShieldCheck size={24}/></div><p className="mt-6 text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">AssetHub access</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Set your password</h1>{done?<div className="mt-6 space-y-4"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">Your password has been set successfully.</div><button onClick={()=>router.push('/login')} className="w-full rounded-xl bg-blue-600 py-3 text-sm font-semibold text-white">Continue to login</button></div>:!token?<div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">This invitation link is missing its token.</div>:<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold text-slate-700">New password<PasswordInput required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 h-11"/></label><label className="block text-sm font-semibold text-slate-700">Confirm password<PasswordInput required minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-2 h-11"/></label>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-semibold text-white disabled:opacity-60"><KeyRound size={16}/>{busy?'Saving…':'Set password'}</button></form>}</div></main>
}
