import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';

@Injectable()
export class UserAsset360Service {
  constructor(private readonly prisma:PrismaService){}
  async overview(auth:AuthContext,userId:string){const user=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.user.findFirst({where:{id:userId,tenantId:auth.tenantId,...(auth.crossCompany?{}:{companyId:auth.companyId})}}));if(!user)throw new NotFoundException('User not found');const assignments=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetAssignment.findMany({where:{userId,asset:{tenantId:auth.tenantId,...(auth.crossCompany?{}:{companyId:auth.companyId})}},orderBy:{assignedAt:'desc'}}));const ids=[...new Set(assignments.map(a=>a.assetId))];const assets=ids.length?await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.asset.findMany({where:{id:{in:ids},tenantId:auth.tenantId,...(auth.crossCompany?{}:{companyId:auth.companyId})},include:{assetType:{select:{name:true}}}})):[];const assetMap=new Map(assets.map(a=>[a.id,a]));const current=assignments.filter(a=>!a.returnedAt);const typeCounts:Record<string,number>={};for(const a of current){const asset=assetMap.get(a.assetId);const type=asset?.assetType?.name??'Other';typeCounts[type]=(typeCounts[type]??0)+1;}const transfers=ids.length?await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetTransfer.findMany({where:{tenantId:auth.tenantId,assetId:{in:ids},...(auth.crossCompany?{}:{companyId:auth.companyId}),OR:[{fromUserId:userId},{toUserId:userId}]},orderBy:{requestedAt:'desc'},take:50})):[];const activity=[...assignments.map(a=>({type:a.returnedAt?'RETURN':'ASSIGNMENT',timestamp:a.returnedAt??a.assignedAt,assetId:a.assetId,title:a.returnedAt?'Asset returned':'Asset assigned'})),...transfers.map(t=>({type:'TRANSFER',timestamp:t.completedAt??t.requestedAt,assetId:t.assetId,title:`Transfer ${t.status.toLowerCase()}`,status:t.status}))].sort((a,b)=>new Date(String(b.timestamp)).getTime()-new Date(String(a.timestamp)).getTime()).slice(0,100);const dtoUser={id:user.id,employeeId:user.id,email:user.email,firstName:user.firstName,lastName:user.lastName,jobTitle:null,phone:null,companyId:user.companyId,departmentId:null,locationId:null,isActive:user.isActive,forcePasswordReset:user.forcePasswordReset,roleIds:[]};const row=(a:any)=>{const asset=assetMap.get(a.assetId);return asset?{assignment:a,asset:{...asset,assetType:asset.assetType?{name:asset.assetType.name}:undefined}}:null;};return{user:dtoUser,assetSummary:{currentCount:current.length,typeCounts},currentAssets:current.map(row).filter(Boolean),history:assignments.map(row).filter(Boolean),transfers,activity};}
}
