import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
import { InviteService } from '../auth/invite.service';
import { MailService } from '../../common/mail/mail.service';

@Injectable()
export class UsersService {
  constructor(private readonly db: PrismaService, private readonly invites: InviteService, private readonly mail: MailService) {}
  private where(auth: AuthContext, userId: string) { return { id: userId, tenantId: auth.tenantId, ...(auth.crossCompany ? {} : { companyId: auth.companyId }) }; }
  async sendAccessEmail(auth: AuthContext, userId: string, action: 'invite' | 'reset') { const user = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!user) throw new NotFoundException('User not found'); if (!user.isActive) throw new ConflictException('Cannot send access email to an inactive user'); const token = await this.invites.createInternalToken(user.id); const appUrl = (process.env.WEB_APP_URL ?? 'http://localhost:3000').replace(/\/$/, ''); const setupUrl = `${appUrl}/accept-invite?token=${encodeURIComponent(token.rawToken)}`; const result = await this.mail.sendTenantAccessEmail({ to: user.email, firstName: user.firstName ?? 'User', action, setupUrl, expiresAt: token.expiresAt }); return { ok: true, action, email: user.email, emailSent: result.sent, emailConfigured: this.mail.isEnabled(), setupUrl: result.sent ? undefined : setupUrl, expiresAt: token.expiresAt }; }
  async setActive(auth: AuthContext, userId: string, active: boolean) { const current = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!current) throw new NotFoundException('User not found'); if (!active && current.adminLevel === 'TENANT_ADMIN') { if (auth.adminLevel !== 'TENANT_ADMIN') throw new ForbiddenException('Only a Tenant Administrator can deactivate another Tenant Administrator'); const count = await this.db.user.count({ where: { tenantId: auth.tenantId, accountType: 'TENANT', adminLevel: 'TENANT_ADMIN', isActive: true } }); if (count <= 1) throw new ConflictException('The last active Tenant Admin cannot be deactivated'); } const updated = await this.db.user.update({ where: { id: userId }, data: { isActive: active, authVersion: { increment: 1 } } }); if (!active) await this.db.session.updateMany({ where: { userId, revokedAt: null }, data: { revokedAt: new Date(), revokedReason: 'admin_deactivated' } }); return this.safe(updated); }
  async sessions(auth: AuthContext, userId: string) { const user = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!user) throw new NotFoundException('User not found'); return this.db.session.findMany({ where: { userId }, orderBy: [{ lastSeenAt: 'desc' }, { createdAt: 'desc' }], select: { id: true, ipAddress: true, userAgent: true, approxLocation: true, lastSeenAt: true, expiresAt: true, revokedAt: true, revokedReason: true, createdAt: true } }); }
  async loginHistory(auth: AuthContext, userId: string) { const user = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!user) throw new NotFoundException('User not found'); return this.db.loginHistory.findMany({ where: { userId }, orderBy: { occurredAt: 'desc' }, take: 100 }); }
  private safe(user:any){const {passwordHash,accessTokenHash,totpSecretEnc,backupCodesHash,...safe}=user;return safe;}
}
