import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
import { InviteService } from '../auth/invite.service';
import { MailService } from '../../common/mail/mail.service';
import { EntitlementService } from '../billing/entitlement.service';
export type UserAdminLevel = 'EMPLOYEE' | 'COMPANY_ADMIN' | 'TENANT_ADMIN';
@Injectable()
export class UsersService {
  constructor(private readonly db: PrismaService, private readonly invites: InviteService, private readonly mail: MailService, private readonly entitlements: EntitlementService) {}
  private where(auth: AuthContext, userId?: string) { return { ...(userId ? { id: userId } : {}), tenantId: auth.tenantId, accountType: 'TENANT', ...(auth.crossCompany ? {} : { companyId: auth.companyId }) }; }
  private safe(user: any) { if (!user) return user; const { passwordHash, totpSecretEnc, backupCodesHash, accessTokenHash, ...safe } = user; return safe; }
  async list(auth: AuthContext, adminLevel?: UserAdminLevel) { const users = await this.db.user.findMany({ where: { ...this.where(auth), ...(adminLevel ? { adminLevel } : {}) }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }] }); return users.map((u) => this.safe(u)); }
  async listTenantAdmins(auth: AuthContext) { if (auth.adminLevel !== 'TENANT_ADMIN') throw new ForbiddenException('Tenant Administrators only'); return this.list({ ...auth, crossCompany: true }, 'TENANT_ADMIN'); }
  async get(auth: AuthContext, userId: string) { const user = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!user) throw new NotFoundException('User not found'); return this.safe(user); }
  async create(auth: AuthContext, input: { email: string; firstName: string; lastName: string; employeeId?: string; companyId?: string; jobTitle?: string; phone?: string; departmentId?: string; locationId?: string }) { const companyId = input.companyId ?? auth.companyId; if (!auth.crossCompany && companyId !== auth.companyId) throw new NotFoundException('Company not in scope'); const email = input.email.trim().toLowerCase(); if (await this.db.user.findFirst({ where: { tenantId: auth.tenantId, email } })) throw new ConflictException('A user with this email already exists'); const employeeId = input.employeeId?.trim() || undefined; if (employeeId && await this.db.user.findFirst({ where: { tenantId: auth.tenantId, employeeId } })) throw new ConflictException('A user with this employee ID already exists'); const count = await this.db.user.count({ where: { tenantId: auth.tenantId, accountType: 'TENANT' } }); await this.entitlements.requireWithinLimit(auth.tenantId, 'max_users', count, 1); const user = await this.db.user.create({ data: { tenantId: auth.tenantId, companyId, employeeId, email, firstName: input.firstName.trim(), lastName: input.lastName.trim(), jobTitle: input.jobTitle?.trim() || null, phone: input.phone?.trim() || null, departmentId: input.departmentId || null, locationId: input.locationId || null, isActive: true, forcePasswordReset: true, roleIds: [], accountType: 'TENANT', adminLevel: 'EMPLOYEE', mfaMethod: 'NONE', backupCodesHash: [] } }); return this.safe(user); }
  async update(auth: AuthContext, userId: string, input: { email?: string; firstName?: string; lastName?: string; employeeId?: string; jobTitle?: string; phone?: string; departmentId?: string; locationId?: string }) { const current = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!current) throw new NotFoundException('User not found'); const email = input.email?.trim().toLowerCase(); if (email && email !== current.email && await this.db.user.findFirst({ where: { tenantId: auth.tenantId, email, NOT: { id: userId } } })) throw new ConflictException('A user with this email already exists'); const employeeId = input.employeeId?.trim() || undefined; if (employeeId && employeeId !== current.employeeId && await this.db.user.findFirst({ where: { tenantId: auth.tenantId, employeeId, NOT: { id: userId } } })) throw new ConflictException('A user with this employee ID already exists'); const updated = await this.db.user.update({ where: { id: userId }, data: { ...(email !== undefined ? { email } : {}), ...(input.firstName !== undefined ? { firstName: input.firstName.trim() } : {}), ...(input.lastName !== undefined ? { lastName: input.lastName.trim() } : {}), ...(input.employeeId !== undefined ? { employeeId: employeeId ?? null } : {}), ...(input.jobTitle !== undefined ? { jobTitle: input.jobTitle.trim() || null } : {}), ...(input.phone !== undefined ? { phone: input.phone.trim() || null } : {}), ...(input.departmentId !== undefined ? { departmentId: input.departmentId || null } : {}), ...(input.locationId !== undefined ? { locationId: input.locationId || null } : {}) } }); return this.safe(updated); }
  async changeAdminLevel(auth: AuthContext, userId: string, adminLevel: UserAdminLevel) { if (auth.adminLevel !== 'TENANT_ADMIN') throw new ForbiddenException('Only a Tenant Administrator can change administrative levels'); if (userId === auth.userId) throw new ForbiddenException('You cannot change your own administrative level'); if (!['EMPLOYEE', 'COMPANY_ADMIN', 'TENANT_ADMIN'].includes(adminLevel)) throw new ConflictException('Invalid administrative level'); const target = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!target) throw new NotFoundException('User not found'); if (target.adminLevel === 'TENANT_ADMIN' && adminLevel !== 'TENANT_ADMIN') { const count = await this.db.user.count({ where: { tenantId: auth.tenantId, accountType: 'TENANT', adminLevel: 'TENANT_ADMIN', isActive: true } }); if (count <= 1) throw new ConflictException('The last active Tenant Admin cannot be demoted'); } const roleRows = await this.db.$queryRawUnsafe<any[]>(`SELECT id FROM roles WHERE tenant_id=$1::uuid AND company_id IS NULL AND name='Tenant Admin' LIMIT 1`, auth.tenantId); const roleId = roleRows[0]?.id ? String(roleRows[0].id) : null; if (adminLevel === 'TENANT_ADMIN' && !roleId) throw new NotFoundException('Tenant Admin role is not configured'); const ids = new Set(target.roleIds); if (adminLevel === 'TENANT_ADMIN' && roleId) ids.add(roleId); if (adminLevel !== 'TENANT_ADMIN' && roleId) ids.delete(roleId); return this.db.user.update({ where: { id: userId }, data: { adminLevel, roleIds: [...ids], authVersion: { increment: 1 } } }); }
  async sendAccessEmail(auth: AuthContext, userId: string, action: 'invite' | 'reset') { const user = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!user) throw new NotFoundException('User not found'); if (!user.isActive) throw new ConflictException('Cannot send access email to an inactive user'); const token = await this.invites.createInternalToken(user.id); const appUrl = (process.env.WEB_APP_URL ?? 'http://localhost:3000').replace(/\/$/, ''); const setupUrl = `${appUrl}/accept-invite?token=${encodeURIComponent(token.rawToken)}`; const result = await this.mail.sendTenantAccessEmail({ to: user.email, firstName: user.firstName ?? 'User', action, setupUrl, expiresAt: token.expiresAt }); return { ok: true, action, email: user.email, emailSent: result.sent, emailConfigured: this.mail.isEnabled(), setupUrl: result.sent ? undefined : setupUrl, expiresAt: token.expiresAt }; }
  async setActive(auth: AuthContext, userId: string, active: boolean) { const current = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!current) throw new NotFoundException('User not found'); if (!active && current.adminLevel === 'TENANT_ADMIN') { if (auth.adminLevel !== 'TENANT_ADMIN') throw new ForbiddenException('Only a Tenant Administrator can deactivate another Tenant Administrator'); const count = await this.db.user.count({ where: { tenantId: auth.tenantId, accountType: 'TENANT', adminLevel: 'TENANT_ADMIN', isActive: true } }); if (count <= 1) throw new ConflictException('The last active Tenant Admin cannot be deactivated'); } const updated = await this.db.user.update({ where: { id: userId }, data: { isActive: active, authVersion: { increment: 1 } } }); if (!active) await this.db.session.updateMany({ where: { userId, revokedAt: null }, data: { revokedAt: new Date(), revokedReason: 'admin_deactivated' } }); return this.safe(updated); }
  async sessions(auth: AuthContext, userId: string) { const user = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!user) throw new NotFoundException('User not found'); return this.db.session.findMany({ where: { userId }, orderBy: [{ lastSeenAt: 'desc' }, { createdAt: 'desc' }], select: { id: true, ipAddress: true, userAgent: true, approxLocation: true, lastSeenAt: true, expiresAt: true, revokedAt: true, revokedReason: true, createdAt: true } }); }
  async loginHistory(auth: AuthContext, userId: string) { const user = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!user) throw new NotFoundException('User not found'); return this.db.loginHistory.findMany({ where: { userId }, orderBy: { occurredAt: 'desc' }, take: 100 }); }
  async revokeSession(auth: AuthContext, userId: string, sessionId: string, actorUserId: string) { const user = await this.db.user.findFirst({ where: this.where(auth, userId) }); if (!user) throw new NotFoundException('User not found'); if (userId === actorUserId) throw new ConflictException('Your current session cannot be revoked from this screen'); const session = await this.db.session.updateMany({ where: { id: sessionId, userId, revokedAt: null }, data: { revokedAt: new Date(), revokedReason: 'admin_revoked' } }); if (!session.count) throw new NotFoundException('Active session not found'); return { ok: true, sessionId }; }
}
