'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertCircle, ArrowRight, Boxes, Building2, CheckCircle2, Clock3, FileWarning, Laptop, RefreshCw, ShieldCheck, TriangleAlert, Wrench, type LucideIcon } from 'lucide-react';
import { apiFetch } from '../../../lib/api-client';
import { useAuth } from '../../../lib/auth-context';
import { FEATURE_KEYS } from '../../../lib/feature-registry';
import { Card, EmptyState, ErrorState, MetricCard, PageHeader, StatusBadge, Button } from '../../../components/ui';

type Summary = { totals: { assets: number; assignedAssets: number; expiringWarranties: number; expiredWarranties: number; dueMaintenance: number; overdueMaintenance: number }; statusCounts: Record<string, number>; conditionCounts: Record<string, number> };
function label(value: string) { return value.replaceAll('_', ' '); }
function pct(value: number, total: number) { return total ? Math.round((value / total) * 100) : 0; }
type Stat = readonly [string, number, LucideIcon, 'neutral'|'primary'|'success'|'warning'|'danger'];

export default function DashboardPage() {
  const { hasFeature } = useAuth(); const [summary, setSummary] = useState<Summary | null>(null); const [companies, setCompanies] = useState<unknown[]>([]); const [types, setTypes] = useState<unknown[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { const [s,c,t] = await Promise.all([apiFetch('/assets/dashboard/summary'), apiFetch('/companies'), apiFetch('/assets/types')]); setSummary(s); setCompanies(Array.isArray(c)?c:[]); setTypes(Array.isArray(t)?t:[]); } catch(e) { setError(e instanceof Error?e.message:'Unable to load dashboard data.'); } finally { setLoading(false); } }
  useEffect(()=>{void load();},[]);
  const totals=summary?.totals; const statusEntries=useMemo(()=>Object.entries(summary?.statusCounts??{}).sort((a,b)=>b[1]-a[1]),[summary]); const conditionEntries=useMemo(()=>Object.entries(summary?.conditionCounts??{}).sort((a,b)=>b[1]-a[1]),[summary]); const statusTotal=statusEntries.reduce((s,[,v])=>s+v,0); const attention=(totals?.expiredWarranties??0)+(totals?.overdueMaintenance??0); const health=totals?.assets?Math.max(0,100-Math.round(attention/totals.assets*100)):100;
  const stats: Stat[]=[['Assets',totals?.assets??0,Laptop,'primary'],['Companies',companies.length,Building2,'info' as 'primary'],['Asset types',types.length,Boxes,'neutral'],['Assigned',totals?.assignedAssets??0,ShieldCheck,'success']];
  return <div className="space-y-7">
    <div className="rounded-3xl border border-slate-200 bg-gradient-to-br from-white via-white to-[var(--theme-primary-soft)]/45 p-6 shadow-sm sm:p-8"><PageHeader title="IT environment overview" description="A live view of your tenant's asset inventory, custody and operational attention points." /><div className="flex flex-wrap gap-2"><StatusBadge status={health>=90?'HEALTHY':health>=70?'WARNING':'OVERDUE'} label={`Environment ${health}%`} /><span className="rounded-full border border-slate-200 bg-white/80 px-3 py-1.5 text-xs font-medium text-slate-500">{totals?.assets??0} assets monitored</span><Button size="sm" variant="secondary" loading={loading} onClick={()=>void load()} icon={<RefreshCw size={15}/>}>Refresh</Button></div></div>
    {error&&<ErrorState title="Dashboard could not be loaded" message={error} onRetry={()=>void load()}/>} 
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([name,value,Icon,tone])=><MetricCard key={name} label={name} value={loading?'—':value} tone={tone} icon={<Icon size={20}/>}/>)}</div>
    <section><div className="mb-3 flex items-end justify-between"><div><h2 className="font-semibold text-slate-950">Operational attention</h2><p className="mt-1 text-xs text-slate-500">Items that may require administrator action.</p></div><Link href="/assets" className="text-xs font-semibold text-[var(--theme-link)] hover:underline">View assets <ArrowRight className="inline" size={13}/></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Warranty expiring',totals?.expiringWarranties??0,'Next 30 days','warning',Clock3],['Warranty expired',totals?.expiredWarranties??0,'Needs attention','danger',FileWarning],['Maintenance due',totals?.dueMaintenance??0,'Next 30 days','warning',Wrench],['Maintenance overdue',totals?.overdueMaintenance??0,'Needs attention','danger',TriangleAlert]].map(([name,value,hint,tone,Icon])=><Link key={String(name)} href="/assets"><Card tone={tone as 'warning'|'danger'} className="group p-5 transition duration-200 hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{name}</p><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/80 text-slate-600 shadow-sm"><Icon size={17}/></span></div><p className="mt-3 text-2xl font-bold text-slate-950">{loading?'—':value}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></Card></Link>)}</div></section>
    <div className="grid gap-6 lg:grid-cols-[1.35fr_0.65fr]"><Card className="overflow-hidden"><div className="flex items-center gap-2 border-b border-slate-200 bg-slate-50/80 px-5 py-4"><Activity size={18} className="text-[var(--theme-link)]"/><div><h2 className="font-semibold text-slate-900">Asset lifecycle</h2><p className="mt-0.5 text-xs text-slate-500">Current distribution across lifecycle states.</p></div></div><div className="p-5">{loading?<div className="space-y-4">{[1,2,3,4].map(i=><div key={i} className="animate-pulse"><div className="mb-2 h-3 w-28 rounded bg-slate-100"/><div className="h-2 rounded-full bg-slate-100"/></div>)}</div>:statusEntries.length===0?<EmptyState title="No asset lifecycle data yet" text="Assets will appear here as inventory is added."/>:<div className="space-y-4">{statusEntries.map(([state,count])=><div key={state}><div className="mb-1.5 flex justify-between text-xs"><span className="font-semibold text-slate-700">{label(state)}</span><span className="text-slate-500">{count} · {pct(count,statusTotal)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[var(--theme-primary)]" style={{width:`${pct(count,statusTotal)}%`}}/></div></div>)}</div>}</div></Card>
      <Card className="overflow-hidden"><div className="flex items-center gap-2 border-b border-slate-200 bg-slate-50/80 px-5 py-4"><TriangleAlert size={18} className="text-amber-600"/><div><h2 className="font-semibold text-slate-900">Condition</h2><p className="mt-0.5 text-xs text-slate-500">Current asset condition mix.</p></div></div><div className="p-5">{loading?<div className="h-40 animate-pulse rounded-xl bg-slate-100"/>:conditionEntries.length===0?<EmptyState title="No condition data yet"/>:<div className="space-y-3">{conditionEntries.map(([state,count])=><div key={state} className="flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[var(--theme-link)]" style={{width:`${pct(count,totals?.assets??0)}%`}}/></div><div className="w-28 text-right text-xs"><span className="font-semibold text-slate-700">{label(state)}</span><span className="ml-1 text-slate-400">{count}</span></div></div>)}</div>}</div></Card></div>
    <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><Wrench size={18} className="text-[var(--theme-link)]"/><div><h2 className="font-semibold text-slate-900">Quick actions</h2><p className="mt-0.5 text-xs text-slate-500">Jump directly to common administration tasks.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Manage assets','/assets','View, edit and manage your inventory'],['Manage companies','/companies','Maintain organizational entities'],...(hasFeature(FEATURE_KEYS.customRoles)?[['Review permissions','/roles','Manage tenant roles and access']]:[])].map(([title,href,text])=><Link key={title} href={href} className="group rounded-xl border border-slate-200 bg-white p-4 transition hover:-translate-y-0.5 hover:border-[var(--theme-primary)]/30 hover:bg-[var(--theme-primary-soft)]/40"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-800">{title}</p><ArrowRight size={15} className="text-slate-400 group-hover:text-[var(--theme-primary)]"/></div><p className="mt-1 text-xs text-slate-500">{text}</p></Link>)}</div></Card>
    {!loading&&summary&&<div className="flex items-center justify-center gap-2 pb-2 text-xs text-slate-400"><CheckCircle2 size={14} className="text-emerald-500"/>Dashboard data loaded successfully</div>}
  </div>;
}
