import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
import { EntitlementService } from '../billing/entitlement.service';
import { asPrismaJson } from '../../common/prisma-json';
export type AuditWriteInput={tenantId:string;companyId?:string;actorUserId?:string;action:string;targetType?:string;targetId?:string;metadata?:Record<string,unknown>;route?:string;method?:string;statusCode?:number;requestId?:string;ipAddress?:string;userAgent?:string};
export type AuditQuery={action?:string;targetType?:string;actorUserId?:string;from?:Date;to?:Date;limit?:number};
@Injectable() export class AuditService{constructor(private readonly prisma:PrismaService,private readonly entitlements:EntitlementService){}
async record(input:AuditWriteInput){if(!input.tenantId)return;const sensitive=/password|token|secret|authorization|cookie|refresh|access[_-]?token|private[_-]?key/i;const metadata:Record<string,unknown>={};for(const[k,v]of Object.entries(input.metadata??{})){if(sensitive.test(k))continue;metadata[k]=typeof v==='string'&&v.length>2000?v.slice(0,2000):v;}await this.prisma.withTenantContext(input.tenantId,input.companyId??null,tx=>tx.auditEvent.create({data:{tenantId:input.tenantId,companyId:input.companyId??null,actorUserId:input.actorUserId??null,action:input.action,targetType:input.targetType??null,targetId:input.targetId??null,metadata:asPrismaJson(metadata),result:null,route:input.route??null,method:input.method??null,statusCode:input.statusCode??null,requestId:input.requestId??null,ipAddress:input.ipAddress??null,userAgent:input.userAgent??null,occurredAt:new Date()}}));}
async purgeExpired(tenantId:string){const days=await this.entitlements.getNumber(tenantId,'audit_retention_days');if(days===null)return{deleted:0,retentionDays:null};const cutoff=new Date(Date.now()-days*86400000);const result=await this.prisma.withTenantContext(tenantId,null,tx=>tx.auditEvent.deleteMany({where:{tenantId,occurredAt:{lt:cutoff}}}));return{deleted:result.count,retentionDays:days,cutoff};}
async list(auth:AuthContext,q:AuditQuery={}){const where:any={tenantId:auth.tenantId,...(auth.crossCompany?{}:{companyId:auth.companyId})};if(q.action)where.action=q.action;if(q.targetType)where.targetType=q.targetType;if(q.actorUserId)where.actorUserId=q.actorUserId;if(q.from||q.to){where.occurredAt={};if(q.from)where.occurredAt.gte=q.from;if(q.to)where.occurredAt.lte=q.to;}return this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.auditEvent.findMany({where,orderBy:{occurredAt:'desc'},take:Math.min(Math.max(q.limit??200,1),1000)}));}
async summary(auth:AuthContext){const where:any={tenantId:auth.tenantId,...(auth.crossCompany?{}:{companyId:auth.companyId})};const [rows,total,today]=await Promise.all([this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.auditEvent.findMany({where,select:{action:true,targetType:true}})),this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.auditEvent.count({where})),this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.auditEvent.count({where:{...where,occurredAt:{gte:new Date(new Date().setHours(0,0,0,0))}}}))]);const actions=new Map<string,number>(),targets=new Map<string,number>();for(const r of rows){actions.set(r.action,(actions.get(r.action)??0)+1);const t=r.targetType??'unknown';targets.set(t,(targets.get(t)??0)+1);}return{total,today,topActions:[...actions.entries()].sort((a,b)=>b[1]-a[1]).slice(0,20).map(([action,count])=>({action,count})),byTargetType:[...targets.entries()].sort((a,b)=>b[1]-a[1]).map(([targetType,count])=>({targetType,count}))};}
async csv(auth:AuthContext){const events=await this.list(auth,{limit:1000});const esc=(v:unknown)=>`"${(v==null?'':typeof v==='string'?v:JSON.stringify(v)).replace(/"/g,'""')}"`;return[['occurredAt','action','targetType','targetId','actorUserId','requestId','metadata'].join(','),...events.map((e:any)=>[e.occurredAt,e.action,e.targetType,e.targetId,e.actorUserId,e.requestId,e.metadata].map(esc).join(','))].join('\n');}
}
