import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';

const TRIAL_DAYS = Number(process.env.LICENSE_TRIAL_DAYS ?? 14);
const THEME_PRESETS = ['trial', 'starter', 'professional', 'enterprise', 'restricted'] as const;
type ThemePreset = typeof THEME_PRESETS[number];

@Injectable()
export class SystemSubscriptionService {
  constructor(private readonly db: PrismaService) {}

  async listPlans(includeArchived = true) { const plans = await this.db.plan.findMany({ where: includeArchived ? undefined : { isActive: true }, orderBy: { name: 'asc' } }); return plans.map(p => this.planDto(p)); }
  private resolveTheme(plan: { themePreset: string; name: string }): ThemePreset { if ((THEME_PRESETS as readonly string[]).includes(plan.themePreset)) return plan.themePreset as ThemePreset; const n=plan.name.trim().toLowerCase(); if(n.includes('enterprise'))return'enterprise'; if(n.includes('professional')||n.includes('pro')||n.includes('business'))return'professional'; if(n.includes('trial')||n.includes('free'))return'trial'; return'starter'; }
  private planDto(plan:any){return{id:plan.id,name:plan.name,themePreset:this.resolveTheme(plan),features:plan.features??{},isActive:plan.isActive!==false,createdAt:plan.createdAt,updatedAt:plan.updatedAt};}
  async createPlan(name:string,features:Record<string,unknown>={},themePreset:ThemePreset='starter'){const normalizedName=name?.trim();if(!normalizedName)throw new BadRequestException('Plan name is required');if(!features||typeof features!=='object'||Array.isArray(features))throw new BadRequestException('Plan features must be an object');if(!(THEME_PRESETS as readonly string[]).includes(themePreset))throw new BadRequestException('Invalid theme preset');if(await this.db.plan.findUnique({where:{name:normalizedName}}))throw new ConflictException('A plan with this name already exists');const plan=await this.db.plan.create({data:{name:normalizedName,themePreset,features,isActive:true}});return this.planDto(plan);}
  async updatePlan(planId:string,name:string,features:Record<string,unknown>,themePreset:ThemePreset='starter'){const normalizedName=name?.trim();if(!planId)throw new BadRequestException('Invalid plan id');if(!normalizedName)throw new BadRequestException('Plan name is required');if(!features||typeof features!=='object'||Array.isArray(features))throw new BadRequestException('Plan features must be an object');if(!(THEME_PRESETS as readonly string[]).includes(themePreset))throw new BadRequestException('Invalid theme preset');const duplicate=await this.db.plan.findFirst({where:{name:normalizedName,NOT:{id:planId}}});if(duplicate)throw new ConflictException('A plan with this name already exists');const plan=await this.db.plan.update({where:{id:planId},data:{name:normalizedName,themePreset,features}}).catch(()=>null);if(!plan)throw new NotFoundException('Plan not found');await this.syncPlanEntitlements(plan.id,features);return this.planDto(plan);}
  async setPlanActive(planId:string,isActive:boolean){if(!planId)throw new BadRequestException('Invalid plan id');const plan=await this.db.plan.findUnique({where:{id:planId}});if(!plan)throw new NotFoundException('Plan not found');if(!isActive){const inUse=await this.db.subscription.count({where:{planId,status:{in:['active','trialing','past_due']}}});if(inUse)throw new ConflictException('Cannot archive a plan that is assigned to an active subscription');}const updated=await this.db.plan.update({where:{id:planId},data:{isActive}});return this.planDto(updated);}
  async overview(){const [plans,subscriptions]=await Promise.all([this.db.plan.findMany({where:{isActive:true},orderBy:{name:'asc'}}),this.db.subscription.findMany({where:{status:{not:'revoked'}},orderBy:{startedAt:'desc'}})]);return{plans:plans.map(p=>this.planDto(p)),subscriptions:subscriptions.map(s=>this.dto(s))};}
  async revokedTenants(){const subscriptions=await this.db.subscription.findMany({where:{status:'revoked'},orderBy:{startedAt:'desc'}});const tenantIds=[...new Set(subscriptions.map(s=>s.tenantId))];const planIds=[...new Set(subscriptions.map(s=>s.planId))];const [tenants,plans]=await Promise.all([this.db.tenant.findMany({where:{id:{in:tenantIds}},select:{id:true,name:true}}),this.db.plan.findMany({where:{id:{in:planIds}},select:{id:true,name:true}})]);const tm=new Map(tenants.map(t=>[t.id,t.name])),pm=new Map(plans.map(p=>[p.id,p.name]));return subscriptions.map(s=>({...this.dto(s),tenantName:tm.get(s.tenantId)??s.tenantId,planName:pm.get(s.planId)??s.planId}));}
  private async getTenantOrThrow(tenantId:string){if(!tenantId)throw new BadRequestException('Invalid tenant id');const t=await this.db.tenant.findUnique({where:{id:tenantId}});if(!t)throw new NotFoundException('Tenant not found');return t;}
  private async getPlanOrThrow(planId:string){if(!planId)throw new BadRequestException('Invalid plan id');const p=await this.db.plan.findUnique({where:{id:planId}});if(!p)throw new NotFoundException('Plan not found');if(p.isActive===false)throw new ConflictException('Plan is archived and cannot be assigned');return p;}
  private dto(s:any){return{id:s.id,tenantId:s.tenantId,planId:s.planId,status:s.status,startedAt:s.startedAt,endsAt:s.endsAt??null,graceUntil:s.graceUntil??null};}
  private async audit(tenantId:string,action:string,targetId:string,metadata:Record<string,unknown>,actorUserId?:string){await this.db.auditEvent.create({data:{tenantId,actorUserId:actorUserId??null,action,targetType:'subscription',targetId,metadata,occurredAt:new Date()}});}
  private async applyPlanEntitlements(subscriptionId:string,features:Record<string,unknown>){const existing=await this.db.entitlement.findMany({where:{subscriptionId}});const byKey=new Map(existing.map(e=>[e.key,e]));const keys=Object.keys(features);for(const [key,value] of Object.entries(features)){const current=byKey.get(key);if(!current)await this.db.entitlement.create({data:{subscriptionId,key,value,source:'plan'}});else if(current.source!=='override')await this.db.entitlement.update({where:{id:current.id},data:{value,source:'plan'}});}await this.db.entitlement.deleteMany({where:{subscriptionId,source:'plan',key:{notIn:keys}}});}
  private async syncPlanEntitlements(planId:string,features:Record<string,unknown>){const subscriptions=await this.db.subscription.findMany({where:{planId,status:{in:['active','trialing','past_due']}}});for(const s of subscriptions)await this.applyPlanEntitlements(s.id,features);}
  async assign(tenantId:string,planId:string,status='active',endsAt?:string,actorUserId?:string){await this.getTenantOrThrow(tenantId);const plan=await this.getPlanOrThrow(planId);const current=await this.db.subscription.findFirst({where:{tenantId},orderBy:{startedAt:'desc'}});let expiry=endsAt?new Date(endsAt):undefined;if(expiry&&Number.isNaN(expiry.getTime()))throw new BadRequestException('Invalid endsAt');if(status==='trialing'&&!expiry)expiry=new Date(Date.now()+TRIAL_DAYS*86400000);const subscription=current?await this.db.subscription.update({where:{id:current.id},data:{planId,status,endsAt:expiry??current.endsAt,graceUntil:null}}):await this.db.subscription.create({data:{tenantId,planId,status,startedAt:new Date(),endsAt:expiry}});await this.applyPlanEntitlements(subscription.id,(plan.features??{}) as Record<string,unknown>);await this.audit(tenantId,current?.status==='revoked'?'subscription.reactivated':current?'subscription.updated':'subscription.created',subscription.id,{planId,status,endsAt:subscription.endsAt??null},actorUserId);return this.dto(subscription);}
  async renew(tenantId:string,endsAt:string,actorUserId?:string){await this.getTenantOrThrow(tenantId);const expiry=new Date(endsAt);if(Number.isNaN(expiry.getTime())||expiry.getTime()<=Date.now())throw new BadRequestException('Renewal date must be in the future');const current=await this.db.subscription.findFirst({where:{tenantId},orderBy:{startedAt:'desc'}});if(!current)throw new NotFoundException('No subscription found for tenant');const subscription=await this.db.subscription.update({where:{id:current.id},data:{status:'active',endsAt:expiry,graceUntil:null}});await this.audit(tenantId,current.status==='revoked'?'subscription.reactivated':'subscription.renewed',subscription.id,{endsAt:expiry},actorUserId);return this.dto(subscription);}
  async setStatus(tenantId:string,status:'active'|'trialing'|'past_due'|'canceled'|'expired',actorUserId?:string){await this.getTenantOrThrow(tenantId);const current=await this.db.subscription.findFirst({where:{tenantId},orderBy:{startedAt:'desc'}});if(!current)throw new NotFoundException('No subscription found for tenant');const subscription=await this.db.subscription.update({where:{id:current.id},data:{status,...((status==='canceled'||status==='expired')?{endsAt:new Date(),graceUntil:null}:{})}});await this.audit(tenantId,`subscription.${status}`,subscription.id,{status},actorUserId);return this.dto(subscription);}
  async revoke(tenantId:string,actorUserId?:string){await this.getTenantOrThrow(tenantId);const current=await this.db.subscription.findFirst({where:{tenantId},orderBy:{startedAt:'desc'}});if(!current)throw new NotFoundException('No subscription found for tenant');const subscription=await this.db.subscription.update({where:{id:current.id},data:{status:'revoked',endsAt:new Date(),graceUntil:null}});await this.db.entitlement.deleteMany({where:{subscriptionId:current.id}});await this.audit(tenantId,'subscription.revoked',subscription.id,{planId:current.planId},actorUserId);return this.dto(subscription);}
  async setEntitlement(subscriptionId:string,key:string,value:unknown,actorUserId?:string){const subscription=await this.db.subscription.findUnique({where:{id:subscriptionId}});if(!subscription)throw new NotFoundException('Subscription not found');const normalizedKey=key.trim();if(!normalizedKey)throw new BadRequestException('Entitlement key is required');const entitlement=await this.db.entitlement.upsert({where:{subscriptionId_key:{subscriptionId,key:normalizedKey}},create:{subscriptionId,key:normalizedKey,value,source:'override'},update:{value,source:'override'}});await this.audit(subscription.tenantId,'subscription.entitlement_updated',subscriptionId,{key:normalizedKey,value,source:'override'},actorUserId);return{id:entitlement.id,subscriptionId,key:normalizedKey,value:entitlement.value};}
}
