import { Body, Controller, Get, NotFoundException, Param, Patch, Req, UseGuards } from '@nestjs/common';
import { SystemAdminGuard } from '../../common/guards/system-admin.guard';
import { SystemPermission } from '../../common/guards/system-permission.decorator';
import { PrismaService } from '../../common/database/prisma.service';
import { asPrismaJson } from '../../common/prisma-json';
import { SystemEntitlementAuditService } from './system-entitlement-audit.service';
@Controller('system/tenants/:tenantId/entitlements')
@UseGuards(SystemAdminGuard)
export class SystemEntitlementController {
  constructor(private readonly db: PrismaService, private readonly audit: SystemEntitlementAuditService) {}
  @Get() @SystemPermission('platform:billing:read') get(@Param('tenantId') tenantId: string) { return this.audit.getTenantEntitlements(tenantId); }
  @Get('history') @SystemPermission('platform:billing:read') history(@Param('tenantId') tenantId: string) { return this.audit.history(tenantId); }
  @Patch(':key') @SystemPermission('platform:billing:manage') async override(@Param('tenantId') tenantId:string,@Param('key') key:string,@Body() body:{value:unknown;reason?:string},@Req() req:any){const subscription=await this.db.subscription.findFirst({where:{tenantId},orderBy:{startedAt:'desc'}});if(!subscription)throw new NotFoundException('Tenant subscription not found');const previous=await this.db.entitlement.findUnique({where:{subscriptionId_key:{subscriptionId:subscription.id,key}}});const plan=await this.db.plan.findUnique({where:{id:subscription.planId}});const planValue=(plan?.features as Record<string,unknown>|null)?.[key];await this.db.entitlement.upsert({where:{subscriptionId_key:{subscriptionId:subscription.id,key}},create:{subscriptionId:subscription.id,key,value:asPrismaJson(body.value),source:'override'},update:{value:asPrismaJson(body.value),source:'override'}});await this.audit.recordChange(tenantId,req?.user?.userId??req?.user?.sub,{key,previousValue:previous?.value??planValue,newValue:body.value,source:'override',reason:body.reason?.trim()||undefined,subscriptionId:subscription.id});return this.audit.getTenantEntitlements(tenantId);}
  @Patch(':key/reset') @SystemPermission('platform:billing:manage') async reset(@Param('tenantId') tenantId:string,@Param('key') key:string,@Req() req:any){const subscription=await this.db.subscription.findFirst({where:{tenantId},orderBy:{startedAt:'desc'}});if(!subscription)throw new NotFoundException('Tenant subscription not found');const previous=await this.db.entitlement.findUnique({where:{subscriptionId_key:{subscriptionId:subscription.id,key}}});const plan=await this.db.plan.findUnique({where:{id:subscription.planId}});const planValue=(plan?.features as Record<string,unknown>|null)?.[key];if(previous?.source==='override'){if(planValue===undefined)await this.db.entitlement.delete({where:{id:previous.id}});else await this.db.entitlement.update({where:{id:previous.id},data:{value:asPrismaJson(planValue),source:'plan'}});await this.audit.recordChange(tenantId,req?.user?.userId??req?.user?.sub,{key,previousValue:previous.value,newValue:planValue,source:'plan',reason:'Reset tenant override to plan default',subscriptionId:subscription.id});}return this.audit.getTenantEntitlements(tenantId);}
}
