import { ForbiddenException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
import { EntitlementService } from '../billing/entitlement.service';

interface ZipEntry { name: string; data: Buffer; }
export interface AssetExcelReportFilters { status?: string; companyId?: string; assetTypeId?: string; locationId?: string; fromDate?: string; toDate?: string; }

@Injectable()
export class AssetExcelReportService {
  constructor(private readonly prisma: PrismaService, private readonly entitlements: EntitlementService) {}

  async generate(auth: AuthContext, filters: AssetExcelReportFilters = {}): Promise<Buffer> {
    await this.entitlements.requireFeature(auth.tenantId, 'advanced_reports_enabled');
    const where: any = { tenantId: auth.tenantId, ...(auth.crossCompany ? {} : { companyId: auth.companyId }) };
    if (filters.status) where.status = filters.status;
    if (filters.assetTypeId) where.assetTypeId = filters.assetTypeId;
    if (filters.locationId) where.locationId = filters.locationId;
    if (filters.companyId) { if (!auth.crossCompany && filters.companyId !== auth.companyId) throw new ForbiddenException('Company out of scope'); where.companyId = filters.companyId; }
    if (filters.fromDate || filters.toDate) { where.createdAt = {}; if (filters.fromDate) where.createdAt.gte = this.parseDate(filters.fromDate, 'fromDate'); if (filters.toDate) { const end = this.parseDate(filters.toDate, 'toDate'); end.setHours(23, 59, 59, 999); where.createdAt.lte = end; } }
    const assets = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.asset.findMany({ where, orderBy: { createdAt: 'desc' }, include: { assetType: { select: { name: true } }, location: { select: { name: true } }, department: { select: { name: true } }, assignments: { where: { returnedAt: null }, orderBy: { assignedAt: 'desc' }, take: 1, include: { user: { select: { email: true, firstName: true, lastName: true } } } } } }));
    const vendorIds = [...new Set(assets.map(a => a.vendorId).filter(Boolean))] as string[];
    const vendors = vendorIds.length ? await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.vendor.findMany({ where: { id: { in: vendorIds }, tenantId: auth.tenantId }, select: { id: true, name: true } })) : [];
    const vendorMap = new Map(vendors.map(v => [v.id, v.name]));
    const headers = ['Asset Number','Status','Asset Type','Company ID','Vendor','Location','Department','Assigned To','Warranty Provider','Warranty Expires','Created At','Asset ID'];
    const rows = assets.map(a => { const assignment = a.assignments[0]; const user = assignment?.user; return [a.assetNumber, a.status, a.assetType?.name ?? '', a.companyId, a.vendorId ? vendorMap.get(a.vendorId) ?? '' : '', a.location?.name ?? '', a.department?.name ?? '', user ? `${user.firstName ?? ''} ${user.lastName ?? ''}`.trim() || user.email : '', a.warrantyProvider ?? '', a.warrantyExpiresAt ? a.warrantyExpiresAt.toISOString().slice(0,10) : '', a.createdAt.toISOString(), a.id]; });
    const summary = [['AssetHub Asset Report',''],['Generated At',new Date().toISOString()],['Tenant ID',auth.tenantId],['Filters',this.filterSummary(filters)],['Total Assets',String(assets.length)],['',''],['Status','Count'],...this.countBy(assets.map(a => a.status))];
    return zip([{name:'[Content_Types].xml',data:Buffer.from(contentTypes())},{name:'_rels/.rels',data:Buffer.from(rootRels())},{name:'xl/workbook.xml',data:Buffer.from(workbook())},{name:'xl/_rels/workbook.xml.rels',data:Buffer.from(workbookRels())},{name:'xl/styles.xml',data:Buffer.from(styles())},{name:'xl/worksheets/sheet1.xml',data:Buffer.from(this.sheetXml(summary,7))},{name:'xl/worksheets/sheet2.xml',data:Buffer.from(this.sheetXml([headers,...rows],1,headers.length,rows.length+1))}]);
  }
  private parseDate(value:string,field:string){const d=new Date(value);if(Number.isNaN(d.getTime()))throw new ForbiddenException(`Invalid ${field}`);return d;}
  private filterSummary(filters:AssetExcelReportFilters){const active=Object.entries(filters).filter(([,v])=>v).map(([k,v])=>`${k}=${v}`);return active.length?active.join('; '):'None';}
  private countBy(values:string[]){const m=new Map<string,number>();for(const v of values)m.set(v,(m.get(v)??0)+1);return [...m.entries()].sort().map(([k,v])=>[k,String(v)]);}
  private sheetXml(rows:string[][],headerRow:number,filterCols?:number,filterRows?:number){const xml=rows.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>`<c r="${col(ci+1)}${ri+1}" s="${ri===headerRow-1?1:0}" t="inlineStr"><is><t xml:space="preserve">${esc(String(v??''))}</t></is></c>`).join('')}</row>`).join('');const filter=filterCols&&filterRows?`<autoFilter ref="A${headerRow}:${col(filterCols)}${filterRows}"/>`:'';return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="${headerRow}" topLeftCell="A${headerRow+1}" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>${xml}</sheetData>${filter}</worksheet>`;}
}
function col(n:number){let s='';while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26);}return s;}
function esc(v:string){return v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
function contentTypes(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`;}
function rootRels(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;}
function workbook(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Summary" sheetId="1" r:id="rId1"/><sheet name="Assets" sheetId="2" r:id="rId2"/></sheets></workbook>`;}
function workbookRels(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;}
function styles(){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" applyFont="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;}
function zip(entries:ZipEntry[]){const local:Buffer[]=[];const central:Buffer[]=[];let offset=0;for(const e of entries){const name=Buffer.from(e.name);const data=e.data;const crc=crc32(data);const lh=Buffer.alloc(30+name.length);lh.writeUInt32LE(0x04034b50,0);lh.writeUInt16LE(20,4);lh.writeUInt32LE(crc,14);lh.writeUInt32LE(data.length,18);lh.writeUInt32LE(data.length,22);lh.writeUInt16LE(name.length,26);name.copy(lh,30);local.push(lh,data);const ch=Buffer.alloc(46+name.length);ch.writeUInt32LE(0x02014b50,0);ch.writeUInt16LE(20,4);ch.writeUInt16LE(20,6);ch.writeUInt32LE(crc,16);ch.writeUInt32LE(data.length,20);ch.writeUInt32LE(data.length,24);ch.writeUInt16LE(name.length,28);ch.writeUInt32LE(offset,42);name.copy(ch,46);central.push(ch);offset+=lh.length+data.length;}const l=Buffer.concat(local),c=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(c.length,12);end.writeUInt32LE(l.length,16);return Buffer.concat([l,c,end]);}
function crc32(buf:Buffer){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
