import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
import { AssetDocumentsService } from './asset-documents.service';
import { TenantPdfBrandingService } from './tenant-pdf-branding.service';

const DEFAULT_CONTENT = `ASSET HANDOVER ACKNOWLEDGEMENT\n\nI, {{employee.name}} (Employee ID: {{employee.employeeId}}), acknowledge receipt of the following company asset:\n\nAsset: {{asset.assetNumber}}\nType: {{asset.type}}\nSerial Number: {{asset.serialNumber}}\nAssigned Date: {{assignment.date}}\n\nI confirm that the above asset has been issued to me for business use and I will take reasonable care of it, use it in accordance with company policy, and return it when requested or when my employment/assignment ends.\n\nEmployee Name: {{employee.name}}\nEmployee ID: {{employee.employeeId}}\nSignature: ______________________________\nDate: ____________________\n\nIssued By: {{issuer.name}}\nDate: {{assignment.date}}`;

@Injectable()
export class AssetAcknowledgementService {
  constructor(private readonly prisma: PrismaService, private readonly documents: AssetDocumentsService, private readonly branding: TenantPdfBrandingService) {}

  async listTemplates(auth: AuthContext) { return this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.findMany({ where: { tenantId: auth.tenantId }, orderBy: [{ isDefault: 'desc' }, { name: 'asc' }] })); }
  async ensureDefault(auth: AuthContext) { const existing = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.findFirst({ where: { tenantId: auth.tenantId, isDefault: true } })); if (existing) return existing; return this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.create({ data: { tenantId: auth.tenantId, name: 'Default asset acknowledgement', content: DEFAULT_CONTENT, createdBy: auth.userId, isDefault: true } })); }
  async createTemplate(auth: AuthContext, name: string, content: string) { const cleanName = String(name ?? '').trim(); const cleanContent = String(content ?? '').trim(); if (!cleanName || !cleanContent) throw new NotFoundException('Template name and content are required'); return this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.create({ data: { tenantId: auth.tenantId, name: cleanName, content: cleanContent, createdBy: auth.userId, isDefault: false } })); }
  async updateTemplate(auth: AuthContext, templateId: string, name: string, content: string) { const result = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.updateMany({ where: { id: templateId, tenantId: auth.tenantId }, data: { name: String(name ?? '').trim(), content: String(content ?? '').trim() } })); if (!result.count) throw new NotFoundException('Acknowledgement template not found'); return this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.findUniqueOrThrow({ where: { id: templateId } })); }
  async setDefault(auth: AuthContext, templateId: string) { const target = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.findFirst({ where: { id: templateId, tenantId: auth.tenantId } })); if (!target) throw new NotFoundException('Acknowledgement template not found'); return this.prisma.withTenantContext(auth.tenantId, auth.companyId, async tx => { await tx.assetAcknowledgementTemplate.updateMany({ where: { tenantId: auth.tenantId }, data: { isDefault: false } }); return tx.assetAcknowledgementTemplate.update({ where: { id: templateId }, data: { isDefault: true } }); }); }
  async deleteTemplate(auth: AuthContext, templateId: string) { const target = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.findFirst({ where: { id: templateId, tenantId: auth.tenantId } })); if (!target) throw new NotFoundException('Acknowledgement template not found'); if (target.isDefault) throw new ForbiddenException('Default acknowledgement template cannot be deleted'); await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.delete({ where: { id: templateId } })); return { ok: true }; }
  async listAcknowledgements(auth: AuthContext, assetId: string) { await this.requireAsset(auth, assetId); return this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgement.findMany({ where: { tenantId: auth.tenantId, companyId: auth.companyId, assetId }, orderBy: { generatedAt: 'desc' } })); }
  async latest(auth: AuthContext, assetId: string) { const rows = await this.listAcknowledgements(auth, assetId); return rows[0] ?? null; }

  async generate(auth: AuthContext, assetId: string, templateId?: string): Promise<{ buffer: Buffer; acknowledgementId: string; documentId: string }> {
    const asset = await this.requireAsset(auth, assetId);
    const assignment = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAssignment.findFirst({ where: { assetId, returnedAt: null }, orderBy: { assignedAt: 'desc' } }));
    if (!assignment?.userId) throw new NotFoundException('Asset has no active assignment');
    const employee = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.user.findFirst({ where: { id: assignment.userId, tenantId: auth.tenantId, companyId: auth.companyId } }));
    if (!employee) throw new NotFoundException('Assigned employee not found');
    const assetType = asset.assetTypeId ? await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetType.findFirst({ where: { id: asset.assetTypeId!, companyId: auth.companyId } })) : null;
    const issuer = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.user.findFirst({ where: { id: auth.userId, tenantId: auth.tenantId } }));
    const template = templateId ? await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgementTemplate.findFirst({ where: { id: templateId, tenantId: auth.tenantId } })) : await this.ensureDefault(auth);
    if (!template) throw new NotFoundException('Acknowledgement template not found');
    const employeeName = `${employee.firstName ?? ''} ${employee.lastName ?? ''}`.trim();
    const issuerName = `${issuer?.firstName ?? ''} ${issuer?.lastName ?? ''}`.trim();
    const values: Record<string, string> = { '{{employee.name}}': employeeName, '{{employee.employeeId}}': employee.id, '{{employee.email}}': employee.email, '{{employee.jobTitle}}': '', '{{asset.assetNumber}}': asset.assetNumber, '{{asset.type}}': assetType?.name ?? '', '{{asset.serialNumber}}': asset.serialNumber ?? '', '{{asset.model}}': asset.model ?? '', '{{assignment.date}}': assignment.assignedAt.toLocaleDateString(), '{{issuer.name}}': issuerName };
    const body = Object.entries(values).reduce((text, [token, value]) => text.split(token).join(value), template.content);
    const buffer = await this.branding.brand(auth.tenantId, buildPdf(body));
    const generatedAt = new Date(); const fileName = `asset-acknowledgement-${asset.assetNumber}-${generatedAt.toISOString().slice(0, 10)}.pdf`;
    const document = await this.documents.storeGeneratedPdf(auth, assetId, fileName, buffer, 'ACKNOWLEDGEMENT');
    try {
      const record = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgement.create({ data: { tenantId: auth.tenantId, companyId: auth.companyId, assetId, employeeId: employee.id, templateId: template.id, templateName: template.name, contentSnapshot: body, documentId: document.id, generatedAt, generatedByUserId: auth.userId, status: 'PENDING' } }));
      return { buffer, acknowledgementId: record.id, documentId: document.id };
    } catch (error) { await this.documents.remove(auth, assetId, document.id).catch(() => undefined); throw error; }
  }

  async download(auth: AuthContext, acknowledgementId: string) { const record = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgement.findFirst({ where: { id: acknowledgementId, tenantId: auth.tenantId, companyId: auth.companyId } })); if (!record) throw new NotFoundException('Acknowledgement not found'); if (!record.documentId) throw new NotFoundException('Acknowledgement PDF is not stored'); return this.documents.download(auth, record.assetId, record.documentId); }
  async acknowledge(auth: AuthContext, acknowledgementId: string, note?: string) { const record = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgement.findFirst({ where: { id: acknowledgementId, tenantId: auth.tenantId, companyId: auth.companyId } })); if (!record) throw new NotFoundException('Acknowledgement not found'); if (record.employeeId !== auth.userId) throw new ForbiddenException('Only the assigned employee can acknowledge this asset'); if (record.status === 'ACKNOWLEDGED') return record; const updated = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgement.updateMany({ where: { id: acknowledgementId, status: 'PENDING' }, data: { status: 'ACKNOWLEDGED', acknowledgedAt: new Date(), acknowledgedByUserId: auth.userId, acknowledgementNote: String(note ?? '').trim() || null } })); if (!updated.count) return this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgement.findUniqueOrThrow({ where: { id: acknowledgementId } })); return this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetAcknowledgement.findUniqueOrThrow({ where: { id: acknowledgementId } })); }

  private async requireAsset(auth: AuthContext, assetId: string) { const asset = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.asset.findFirst({ where: { id: assetId, tenantId: auth.tenantId, companyId: auth.companyId } })); if (!asset) throw new NotFoundException('Asset not found'); return asset; }
}

function buildPdf(content: string): Buffer { const lines = content.split(/\r?\n/).flatMap(line => wrap(line, 92)); const pageHeight = 842; const pageWidth = 595; const margin = 48; const lineHeight = 14; const maxLines = 50; const pages: string[][] = []; for (let i = 0; i < lines.length; i += maxLines) pages.push(lines.slice(i, i + maxLines)); if (!pages.length) pages.push(['']); const objects: string[] = ['']; objects.push('<< /Type /Catalog /Pages 2 0 R >>'); const fontObject = 3 + pages.length * 2; objects.push(`<< /Type /Pages /Kids [${pages.map((_, i) => `${4 + i * 2} 0 R`).join(' ')}] /Count ${pages.length} >>`); for (let i = 0; i < pages.length; i += 1) { const pageObj = 4 + i * 2; const contentObj = pageObj + 1; const commands = ['BT', '/F1 10 Tf', `${margin} ${pageHeight - 56} Td`]; pages[i].forEach((line, idx) => { if (idx > 0) commands.push(`0 -${lineHeight} Td`); commands.push(`(${pdfEscape(line)}) Tj`); }); commands.push('ET'); const stream = commands.join('\n'); objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 ${fontObject} 0 R >> >> /Contents ${contentObj} 0 R >>`); objects.push(`<< /Length ${Buffer.byteLength(stream, 'utf8')} >>\nstream\n${stream}\nendstream`); } objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'); const chunks: Buffer[] = [Buffer.from('%PDF-1.4\n')]; const offsets: number[] = [0]; let offset = chunks[0].length; for (let i = 1; i < objects.length; i += 1) { offsets[i] = offset; const obj = Buffer.from(`${i} 0 obj\n${objects[i]}\nendobj\n`); chunks.push(obj); offset += obj.length; } const xrefOffset = offset; const xref = ['xref', `0 ${objects.length}`, '0000000000 65535 f ']; for (let i = 1; i < objects.length; i += 1) xref.push(`${String(offsets[i]).padStart(10, '0')} 00000 n `); xref.push('trailer', `<< /Size ${objects.length} /Root 1 0 R >>`, 'startxref', String(xrefOffset), '%%EOF'); chunks.push(Buffer.from(`${xref.join('\n')}\n`)); return Buffer.concat(chunks); }
function wrap(text: string, width: number) { if (!text) return ['']; const words = text.split(/\s+/); const result: string[] = []; let line = ''; for (const word of words) { const next = line ? `${line} ${word}` : word; if (next.length > width && line) { result.push(line); line = word; } else line = next; } if (line) result.push(line); return result; }
function pdfEscape(value: string) { return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)').replace(/\r?\n/g, ' '); }
