import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
import { EntitlementService } from '../billing/entitlement.service';
import { AssetExcelReportFilters } from './asset-excel-report.service';
import { asPrismaJson } from '../../common/prisma-json';
export interface AssetReportTemplate { id: string; name: string; description?: string | null; filters: AssetExcelReportFilters; createdBy: string; createdAt?: Date; updatedAt?: Date; }
@Injectable()
export class AssetReportTemplateService {
  constructor(private readonly prisma: PrismaService, private readonly entitlements: EntitlementService) {}
  private async requireAccess(auth: AuthContext) { await this.entitlements.requireFeature(auth.tenantId, 'advanced_reports_enabled'); }
  async list(auth: AuthContext) { await this.requireAccess(auth); return this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetReportTemplate.findMany({ where: { tenantId: auth.tenantId }, orderBy: { name: 'asc' } })); }
  async create(auth: AuthContext, name: string, description: string | undefined, filters: AssetExcelReportFilters) { await this.requireAccess(auth); const cleanName=String(name??'').trim(); if(!cleanName)throw new BadRequestException('Template name is required'); if(cleanName.length>120)throw new BadRequestException('Template name cannot exceed 120 characters'); const normalized=this.normalizeFilters(filters); try{return await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetReportTemplate.create({data:{tenantId:auth.tenantId,name:cleanName,description:description?.trim()||null,filters:asPrismaJson(normalized),createdBy:auth.userId}}));}catch(e:any){if(e?.code==='P2002')throw new BadRequestException('A report template with this name already exists');throw e;} }
  async update(auth: AuthContext, templateId: string, name: string, description: string | undefined, filters: AssetExcelReportFilters) { await this.requireAccess(auth); const cleanName=String(name??'').trim(); if(!cleanName)throw new BadRequestException('Template name is required'); const duplicate=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetReportTemplate.findFirst({where:{tenantId:auth.tenantId,name:cleanName,id:{not:templateId}}})); if(duplicate)throw new BadRequestException('A report template with this name already exists'); const result=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetReportTemplate.updateMany({where:{id:templateId,tenantId:auth.tenantId},data:{name:cleanName,description:description?.trim()||null,filters:asPrismaJson(this.normalizeFilters(filters))}})); if(!result.count)throw new NotFoundException('Report template not found'); return this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetReportTemplate.findUniqueOrThrow({where:{id:templateId}})); }
  async remove(auth: AuthContext, templateId: string) { await this.requireAccess(auth); const result=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetReportTemplate.deleteMany({where:{id:templateId,tenantId:auth.tenantId}})); if(!result.count)throw new NotFoundException('Report template not found'); return {ok:true}; }
  async get(auth: AuthContext, templateId: string) { await this.requireAccess(auth); const doc=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetReportTemplate.findFirst({where:{id:templateId,tenantId:auth.tenantId}})); if(!doc)throw new NotFoundException('Report template not found'); return doc; }
  private normalizeFilters(filters:AssetExcelReportFilters={}){const allowed=['status','companyId','assetTypeId','locationId','fromDate','toDate'] as const;const normalized:AssetExcelReportFilters={};for(const key of allowed){const value=filters[key];if(value!==undefined&&value!==null&&String(value).trim()!=='')normalized[key]=String(value).trim();}if(normalized.fromDate&&normalized.toDate&&new Date(normalized.fromDate).getTime()>new Date(normalized.toDate).getTime())throw new BadRequestException('fromDate cannot be after toDate');return normalized;}
}
