import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
import { EntitlementService } from '../billing/entitlement.service';
import { DOCUMENT_STORAGE, DocumentStorage } from './document-storage';

const ALLOWED_TYPES = new Set(['application/pdf','image/jpeg','image/png','image/webp','text/plain','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/msword','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-excel']);
const ALLOWED_DOCUMENT_TYPES = new Set(['INVOICE','PURCHASE_ORDER','WARRANTY_CERTIFICATE','PHOTO','DISPOSAL_RECORD','OTHER','ACKNOWLEDGEMENT']);
const PLATFORM_MAX_FILE_BYTES = 25 * 1024 * 1024;
@Injectable()
export class AssetDocumentsService {
  constructor(private readonly prisma:PrismaService,private readonly entitlements:EntitlementService,@Inject(DOCUMENT_STORAGE)private readonly storage:DocumentStorage){}
  private async asset(auth:AuthContext,assetId:string){const a=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.asset.findFirst({where:{id:assetId,tenantId:auth.tenantId,companyId:auth.companyId}}));if(!a)throw new NotFoundException('Asset not found in your scope');return a;}
  private dto(d:any){return {...d,sizeBytes:d.sizeBytes===null||d.sizeBytes===undefined?d.sizeBytes:Number(d.sizeBytes)};}
  async list(auth:AuthContext,assetId:string){await this.asset(auth,assetId);const rows=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.findMany({where:{tenantId:auth.tenantId,companyId:auth.companyId,assetId},orderBy:{createdAt:'desc'}}));return rows.map(r=>this.dto(r));}
  async registerUpload(auth:AuthContext,assetId:string,input:{uuid:string;fileName:string;contentType:string;sizeBytes:number;documentType?:string}){await this.asset(auth,assetId);const fileName=String(input.fileName??'').trim(),contentType=String(input.contentType??'').trim().toLowerCase(),size=Number(input.sizeBytes);if(!input.uuid||!fileName||!ALLOWED_TYPES.has(contentType)||!Number.isFinite(size)||size<=0)throw new BadRequestException('Valid uploaded file metadata is required');this.assertType(input.documentType);const stored=await this.storage.register(input.uuid);try{const verifiedSize=Number(stored.sizeBytes);if(String(stored.contentType).toLowerCase()!==contentType||verifiedSize!==size)throw new BadRequestException('Uploaded file metadata does not match the verified file');await this.limits(auth,verifiedSize);const doc=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.create({data:{tenantId:auth.tenantId,companyId:auth.companyId,assetId,s3Key:stored.key,storageProvider:stored.provider,fileName:stored.fileName??fileName,contentType:stored.contentType??contentType,sizeBytes:BigInt(verifiedSize),documentType:input.documentType?.trim()||null}}));return this.dto(doc);}catch(e){await this.storage.remove(stored.key).catch(()=>undefined);throw e;}}
  async upload(auth:AuthContext,assetId:string,file:any,documentType?:string){await this.asset(auth,assetId);if(!file?.buffer?.length)throw new BadRequestException('Document file is required');const contentType=String(file.mimetype).toLowerCase();if(!ALLOWED_TYPES.has(contentType))throw new BadRequestException('Unsupported document type');this.assertType(documentType);const size=Number(file.size??file.buffer.length);await this.limits(auth,size);const fileName=String(file.originalname??'document').replace(/[\r\n]/g,'').trim()||'document';const stored=await this.storage.upload({buffer:file.buffer,fileName,contentType});try{const doc=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.create({data:{tenantId:auth.tenantId,companyId:auth.companyId,assetId,s3Key:stored.key,storageProvider:stored.provider,fileName:stored.fileName??fileName,contentType:stored.contentType??contentType,sizeBytes:BigInt(stored.sizeBytes??size),documentType:documentType?.trim()||null}}));return this.dto(doc);}catch(e){await this.storage.remove(stored.key).catch(()=>undefined);throw e;}}
  async storeGeneratedPdf(auth:AuthContext,assetId:string,fileName:string,buffer:Buffer,documentType='ACKNOWLEDGEMENT'){await this.asset(auth,assetId);this.assertType(documentType);await this.limits(auth,buffer.length);const stored=await this.storage.upload({buffer,fileName,contentType:'application/pdf'});try{const doc=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.create({data:{tenantId:auth.tenantId,companyId:auth.companyId,assetId,s3Key:stored.key,storageProvider:stored.provider,fileName:stored.fileName??fileName,contentType:stored.contentType??'application/pdf',sizeBytes:BigInt(stored.sizeBytes??buffer.length),documentType}}));return this.dto(doc);}catch(e){await this.storage.remove(stored.key).catch(()=>undefined);throw e;}}
  async download(auth:AuthContext,assetId:string,documentId:string){await this.asset(auth,assetId);const doc=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.findFirst({where:{id:documentId,tenantId:auth.tenantId,companyId:auth.companyId,assetId}}));if(!doc)throw new NotFoundException('Document not found');const stored=await this.storage.download(doc.s3Key);return {buffer:stored.buffer,fileName:doc.fileName,contentType:doc.contentType??stored.contentType??'application/octet-stream'};}
  async remove(auth:AuthContext,assetId:string,documentId:string){await this.asset(auth,assetId);const doc=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.findFirst({where:{id:documentId,tenantId:auth.tenantId,companyId:auth.companyId,assetId}}));if(!doc)throw new NotFoundException('Document not found');await this.storage.remove(doc.s3Key);await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.delete({where:{id:doc.id}}));return {ok:true};}
  private async limits(auth:AuthContext,incoming:number){if(incoming>PLATFORM_MAX_FILE_BYTES)throw new BadRequestException('Document exceeds the 25 MB platform limit');const max=await this.entitlements.getNumber(auth.tenantId,'max_asset_document_size_mb');if(max!==null&&incoming>max*1024*1024)throw new BadRequestException(`Document exceeds the ${Math.floor(max)} MB size limit`);const count=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.count({where:{tenantId:auth.tenantId}}));await this.entitlements.requireWithinLimit(auth.tenantId,'max_asset_documents',count,1);const docs=await this.prisma.withTenantContext(auth.tenantId,auth.companyId,tx=>tx.assetDocument.findMany({where:{tenantId:auth.tenantId},select:{sizeBytes:true}}));const current=docs.reduce((sum,d)=>sum+Number(d.sizeBytes??0),0);const maxGb=await this.entitlements.getNumber(auth.tenantId,'max_storage_gb');if(maxGb!==null&&current+incoming>maxGb*1024*1024*1024)throw new ConflictException('Tenant storage limit reached');}
  private assertType(t?:string){if(t&&!ALLOWED_DOCUMENT_TYPES.has(t.trim().toUpperCase()))throw new BadRequestException('Invalid document type');}
}
