import { Body, Controller, Delete, ForbiddenException, Get, Header, Param, Patch, Post, Query, Req, UseGuards } from '@nestjs/common';
import { Type } from 'class-transformer'; import { IsIn, IsInt, IsISO8601, IsObject, IsOptional, IsString, Min } from 'class-validator';
import { AssetCondition, AssetLifecycleState } from '../../common/enums';
import { AssetsService } from './assets.service'; import { AssetImportService } from './asset-import.service'; import { AssetExcelReportService } from './asset-excel-report.service'; import { AssetPdfReportService } from './asset-pdf-report.service'; import { AssetTransferService } from './asset-transfer.service'; import { AssetAssignmentTransactionService } from './asset-assignment-transaction.service'; import { AssetTimelineService } from './asset-timeline.service'; import { AssetSearchService } from './asset-search.service'; import { AssetListService } from './asset-list.service'; import { AssetDetailService } from './asset-detail.service';
import { TenantContextGuard } from '../../common/guards/tenant-context.guard'; import { RbacGuard } from '../../common/guards/rbac.guard'; import { FeatureGuard } from '../../common/guards/feature.guard'; import { RequirePermission } from '../../common/decorators/require-permission.decorator'; import { RequireFeature } from '../../common/decorators/require-feature.decorator';
class CreateAssetDto{@IsString()assetTypeId:string;@IsOptional()@IsString()companyId?:string;@IsOptional()@IsString()locationId?:string;@IsOptional()@IsString()departmentId?:string;@IsOptional()@IsString()vendorId?:string;@IsOptional()@IsIn(Object.values(AssetCondition))condition?:AssetCondition;@IsOptional()@IsString()serialNumber?:string;@IsOptional()@IsString()model?:string;@IsObject()@IsOptional()fields?:Record<string,unknown>}
class AssignAssetDto{@IsString()userId:string;@IsString()@IsOptional()notes?:string} class ReturnAssetDto{@IsString()@IsOptional()notes?:string;@IsOptional()@IsIn(Object.values(AssetCondition))condition?:AssetCondition} class ConditionDto{@IsIn(Object.values(AssetCondition))condition!:AssetCondition} class TransitionDto{@IsIn(Object.values(AssetLifecycleState))toState:AssetLifecycleState;@IsString()@IsOptional()reason?:string} class VendorDto{@IsString()name:string;@IsOptional()@IsString()contact?:string} class ImportCsvDto{@IsString()csv:string} class ExcelReportQueryDto{@IsOptional()@IsString()status?:string;@IsOptional()@IsString()companyId?:string;@IsOptional()@IsString()assetTypeId?:string;@IsOptional()@IsString()locationId?:string;@IsOptional()@IsString()departmentId?:string;@IsOptional()@IsISO8601()fromDate?:string;@IsOptional()@IsISO8601()toDate?:string} class AssetListQueryDto{@IsOptional()@IsString()q?:string;@IsOptional()@IsString()status?:string;@IsOptional()@IsString()assetTypeId?:string;@IsOptional()@Type(()=>Number)@IsInt()@Min(1)page?:number;@IsOptional()@Type(()=>Number)@IsInt()@Min(1)pageSize?:number;@IsOptional()@IsString()sortBy?:string;@IsOptional()@IsIn(['asc','desc'])sortDir?:'asc'|'desc'} class TransferDto{@IsOptional()@IsString()toUserId?:string;@IsOptional()@IsString()toLocationId?:string;@IsOptional()@IsString()toDepartmentId?:string;@IsOptional()@IsString()reason?:string;@IsOptional()@IsString()note?:string} class TransferStatusDto{@IsIn(['PENDING','APPROVED','COMPLETED','REJECTED','CANCELLED'])status!:'PENDING'|'APPROVED'|'COMPLETED'|'REJECTED'|'CANCELLED'}
@Controller('assets')@UseGuards(TenantContextGuard,RbacGuard,FeatureGuard)
export class AssetsController{
 constructor(private readonly assets:AssetsService,private readonly imports:AssetImportService,private readonly excelReports:AssetExcelReportService,private readonly pdfReports:AssetPdfReportService,private readonly transfers:AssetTransferService,private readonly assignmentTransactions:AssetAssignmentTransactionService,private readonly timeline:AssetTimelineService,private readonly searchService:AssetSearchService,private readonly listService:AssetListService,private readonly detail:AssetDetailService){}
 private companyAuth(auth:any,requested?:string){if(requested&&requested!==auth.companyId&&!auth.crossCompany)throw new ForbiddenException('Company out of scope for this user');return requested?{...auth,companyId:requested}:auth;}
 @Get('search')@RequirePermission('asset:read')search(@Query('q')q:string,@Req()r:any){return this.searchService.search(r.authContext,q??'');}
 @Get()@RequirePermission('asset:read')list(@Query()q:AssetListQueryDto,@Req()r:any){return this.listService.list(r.authContext,q);}
 @Get('assignments')@RequirePermission('asset:read')listAssignments(@Req()r:any){return this.assets.listAssignments(r.authContext);}
 @Get('transfers')@RequirePermission('asset:read')listTransfers(@Query()q:TransferStatusDto,@Req()r:any){return this.transfers.list(r.authContext,q.status);}
 @Get('transfers/:transferId')@RequirePermission('asset:read')getTransfer(@Param('transferId')id:string,@Req()r:any){return this.transfers.get(r.authContext,id);}
 @Get('dashboard/summary')@RequirePermission('asset:read')dashboard(@Req()r:any){return this.assets.getReportSummary(r.authContext);}
 @Get('reports/summary')@RequirePermission('asset:read')@RequireFeature('advanced_reports_enabled')summary(@Req()r:any){return this.assets.getReportSummary(r.authContext);}
 @Get('reports/excel')@RequirePermission('asset:read')@RequireFeature('advanced_reports_enabled')@Header('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')@Header('Content-Disposition','attachment; filename="assethub-asset-report.xlsx"')excel(@Query()q:ExcelReportQueryDto,@Req()r:any){return this.excelReports.generate(r.authContext,q);}
 @Get('reports/pdf')@RequirePermission('asset:read')@RequireFeature('advanced_reports_enabled')@Header('Content-Type','application/pdf')@Header('Content-Disposition','attachment; filename="assethub-asset-report.pdf"')pdf(@Query()q:ExcelReportQueryDto,@Req()r:any){return this.pdfReports.generate(r.authContext,q);}
 @Get('vendors')@RequirePermission('asset:read')vendors(@Query('companyId')companyId:string|undefined,@Req()r:any){return this.assets.listVendors(this.companyAuth(r.authContext,companyId));}
 @Post('vendors')@RequirePermission('asset:write')createVendor(@Body()d:VendorDto,@Req()r:any){return this.assets.createVendor(r.authContext,d.name,d.contact);}
 @Patch('vendors/:vendorId')@RequirePermission('asset:write')updateVendor(@Param('vendorId')id:string,@Body()d:VendorDto,@Req()r:any){return this.assets.updateVendor(r.authContext,id,d.name,d.contact);}
 @Delete('vendors/:vendorId')@RequirePermission('asset:write')deleteVendor(@Param('vendorId')id:string,@Req()r:any){return this.assets.deleteVendor(r.authContext,id);}
 @Get('warranties')@RequirePermission('asset:read')warranties(@Req()r:any){return this.assets.listWarranties(r.authContext);}
 @Get('types')@RequirePermission('asset:read')types(@Query('companyId')companyId:string|undefined,@Req()r:any){return this.assets.listAssetTypes(this.companyAuth(r.authContext,companyId));}
 @Delete('types/:assetTypeId')@RequirePermission('asset:write')deleteType(@Param('assetTypeId')id:string,@Req()r:any){return this.assets.deleteAssetType(r.authContext,id);}
 @Post('import/preview')@RequirePermission('asset:write')preview(@Body()d:ImportCsvDto,@Req()r:any){return this.imports.preview(r.authContext,d.csv);}
 @Post('import')@RequirePermission('asset:write')commit(@Body()d:ImportCsvDto,@Req()r:any){return this.imports.commit(r.authContext,d.csv);}
 @Post(':assetId/transfer')@RequirePermission('asset:write')requestTransfer(@Param('assetId')id:string,@Body()d:TransferDto,@Req()r:any){return this.transfers.request(r.authContext,id,d);}
 @Post('transfers/:transferId/approve')@RequirePermission('asset:write')approve(@Param('transferId')id:string,@Body()d:TransferDto,@Req()r:any){return this.transfers.approve(r.authContext,id,d.note);}
 @Post('transfers/:transferId/reject')@RequirePermission('asset:write')reject(@Param('transferId')id:string,@Body()d:TransferDto,@Req()r:any){return this.transfers.reject(r.authContext,id,d.note);}
 @Post('transfers/:transferId/complete')@RequirePermission('asset:write')complete(@Param('transferId')id:string,@Body()d:TransferDto,@Req()r:any){return this.transfers.complete(r.authContext,id,d.note);}
 @Post('transfers/:transferId/cancel')@RequirePermission('asset:write')cancel(@Param('transferId')id:string,@Body()d:TransferDto,@Req()r:any){return this.transfers.cancel(r.authContext,id,d.note);}
 @Post()@RequirePermission('asset:write')create(@Body()d:CreateAssetDto,@Req()r:any){const auth=this.companyAuth(r.authContext,d.companyId);return this.assets.createAsset(auth,d.assetTypeId,{...(d.fields??{}),locationId:d.locationId,departmentId:d.departmentId,vendorId:d.vendorId,condition:d.condition,serialNumber:d.serialNumber,model:d.model});}
 @Get(':assetId')@RequirePermission('asset:read')get(@Param('assetId')id:string,@Req()r:any){return this.detail.get(r.authContext,id);}
 @Patch(':assetId/condition')@RequirePermission('asset:write')condition(@Param('assetId')id:string,@Body()d:ConditionDto,@Req()r:any){return this.assets.updateCondition(r.authContext,id,d.condition);}
 @Post(':assetId/assign')@RequirePermission('asset:write')assign(@Param('assetId')id:string,@Body()d:AssignAssetDto,@Req()r:any){return this.assignmentTransactions.assign(r.authContext,id,d.userId,d.notes);}
 @Get(':assetId/assignment')@RequirePermission('asset:read')current(@Param('assetId')id:string,@Req()r:any){return this.assets.getCurrentAssignment(r.authContext,id);}
 @Post(':assetId/unassign')@RequirePermission('asset:write')unassign(@Param('assetId')id:string,@Body()d:ReturnAssetDto,@Req()r:any){return this.assignmentTransactions.unassign(r.authContext,id,d.notes,d.condition);}
 @Get(':assetId/assignment/history')@RequirePermission('asset:read')history(@Param('assetId')id:string,@Req()r:any){return this.assets.listAssignmentHistory(r.authContext,id);}
 @Get(':assetId/lifecycle')@RequirePermission('asset:read')lifecycle(@Param('assetId')id:string,@Req()r:any){return this.assets.allowedLifecycleTransitions(r.authContext,id);}
 @Get(':assetId/timeline')@RequirePermission('asset:read')timelineView(@Param('assetId')id:string,@Req()r:any){return this.timeline.get(r.authContext,id);}
 @Post(':assetId/transition')@RequirePermission('asset:write')transition(@Param('assetId')id:string,@Body()d:TransitionDto,@Req()r:any){return this.assets.transitionState(r.authContext,id,d.toState,r.authContext.userId,d.reason);}
}
