import { BadRequestException, ConflictException, ForbiddenException, Injectable } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
import { EntitlementService } from '../billing/entitlement.service';
import { AssetCondition, AssetLifecycleState } from '../../common/enums';
import { asPrismaJson } from '../../common/prisma-json';

interface ImportRow { line: number; assetTypeId: string; locationId?: string; departmentId?: string; vendorId?: string; serialNumber?: string; model?: string; condition?: AssetCondition; fields: Record<string, unknown>; }

@Injectable()
export class AssetImportService {
  constructor(private readonly prisma: PrismaService, private readonly entitlements: EntitlementService) {}
  async preview(auth: AuthContext, csv: string) {
    await this.entitlements.requireFeature(auth.tenantId, 'bulk_import_enabled'); const rows = await this.validateRows(auth, this.parseCsv(csv)); const current = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.asset.count({ where: { tenantId: auth.tenantId } })); await this.entitlements.requireWithinLimit(auth.tenantId, 'max_assets', current, rows.length); const serials = rows.map(r => r.serialNumber).filter(Boolean) as string[]; const existing = serials.length ? await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.asset.findMany({ where: { tenantId: auth.tenantId, serialNumber: { in: serials } }, select: { serialNumber: true } })) : []; const existingSet = new Set(existing.map(x => String(x.serialNumber))); const seen = new Set<string>(); const warnings: any[] = []; for (const row of rows) { if (row.serialNumber && existingSet.has(row.serialNumber)) warnings.push({ line: row.line, code: 'SERIAL_EXISTS', message: `Serial number ${row.serialNumber} already exists.` }); if (row.serialNumber && seen.has(row.serialNumber)) warnings.push({ line: row.line, code: 'SERIAL_DUPLICATE_IN_FILE', message: `Serial number ${row.serialNumber} appears more than once in this import.` }); if (row.serialNumber) seen.add(row.serialNumber); if (!row.condition) warnings.push({ line: row.line, code: 'CONDITION_DEFAULT', message: 'Condition not provided; GOOD will be used.' }); } return { rowCount: rows.length, currentAssets: current, projectedAssets: current + rows.length, warnings, rows: rows.map(row => ({ ...row, locationId: row.locationId ?? null, departmentId: row.departmentId ?? null, vendorId: row.vendorId ?? null, serialNumber: row.serialNumber ?? null, model: row.model ?? null, condition: row.condition ?? AssetCondition.GOOD })) };
  }
  async commit(auth: AuthContext, csv: string) {
    await this.entitlements.requireFeature(auth.tenantId, 'bulk_import_enabled'); const rows = await this.validateRows(auth, this.parseCsv(csv)); if (!rows.length) throw new BadRequestException('CSV contains no data rows'); const result = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, async tx => { const current = await tx.asset.count({ where: { tenantId: auth.tenantId } }); await this.entitlements.requireWithinLimit(auth.tenantId, 'max_assets', current, rows.length); const company = await tx.company.findFirst({ where: { id: auth.companyId, tenantId: auth.tenantId } }); if (!company) throw new BadRequestException('Company not found'); const grouped = new Map<string, ImportRow[]>(); for (const row of rows) grouped.set(row.assetTypeId, [...(grouped.get(row.assetTypeId) ?? []), row]); const assetNumbers = new Map<number, string>(); for (const [assetTypeId, groupedRows] of grouped) { const type = await tx.assetType.findFirst({ where: { id: assetTypeId, companyId: auth.companyId } }); if (!type) throw new BadRequestException(`Line ${groupedRows[0].line}: asset type is unavailable`); const previous = type.nextSequence; const updated = await tx.assetType.updateMany({ where: { id: assetTypeId, companyId: auth.companyId, nextSequence: previous }, data: { nextSequence: { increment: groupedRows.length } } }); if (!updated.count) throw new ConflictException('Asset numbering sequence changed during import; retry the import'); groupedRows.forEach((row, index) => assetNumbers.set(row.line, `${type.prefix ?? 'AST'}${type.separator ?? '-'}${company.code}${type.separator ?? '-'}${String(previous + index).padStart(type.padding ?? 6, '0')}`)); } const created = []; for (const row of rows) created.push(await tx.asset.create({ data: { tenantId: auth.tenantId, companyId: auth.companyId, assetTypeId: row.assetTypeId, assetNumber: assetNumbers.get(row.line)!, status: AssetLifecycleState.IN_STOCK, condition: row.condition ?? AssetCondition.GOOD, serialNumber: row.serialNumber ?? null, model: row.model ?? null, locationId: row.locationId ?? null, departmentId: row.departmentId ?? null, vendorId: row.vendorId ?? null, barcodeValue: assetNumbers.get(row.line)!, customFields: asPrismaJson(row.fields) } })); return { imported: created.length, assets: created }; }); return { ok: true, ...result };
  }
  private async validateRows(auth: AuthContext, rows: ImportRow[]) { if (!rows.length) throw new BadRequestException('CSV contains no data rows'); if (rows.length > 5000) throw new BadRequestException('Import batch cannot exceed 5000 rows'); const assetTypes = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.assetType.findMany({ where: { companyId: auth.companyId } })); const assetTypeMap = new Map(assetTypes.map(x => [x.id, x])); for (const row of rows) { if (!assetTypeMap.has(row.assetTypeId)) throw new BadRequestException(`Line ${row.line}: assetTypeId is not in your company`); if (row.condition && !Object.values(AssetCondition).includes(row.condition)) throw new BadRequestException(`Line ${row.line}: invalid condition`); if (row.locationId) { const location = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.location.findFirst({ where: { id: row.locationId!, site: { tenantId: auth.tenantId, companyId: auth.companyId } } })); if (!location) throw new BadRequestException(`Line ${row.line}: locationId not found or outside your scope`); if (row.departmentId) { const department = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.department.findFirst({ where: { id: row.departmentId!, locationId: row.locationId! } })); if (!department) throw new BadRequestException(`Line ${row.line}: departmentId does not belong to locationId`); } } else if (row.departmentId) { const department = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.department.findFirst({ where: { id: row.departmentId!, location: { site: { tenantId: auth.tenantId, companyId: auth.companyId } } } })); if (!department) throw new ForbiddenException(`Line ${row.line}: department is outside your scope`); } if (row.vendorId) { const vendor = await this.prisma.withTenantContext(auth.tenantId, auth.companyId, tx => tx.vendor.findFirst({ where: { id: row.vendorId!, companyId: auth.companyId } })); if (!vendor) throw new BadRequestException(`Line ${row.line}: vendorId is not in your company`); } } return rows; }
  private parseCsv(input: string): ImportRow[] { const text = String(input ?? '').replace(/^\uFEFF/, '').trim(); if (!text) return []; const matrix = this.parseCsvMatrix(text); if (matrix.length < 2) return []; const headers = matrix[0].map(value => value.trim()); if (!headers.includes('assetTypeId')) throw new BadRequestException('CSV header missing required column: assetTypeId'); return matrix.slice(1).map((cells, index) => { const values: Record<string, string> = {}; headers.forEach((header, column) => { values[header] = (cells[column] ?? '').trim(); }); let fields: Record<string, unknown> = {}; if (values.fieldsJson) { try { const parsed = JSON.parse(values.fieldsJson); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error(); fields = parsed; } catch { throw new BadRequestException(`Line ${index + 2}: fieldsJson must be valid JSON object`); } } const condition = values.condition ? String(values.condition).toUpperCase() as AssetCondition : undefined; return { line: index + 2, assetTypeId: values.assetTypeId, locationId: values.locationId || undefined, departmentId: values.departmentId || undefined, vendorId: values.vendorId || undefined, serialNumber: values.serialNumber || undefined, model: values.model || undefined, condition, fields }; }).filter(row => row.assetTypeId); }
  private parseCsvMatrix(input: string): string[][] { const rows: string[][] = []; let row: string[] = [], cell = '', quoted = false; for (let i = 0; i < input.length; i++) { const ch = input[i]; if (ch === '"') { if (quoted && input[i + 1] === '"') { cell += '"'; i++; } else quoted = !quoted; } else if (ch === ',' && !quoted) { row.push(cell); cell = ''; } else if ((ch === '\n' || ch === '\r') && !quoted) { if (ch === '\r' && input[i + 1] === '\n') i++; row.push(cell); cell = ''; if (row.some(v => v.trim())) rows.push(row); row = []; } else cell += ch; } row.push(cell); if (row.some(v => v.trim())) rows.push(row); return rows; }
}
