'use client';

import { AlertTriangle, CheckCircle2, ChevronDown, Copy, Loader2, ShieldCheck, Sparkles, Upload } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button, Badge } from './ui';
import { useToast } from './toast';

export function RiskBadge({ score, label }: { score: number; label?: string }) {
  const tone = score >= 80 ? 'success' : score >= 60 ? 'warning' : 'danger'; const text = label ?? (score >= 80 ? 'Healthy' : score >= 60 ? 'Attention' : 'High risk');
  return <Badge tone={tone}><span className={`mr-1.5 inline-block h-1.5 w-1.5 rounded-full ${tone==='success'?'bg-emerald-500':tone==='warning'?'bg-amber-500':'bg-red-500'}`}/>{text} · {score}</Badge>;
}

export function ActivityTimeline({ items }: { items: { id:string; time:string; title:string; description?:string; tone?:'neutral'|'success'|'warning'|'danger' }[] }) { return <div className="relative space-y-0">{items.map((item,index)=><div key={item.id} className="relative flex gap-4 pb-6 last:pb-0"><div className="relative flex w-5 shrink-0 justify-center"><span className={`mt-1.5 h-2.5 w-2.5 rounded-full ring-4 ring-white ${item.tone==='success'?'bg-emerald-500':item.tone==='warning'?'bg-amber-500':item.tone==='danger'?'bg-red-500':'bg-[var(--theme-primary)]'}`}/>{index<items.length-1?<span className="absolute top-4 h-full w-px bg-slate-200"/>:null}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-900">{item.title}</p><span className="text-[10px] font-medium text-slate-400">{item.time}</span></div>{item.description?<p className="mt-1 text-xs leading-5 text-slate-500">{item.description}</p>:null}</div></div>)}</div>; }

export function EffectiveAccessPreview({ role, groups }: { role:string; groups:{name:string; permissions:string[]; scope?:string}[] }) { const total=groups.reduce((sum,g)=>sum+g.permissions.length,0); return <section className="panel overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-200 bg-gradient-to-r from-violet-50 to-white px-5 py-4"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white text-violet-600 shadow-sm"><ShieldCheck size={17}/></div><div><h3 className="text-sm font-semibold text-slate-950">Effective access</h3><p className="text-xs text-slate-500">What <strong>{role}</strong> can actually do · {total} permissions</p></div></div><div className="divide-y divide-slate-100">{groups.map(group=><div key={group.name} className="p-5"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-slate-900">{group.name}</p>{group.scope?<span className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{group.scope}</span>:null}</div><div className="mt-3 flex flex-wrap gap-2">{group.permissions.map(permission=><span key={permission} className="rounded-full border border-violet-100 bg-violet-50 px-2.5 py-1 text-xs font-semibold text-violet-700">{permission}</span>)}</div></div>)}</div></section>; }

export function BulkActionBar({ selected, total, actions }: { selected:number; total?:number; actions:{label:string;danger?:boolean;onClick:()=>void;loading?:boolean}[] }) { if(!selected)return null; return <div className="sticky bottom-4 z-30 mx-auto flex max-w-5xl flex-wrap items-center gap-2 rounded-2xl border border-slate-200 bg-slate-950 px-3 py-2.5 text-white shadow-2xl motion-pop"><div className="mr-auto flex items-center gap-2 px-2 text-xs font-semibold"><span className="grid h-7 min-w-7 place-items-center rounded-lg bg-white/10 px-1.5">{selected}</span>{total?`of ${total} selected`:'selected'}</div>{actions.map(action=><button key={action.label} type="button" onClick={action.onClick} disabled={action.loading} className={`rounded-xl px-3 py-2 text-xs font-semibold transition ${action.danger?'bg-red-500/15 text-red-100 hover:bg-red-500/25':'bg-white/10 text-white hover:bg-white/15'}`}>{action.loading?<Loader2 size={13} className="mr-1 inline animate-spin"/>:null}{action.label}</button>)}</div>; }

export function ColumnVisibility({ columns, value, onChange }: { columns:{key:string;label:string}[]; value:string[]; onChange:(keys:string[])=>void }) { const [open,setOpen]=useState(false); return <div className="relative"><button type="button" onClick={()=>setOpen(v=>!v)} className="field inline-flex h-10 items-center gap-2 px-3 text-sm font-semibold"><span>Columns</span><ChevronDown size={14}/></button>{open?<div className="absolute right-0 top-12 z-40 w-60 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><p className="px-2 py-1.5 text-[10px] font-bold uppercase tracking-wider text-slate-400">Visible columns</p>{columns.map(column=><label key={column.key} className="flex cursor-pointer items-center gap-2 rounded-xl px-2 py-2 text-xs font-medium text-slate-700 hover:bg-slate-50"><input type="checkbox" checked={value.includes(column.key)} onChange={e=>onChange(e.target.checked?[...value,column.key]:value.filter(k=>k!==column.key))}/>{column.label}</label>)}</div>:null}</div>; }

export function ImportWizard({ steps=['Upload','Map','Validate','Review','Import'], onComplete }:{steps?:string[];onComplete?:()=>void}) { const [step,setStep]=useState(0); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const {toast}=useToast(); const next=()=>{if(step<steps.length-1)setStep(step+1);else{setBusy(true);window.setTimeout(()=>{setBusy(false);toast({title:'Import completed',message:'The inventory import workflow finished successfully.',tone:'success'});onComplete?.()},700)}}; return <section className="panel overflow-hidden"><div className="border-b border-slate-200 bg-gradient-to-r from-slate-50 to-white px-5 py-4"><div className="flex flex-wrap items-center gap-2">{steps.map((name,index)=><div key={name} className="flex items-center gap-2"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${index<=step?'bg-[var(--theme-primary)] text-white':'bg-slate-100 text-slate-400'}`}>{index<step?<CheckCircle2 size={14}/>:index+1}</span><span className={`text-xs font-semibold ${index===step?'text-slate-900':'text-slate-400'}`}>{name}</span>{index<steps.length-1?<span className="mx-1 h-px w-5 bg-slate-200 sm:w-10"/>:null}</div>)}</div></div><div className="p-6">{step===0?<label className="flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-slate-50/70 text-center hover:border-[var(--theme-primary)] hover:bg-[var(--theme-primary-soft)]"><Upload size={24} className="text-slate-400"/><p className="mt-3 text-sm font-semibold text-slate-800">Upload inventory file</p><p className="mt-1 text-xs text-slate-500">CSV or spreadsheet export</p><input type="file" className="sr-only" onChange={e=>setFile(e.target.files?.[0]??null)}/>{file?<span className="mt-3 text-xs font-semibold text-[var(--theme-link)]">{file.name}</span>:null}</label>:<div className="rounded-2xl bg-slate-50 p-5"><div className="flex items-start gap-3"><Sparkles className="mt-0.5 text-[var(--theme-link)]" size={18}/><div><p className="text-sm font-semibold text-slate-900">{steps[step]} stage</p><p className="mt-1 text-xs leading-5 text-slate-500">Review the current import stage before continuing. Existing backend validation remains authoritative.</p></div></div></div>}<div className="mt-5 flex justify-end gap-2"><Button variant="secondary" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>Back</Button><Button loading={busy} disabled={step===0&&!file} onClick={next}>{step===steps.length-1?'Import':`Continue to ${steps[step+1]}`}</Button></div></div></section>; }

export function CopyField({ value, label='Copy value' }: { value:string; label?:string }) { const {toast}=useToast(); return <button type="button" title={label} onClick={()=>{void navigator.clipboard.writeText(value).then(()=>toast({title:'Copied',message:label,tone:'success'})).catch(()=>toast({title:'Copy failed',message:'Clipboard access unavailable.',tone:'error'}))}} className="inline-flex max-w-full items-center gap-2 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-mono text-slate-700 hover:bg-slate-50"><span className="truncate">{value}</span><Copy size={13}/></button>; }

export function ConnectionBanner(){const [online,setOnline]=useState(true);useEffect(()=>{const update=()=>setOnline(navigator.onLine);update();window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[]);return online?null:<div role="alert" className="sticky top-0 z-[1250] flex items-center gap-2 border-b border-red-200 bg-red-50 px-4 py-2 text-xs font-semibold text-red-800"><AlertTriangle size={14}/>Connection interrupted. Reconnect before retrying important changes.</div>; }

export function UnsavedChangesGuard({ dirty }: { dirty:boolean }) { useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(!dirty)return;e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]); return null; }
