'use client';

import { Bell, Check, Command, Globe2, Search, X } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

const NAV = [
  ['Dashboard','/dashboard'],['Assets','/assets'],['Asset Types','/asset-types'],['Assignments','/assignments'],['Transfers','/assets/transfers'],['Employees','/employees'],['Companies','/companies'],['Locations','/locations'],['Departments','/business-units'],['Roles & Permissions','/roles'],['Identity & SSO','/identity'],['Audit Logs','/audit'],['Settings','/settings'],
] as const;

type Notification = { id:string; title:string; text:string; time:string; read:boolean; tone:'info'|'success'|'warning'|'danger' };
const seed: Notification[] = [
  {id:'welcome',title:'AssetHub ready',text:'Your operations workspace is ready to use.',time:'Now',read:false,tone:'info'},
];

export function ProductivityHub(){
  const [searchOpen,setSearchOpen]=useState(false); const [query,setQuery]=useState(''); const [noticeOpen,setNoticeOpen]=useState(false);
  const [notifications,setNotifications]=useState<Notification[]>(()=>{try{const raw=localStorage.getItem('assethub.notifications');return raw?JSON.parse(raw):seed;}catch{return seed;}});
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true);} if(e.key==='Escape'){setSearchOpen(false);setNoticeOpen(false);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
  useEffect(()=>{try{localStorage.setItem('assethub.notifications',JSON.stringify(notifications))}catch{}},[notifications]);
  const filtered=useMemo(()=>NAV.filter(([label])=>label.toLowerCase().includes(query.trim().toLowerCase())),[query]);
  const unread=notifications.filter(n=>!n.read).length;
  return <>
    <div className="flex items-center gap-1">
      <button type="button" onClick={()=>setSearchOpen(true)} className="hidden h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-500 shadow-sm transition hover:border-slate-300 hover:text-slate-700 lg:flex" aria-label="Search AssetHub"><Search size={15}/><span>Search</span><kbd className="rounded-md bg-slate-100 px-1.5 py-0.5 font-mono text-[10px]">Ctrl K</kbd></button>
      <button type="button" onClick={()=>setSearchOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl text-slate-500 hover:bg-[var(--theme-primary-soft)]" aria-label="Search AssetHub"><Search size={17}/></button>
      <div className="relative"><button type="button" onClick={()=>setNoticeOpen(v=>!v)} className="relative grid h-10 w-10 place-items-center rounded-xl text-slate-500 hover:bg-[var(--theme-primary-soft)]" aria-label="Notifications"><Bell size={17}/>{unread>0?<span className="absolute right-1.5 top-1.5 grid h-4 min-w-4 place-items-center rounded-full bg-[var(--theme-primary)] px-1 text-[9px] font-bold text-white">{unread>9?'9+':unread}</span>:null}</button>{noticeOpen?<NotificationPanel items={notifications} onRead={(id)=>setNotifications(x=>x.map(n=>n.id===id?{...n,read:true}:n))} onReadAll={()=>setNotifications(x=>x.map(n=>({...n,read:true})))} onClose={()=>setNoticeOpen(false)}/>:null}</div>
    </div>
    {searchOpen?<SearchOverlay query={query} setQuery={setQuery} results={filtered} onClose={()=>{setSearchOpen(false);setQuery('')}}/>:null}
  </>;
}

function SearchOverlay({query,setQuery,results,onClose}:{query:string;setQuery:(v:string)=>void;results:readonly (readonly [string,string])[];onClose:()=>void}){
  return <div className="fixed inset-0 z-[1300] bg-slate-950/45 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="mx-auto mt-[8vh] w-full max-w-2xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl motion-pop" role="dialog" aria-modal="true" aria-label="Search AssetHub"><div className="flex items-center gap-3 border-b border-slate-200 px-4 py-3"><Search size={18} className="text-slate-400"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search modules, actions or pages…" className="h-11 flex-1 bg-transparent text-sm outline-none"/><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl text-slate-400 hover:bg-slate-100" aria-label="Close search"><X size={16}/></button></div><div className="p-2">{results.length?<div className="grid gap-1">{results.map(([label,href])=><Link key={href} href={href} onClick={onClose} className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-medium text-slate-700 transition hover:bg-[var(--theme-primary-soft)] hover:text-[var(--theme-link)]"><Command size={15}/><span>{label}</span><span className="ml-auto text-xs text-slate-400">Open</span></Link>)}</div>:<div className="p-8 text-center text-sm text-slate-500">No matching workspace found.</div>}</div></section></div>
}

function NotificationPanel({items,onRead,onReadAll,onClose}:{items:Notification[];onRead:(id:string)=>void;onReadAll:()=>void;onClose:()=>void}){
  return <div className="absolute right-0 top-12 z-[1200] w-[min(92vw,380px)] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl motion-pop"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><p className="text-sm font-semibold text-slate-950">Notifications</p><p className="text-[11px] text-slate-500">Recent platform activity</p></div><div className="flex items-center gap-1"><button type="button" onClick={onReadAll} className="rounded-lg px-2 py-1 text-[11px] font-semibold text-[var(--theme-link)] hover:bg-[var(--theme-primary-soft)]">Mark all read</button><button type="button" onClick={onClose} className="grid h-8 w-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100" aria-label="Close notifications"><X size={15}/></button></div></div><div className="max-h-[60vh] overflow-y-auto">{items.length?items.map(item=><button key={item.id} type="button" onClick={()=>onRead(item.id)} className={`flex w-full items-start gap-3 border-b border-slate-100 px-4 py-3 text-left transition hover:bg-slate-50 ${item.read?'opacity-65':'bg-[var(--theme-primary-soft)]/30'}`}><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${item.tone==='danger'?'bg-red-500':item.tone==='warning'?'bg-amber-500':item.tone==='success'?'bg-emerald-500':'bg-[var(--theme-primary)]'}`}/><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-sm font-semibold text-slate-900">{item.title}{!item.read?<span className="rounded-full bg-white px-1.5 py-0.5 text-[9px] font-bold text-[var(--theme-link)] shadow-sm">NEW</span>:null}</span><span className="mt-0.5 block text-xs leading-5 text-slate-500">{item.text}</span><span className="mt-1 block text-[10px] text-slate-400">{item.time}</span></span>{item.read?<Check size={14} className="mt-1 text-emerald-500"/>:null}</button>):<div className="p-8 text-center text-sm text-slate-500">You're all caught up.</div>}</div></div>
}

export function NetworkStatus(){const [online,setOnline]=useState(true);useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync)}},[]);return <span className={`hidden items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-semibold sm:inline-flex ${online?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-red-200 bg-red-50 text-red-700'}`} title={online?'Connection available':'Connection interrupted'}><Globe2 size={12}/>{online?'Online':'Offline'}</span>}

export function SavedViews({scope}:{scope:string}){const key=`assethub.savedviews.${scope}`;const [views,setViews]=useState<string[]>([]);const [name,setName]=useState('');useEffect(()=>{try{setViews(JSON.parse(localStorage.getItem(key)||'[]'))}catch{}},[key]);const add=()=>{const v=name.trim();if(!v)return;const next=Array.from(new Set([...views,v])).slice(-12);setViews(next);setName('');try{localStorage.setItem(key,JSON.stringify(next))}catch{}};const remove=(v:string)=>{const next=views.filter(x=>x!==v);setViews(next);try{localStorage.setItem(key,JSON.stringify(next))}catch{}};return <div className="flex flex-wrap items-center gap-2"><select aria-label="Saved views" className="field h-10 min-w-40" defaultValue=""><option value="">Saved views</option>{views.map(v=><option key={v} value={v}>{v}</option>)}</select><details className="relative"><summary className="field flex h-10 cursor-pointer list-none items-center px-3 text-sm font-semibold">Save current view</summary><div className="absolute right-0 top-12 z-30 w-72 rounded-2xl border border-slate-200 bg-white p-3 shadow-xl"><div className="flex gap-2"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')add()}} className="field min-w-0 flex-1" placeholder="View name"/><button type="button" onClick={add} className="btn-primary">Save</button></div>{views.length?<div className="mt-3 space-y-1">{views.map(v=><div key={v} className="flex items-center justify-between rounded-lg px-2 py-1.5 text-xs text-slate-600 hover:bg-slate-50"><span className="truncate">{v}</span><button type="button" onClick={()=>remove(v)} className="text-slate-400 hover:text-red-600" aria-label={`Delete ${v}`}>×</button></div>)}</div>:null}</div></details></div>}
