'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarClock, Play, Plus, RefreshCw, Save, ShieldCheck, Trash2, Pause } from 'lucide-react';
import { systemFetch } from '../../../lib/system-api';
import { Button, EmptyState, ErrorState, LoadingState } from '../../../components/ui';
import { ConfirmDialog } from '../../../components/confirm-dialog';
import { FormField, FormSelect } from '../../../components/form-field';
import { useToast } from '../../../components/toast';

type Tenant = { id: string; name: string; slug?: string; subscriptionStatus?: string; planId?: string | null; endsAt?: string | null };
type Plan = { id: string; name: string; features?: Record<string, unknown> };
type Subscription = { id: string; tenantId: string; planId: string; status: string; startedAt?: string; endsAt?: string | null };
const statuses = ['active', 'trialing', 'past_due', 'canceled'] as const;

export default function SystemSubscriptionsPage() {
  const { toast } = useToast();
  const [tenants,setTenants]=useState<Tenant[]>([]),[plans,setPlans]=useState<Plan[]>([]),[subscriptions,setSubscriptions]=useState<Subscription[]>([]);
  const [selectedTenantId,setSelectedTenantId]=useState(''),[planId,setPlanId]=useState(''),[status,setStatus]=useState('active'),[endsAt,setEndsAt]=useState('');
  const [entitlementKey,setEntitlementKey]=useState(''),[entitlementValue,setEntitlementValue]=useState('');
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[action,setAction]=useState(''),[error,setError]=useState('');
  const [revokeOpen,setRevokeOpen]=useState(false);

  async function load(){setLoading(true);setError('');try{const [tenantData,billingData]=await Promise.all([systemFetch('/system/tenants'),systemFetch('/system/subscriptions')]);const nextTenants=Array.isArray(tenantData)?tenantData:[];setTenants(nextTenants);setPlans(Array.isArray(billingData?.plans)?billingData.plans:[]);setSubscriptions(Array.isArray(billingData?.subscriptions)?billingData.subscriptions:[]);if(!selectedTenantId&&nextTenants[0])setSelectedTenantId(nextTenants[0].id)}catch(e:any){setError(e?.message??'Unable to load license data.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const selectedTenant=useMemo(()=>tenants.find(t=>t.id===selectedTenantId)??null,[tenants,selectedTenantId]);
  const subscription=useMemo(()=>subscriptions.find(s=>s.tenantId===selectedTenantId)??null,[subscriptions,selectedTenantId]);
  useEffect(()=>{setPlanId(subscription?.planId??'');setStatus(subscription?.status??'active');setEndsAt(subscription?.endsAt?new Date(subscription.endsAt).toISOString().slice(0,10):'');setEntitlementKey('');setEntitlementValue('')},[subscription?.id]);

  async function assignOrUpdate(){if(!selectedTenantId||!planId)return;setSaving(true);setError('');try{await systemFetch(`/system/subscriptions/${selectedTenantId}`,{method:'PATCH',body:JSON.stringify({planId,status,endsAt:endsAt?new Date(`${endsAt}T23:59:59`).toISOString():undefined})});toast({title:subscription?'License updated':'License assigned',message:selectedTenant?.name,tone:'success'});await load()}catch(e:any){setError(e?.message??'Unable to save license.')}finally{setSaving(false)}}
  async function renew(){if(!selectedTenantId||!endsAt)return;setAction('renew');setError('');try{await systemFetch(`/system/subscriptions/${selectedTenantId}/renew`,{method:'POST',body:JSON.stringify({endsAt:new Date(`${endsAt}T23:59:59`).toISOString()})});toast({title:'License renewed',message:selectedTenant?.name,tone:'success'});await load()}catch(e:any){setError(e?.message??'Unable to renew license.')}finally{setAction('')}}
  async function changeStatus(nextStatus:string){if(!selectedTenantId||!subscription)return;setAction(nextStatus);setError('');try{await systemFetch(`/system/subscriptions/${selectedTenantId}/status`,{method:'PATCH',body:JSON.stringify({status:nextStatus})});toast({title:'License status updated',message:nextStatus,tone:'success'});await load()}catch(e:any){setError(e?.message??'Unable to change license status.')}finally{setAction('')}}
  async function revoke(){if(!selectedTenantId||!subscription)return;setAction('revoke');setError('');try{await systemFetch(`/system/subscriptions/${selectedTenantId}`,{method:'DELETE'});toast({title:'License revoked',message:selectedTenant?.name,tone:'success'});setRevokeOpen(false);await load()}catch(e:any){setError(e?.message??'Unable to revoke license.')}finally{setAction('')}}
  async function saveEntitlement(){if(!subscription||!entitlementKey.trim())return;setAction('entitlement');setError('');let value:unknown=entitlementValue;try{value=JSON.parse(entitlementValue)}catch{}try{await systemFetch(`/system/subscriptions/${selectedTenantId}/entitlement/${subscription.id}`,{method:'PATCH',body:JSON.stringify({key:entitlementKey.trim(),value})});toast({title:'Entitlement saved',tone:'success'});setEntitlementKey('');setEntitlementValue('')}catch(e:any){setError(e?.message??'Unable to save entitlement.')}finally{setAction('')}}

  if(loading)return <LoadingState label="Loading tenant licenses…" rows={8}/>;
  if(error&&tenants.length===0)return <ErrorState title="Unable to load tenant licenses" message={error} onRetry={()=>void load()}/>;
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">Platform</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Tenant Licenses</h1><p className="mt-2 text-sm text-slate-500">Assign, edit, renew, suspend, reactivate, and revoke tenant subscriptions.</p></div><Button variant="secondary" onClick={()=>void load()} loading={loading} icon={<RefreshCw size={15}/>}>Refresh</Button></header>
    {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
      <section className="panel p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-blue-600"/><h2 className="font-semibold text-slate-950">Tenants</h2></div><div className="mt-4 space-y-2">{tenants.length===0?<EmptyState title="No tenants found" text="Create a tenant before assigning a license."/>:tenants.map(t=><button type="button" key={t.id} onClick={()=>setSelectedTenantId(t.id)} className={`w-full rounded-xl border p-4 text-left ui-interactive ${t.id===selectedTenantId?'border-blue-300 bg-blue-50/60':'border-slate-200 bg-white hover:bg-slate-50'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{t.name}</p><p className="mt-1 text-xs text-slate-500">{t.slug??t.id}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold text-slate-700">{t.subscriptionStatus??'unlicensed'}</span></div></button>)}</div></section>
      <section className="space-y-5">{!selectedTenant?<EmptyState title="Select a tenant" text="Choose a tenant to manage its license."/>:<>
        <section className="panel p-6"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-600">License management</p><h2 className="mt-1 text-xl font-bold text-slate-950">{selectedTenant.name}</h2><p className="mt-1 text-xs text-slate-500">Tenant ID: {selectedTenant.id}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${subscription?.status==='active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-700'}`}>{subscription?.status??'unlicensed'}</span></div><div className="mt-6 grid gap-4 md:grid-cols-3"><FormSelect label="Plan" id="subscription-plan" value={planId} onChange={e=>setPlanId(e.target.value)} required><option value="">Select plan</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</FormSelect><FormSelect label="Status" id="subscription-status" value={status} onChange={e=>setStatus(e.target.value)} required>{statuses.map(s=><option key={s} value={s}>{s}</option>)}</FormSelect><FormField label="Expiry" id="subscription-expiry" type="date" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={()=>void assignOrUpdate()} disabled={!planId||saving} loading={saving} icon={<Save size={15}/>}>{subscription?'Save changes':'Assign license'}</Button>{subscription&&<><Button variant="secondary" onClick={()=>void renew()} disabled={!endsAt||action!==''} loading={action==='renew'} icon={<CalendarClock size={15}/>}>Renew</Button>{subscription.status==='active'?<Button variant="secondary" onClick={()=>void changeStatus('canceled')} disabled={action!==''} loading={action==='canceled'} icon={<Pause size={15}/>}>Suspend</Button>:<Button variant="secondary" onClick={()=>void changeStatus('active')} disabled={action!==''} loading={action==='active'} icon={<Play size={15}/>}>Reactivate</Button>}<Button variant="danger" onClick={()=>setRevokeOpen(true)} disabled={action!==''} icon={<Trash2 size={15}/>}>Revoke license</Button></>}</div></section>
        {subscription&&<section className="panel p-6"><div className="flex items-center gap-2"><Plus className="h-5 w-5 text-blue-600"/><h2 className="font-semibold text-slate-950">Edit entitlement</h2></div><p className="mt-1 text-sm text-slate-500">Store a feature flag or limit override. Values can be JSON or plain text.</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1.4fr_auto]"><FormField label="Key" id="entitlement-key" value={entitlementKey} onChange={e=>setEntitlementKey(e.target.value)} placeholder="max_assets"/><FormField label="Value" id="entitlement-value" value={entitlementValue} onChange={e=>setEntitlementValue(e.target.value)} placeholder="1000, true, or enterprise"/><div className="self-end"><Button className="w-full md:w-auto" onClick={()=>void saveEntitlement()} disabled={!entitlementKey.trim()||action!==''} loading={action==='entitlement'} icon={<Plus size={15}/>}>Save</Button></div></div></section>}
        <div className="grid gap-4 md:grid-cols-3"><div className="panel p-5"><p className="text-xs uppercase tracking-wide text-slate-500">Plan</p><p className="mt-2 font-semibold text-slate-950">{plans.find(p=>p.id===subscription?.planId)?.name??'Unlicensed'}</p></div><div className="panel p-5"><p className="text-xs uppercase tracking-wide text-slate-500">Started</p><p className="mt-2 font-semibold text-slate-950">{subscription?.startedAt?new Date(subscription.startedAt).toLocaleDateString():'—'}</p></div><div className="panel p-5"><p className="text-xs uppercase tracking-wide text-slate-500">Ends</p><p className="mt-2 font-semibold text-slate-950">{subscription?.endsAt?new Date(subscription.endsAt).toLocaleDateString():'No expiry'}</p></div></div>
      </>}</section>
    </div>
    <ConfirmDialog open={revokeOpen} title="Revoke tenant license" message={selectedTenant?`Revoke the current license for ${selectedTenant.name}? This removes the current subscription and its entitlements.`:undefined} confirmLabel="Revoke license" danger loading={action==='revoke'} onCancel={()=>action!=='revoke'&&setRevokeOpen(false)} onConfirm={()=>void revoke()}/>
  </div>;
}
