'use client';

import { useEffect, useMemo, useState } from 'react';
import { ShieldCheck, RefreshCw, Search, UserCheck, UserX, Building2 } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import { apiFetch } from '../../../lib/api-client';
import CompanyScopeControl from '../../../components/company-scope-control';
import { Alert, Badge, Button, EmptyState, ErrorState, LoadingState, StatusBadge } from '../../../components/ui';
import { ConfirmDialog } from '../../../components/confirm-dialog';

type Admin={id:string;employeeId?:string;email:string;firstName:string;lastName:string;jobTitle?:string;companyId?:string;isActive:boolean;adminLevel?:'EMPLOYEE'|'COMPANY_ADMIN'|'TENANT_ADMIN'};
type Company={id:string;name:string;code?:string};

export default function TenantAdminsPage(){
 const params=useSearchParams(), companyFilter=params.get('companyId');
 const [admins,setAdmins]=useState<Admin[]>([]),[companies,setCompanies]=useState<Company[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[demoteTarget,setDemoteTarget]=useState<Admin|null>(null);
 async function load(){setLoading(true);setError(null);try{const [rows,org]=await Promise.all([apiFetch('/users/tenant-admins'),apiFetch('/companies/hierarchy')]);setAdmins(Array.isArray(rows)?rows:[]);setCompanies(Array.isArray(org)?org.map((c:any)=>({id:String(c.id),name:String(c.name),code:c.code?String(c.code):undefined})):[])}catch(e:any){setError(e?.message??'Unable to load Tenant Administrators.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const companyName=(id?:string)=>companies.find(c=>c.id===id)?.name??(id||'Tenant-wide');
 const scoped=useMemo(()=>companyFilter&&companyFilter!=='all'?admins.filter(a=>a.companyId===companyFilter):admins,[admins,companyFilter]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return !q?scoped:scoped.filter(a=>`${a.firstName} ${a.lastName} ${a.email} ${a.employeeId??''} ${a.jobTitle??''} ${companyName(a.companyId)}`.toLowerCase().includes(q))},[scoped,query,companies]);
 async function demote(){if(!demoteTarget)return;const admin=demoteTarget;setBusy(admin.id);setError(null);setMessage(null);try{await apiFetch(`/users/${admin.id}/admin-level`,{method:'PATCH',body:JSON.stringify({adminLevel:'EMPLOYEE'})});setMessage(`${admin.firstName} ${admin.lastName} is now an Employee.`);setDemoteTarget(null);await load()}catch(e:any){setError(e?.message??'Unable to remove Tenant Admin access.')}finally{setBusy(null)}}
 const scopeText=companyFilter&&companyFilter!=='all'?companyName(companyFilter):'All companies';
 return <div className="mx-auto max-w-[1500px] space-y-6 page-section-enter">
  <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]"><ShieldCheck size={14}/>People & Organization</div><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold tracking-tight text-slate-950">Tenant Administrators</h1><Badge tone="brand">Tenant-wide authority</Badge><CompanyScopeControl/></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Dedicated administrative identities with authority across the tenant. They are intentionally separated from ordinary Employees.</p></div><Button variant="secondary" loading={loading} onClick={()=>void load()} icon={<RefreshCw size={15}/>}>Refresh</Button></header>
  <div className="grid gap-3 sm:grid-cols-3"><div className="panel p-4"><div className="text-xs font-medium text-slate-500">Current scope</div><div className="mt-1 flex items-center gap-2 font-semibold text-slate-900"><Building2 size={15} className="text-[var(--theme-link)]"/>{scopeText}</div></div><div className="panel p-4"><div className="text-xs font-medium text-slate-500">Administrators in view</div><div className="mt-1 text-xl font-bold text-slate-950">{scoped.length}</div></div><div className="panel p-4"><div className="text-xs font-medium text-slate-500">Active</div><div className="mt-1 text-xl font-bold text-slate-950">{scoped.filter(a=>a.isActive).length}</div></div></div>
  {error?<ErrorState title="Unable to load Tenant Administrators" message={error} onRetry={()=>void load()}/>:message?<Alert title="Administrator updated" message={message} tone="success"/>:null}
  <section className="panel overflow-hidden"><div className="border-b border-slate-100 p-4 sm:p-5"><label className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 shadow-sm"><Search size={16} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search administrators, email or company…" className="w-full bg-transparent py-2 text-sm outline-none"/></label></div>
   {loading?<LoadingState label="Loading Tenant Administrators…"/>:filtered.length===0?<EmptyState title="No Tenant Administrators in this scope" text="Promotion is performed from the Employees workspace."/>:<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Administrator</th><th className="px-5 py-3">Company</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Authority</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(admin=><tr key={admin.id} className="hover:bg-[var(--theme-primary-soft)]/35"><td className="px-5 py-4"><div className="font-semibold text-slate-900">{admin.firstName} {admin.lastName}</div><div className="mt-0.5 text-xs text-slate-500">{admin.email}</div><div className="mt-0.5 font-mono text-[11px] text-slate-400">{admin.employeeId||'Employee ID not set'}</div></td><td className="px-5 py-4"><div className="font-medium text-slate-700">{companyName(admin.companyId)}</div><div className="text-[11px] text-slate-400">{admin.companyId||'Tenant-wide role'}</div></td><td className="px-5 py-4"><StatusBadge status={admin.isActive?'ACTIVE':'INACTIVE'}/></td><td className="px-5 py-4"><Badge tone="brand">Tenant-wide administration</Badge></td><td className="px-5 py-4 text-right"><Button variant="secondary" size="sm" loading={busy===admin.id} disabled={!admin.isActive||!!busy} onClick={()=>setDemoteTarget(admin)} icon={<UserX size={14}/>}>Demote</Button></td></tr>)}</tbody></table></div>}
  </section>
  <section className="panel p-5"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[var(--theme-primary-soft)] text-[var(--theme-link)]"><UserCheck size={17}/></div><div><h2 className="font-semibold text-slate-900">How administration works</h2><p className="mt-1 text-sm leading-6 text-slate-500">Employees can be promoted to Tenant Admin from the Employees page. Tenant Admin access is separate from ordinary roles, cannot be self-assigned, and the last active Tenant Administrator is protected by the API.</p></div></div></section>
  <ConfirmDialog open={!!demoteTarget} title="Remove Tenant Administrator access" message={demoteTarget?`Remove tenant-wide administrative access from ${demoteTarget.firstName} ${demoteTarget.lastName}?`:undefined} confirmLabel="Remove access" danger loading={!!busy} onConfirm={()=>void demote()} onCancel={()=>{if(!busy)setDemoteTarget(null)}} />
 </div>;
}
