'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { KeyRound, ShieldCheck } from 'lucide-react';
import { apiFetch } from '../../../lib/api-client';
import { useAuth } from '../../../lib/auth-context';

export default function ChangePasswordPage(){
 const router=useRouter(); const { refreshLicense }=useAuth(); const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [confirm,setConfirm]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setError('');if(next.length<12)return setError('Use at least 12 characters.');if(next!==confirm)return setError('Passwords do not match.');setBusy(true);try{await apiFetch('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:current||undefined,newPassword:next})});await refreshLicense();router.replace('/dashboard');}catch(err:any){setError(err?.message??'Unable to change password.');}finally{setBusy(false);}}
 return <div className="grid min-h-[calc(100vh-7rem)] place-items-center"><div className="w-full max-w-lg rounded-3xl border border-slate-200 bg-white p-8 shadow-xl"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--theme-primary-soft)] text-[var(--theme-primary)]"><KeyRound size={23}/></div><h1 className="mt-6 text-2xl font-bold text-slate-950">Set your new password</h1><p className="mt-2 text-sm leading-6 text-slate-500">For security, you must change the temporary password before continuing to your AssetHub workspace.</p>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-4">{!current&&<p className="rounded-xl bg-slate-50 px-4 py-3 text-xs text-slate-500"><ShieldCheck className="mr-1 inline h-4 w-4"/>If this is your first login with a temporary password, leave the current password field empty.</p>}<label className="block text-sm font-semibold text-slate-700">Current password<input value={current} onChange={e=>setCurrent(e.target.value)} type="password" autoComplete="current-password" className="field mt-2 h-11 w-full" placeholder="Temporary password"/></label><label className="block text-sm font-semibold text-slate-700">New password<input required value={next} onChange={e=>setNext(e.target.value)} type="password" autoComplete="new-password" className="field mt-2 h-11 w-full" placeholder="At least 12 characters"/></label><label className="block text-sm font-semibold text-slate-700">Confirm new password<input required value={confirm} onChange={e=>setConfirm(e.target.value)} type="password" autoComplete="new-password" className="field mt-2 h-11 w-full" placeholder="Repeat your new password"/></label><button disabled={busy} className="ui-interactive inline-flex h-11 w-full items-center justify-center rounded-xl bg-[var(--theme-primary)] px-4 text-sm font-semibold text-white shadow-sm disabled:opacity-50">{busy?'Updating…':'Set new password'}</button></form></div></div>;
}
