'use client';
import Link from 'next/link';
import { ArrowLeft, Building2, CalendarClock, CheckCircle2, Globe2, KeyRound, PauseCircle, PlayCircle, RefreshCw, ShieldCheck, Users, Boxes, Activity } from 'lucide-react';
import { useParams } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';
import { systemFetch } from '../../../../lib/system-api';
import { Modal, ModalBody } from '../../../../components/modal';
import { ActivityTimeline } from '../../../../components/enterprise-ux';
import { Button, EmptyState, ErrorState, LoadingState, MetricCard, StatusBadge } from '../../../../components/ui';
import { FormTextarea } from '../../../../components/form-field';
import { useToast } from '../../../../components/toast';

type Tenant360={tenant:any;subscription:any;metrics:any;users:any[];activity:any[];health:any};
function fmt(v?:string|null){return v?new Date(v).toLocaleDateString():'—'}
function activityTone(action:string){return /fail|reject|suspend|delete|revok/i.test(action)?'danger':/create|success|complete|activat/i.test(action)?'success':'neutral'}

export default function Tenant360Page(){
 const {tenantId}=useParams<{tenantId:string}>(); const {toast}=useToast(); const [data,setData]=useState<Tenant360|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [modal,setModal]=useState<'suspend'|'reset'|null>(null); const [reason,setReason]=useState('Suspended by platform administrator'); const [credentials,setCredentials]=useState<any>(null);
 async function load(){setLoading(true);setError('');try{setData(await systemFetch(`/system/tenants/${tenantId}/360`))}catch(e:any){setError(e?.message??'Unable to load tenant control center.')}finally{setLoading(false)}}
 useEffect(()=>{if(tenantId)void load()},[tenantId]);
 async function suspend(){setBusy(true);try{await systemFetch(`/system/tenants/${tenantId}/suspend`,{method:'PATCH',body:JSON.stringify({reason:reason.trim()||'Suspended by platform administrator'})});toast({title:'Tenant suspended',message:data?.tenant.name,tone:'warning'});setModal(null);await load()}catch(e:any){toast({title:'Suspension failed',message:e.message,tone:'error'})}finally{setBusy(false)}}
 async function activate(){setBusy(true);try{await systemFetch(`/system/tenants/${tenantId}/activate`,{method:'PATCH'});toast({title:'Tenant activated',message:data?.tenant.name,tone:'success'});await load()}catch(e:any){toast({title:'Activation failed',message:e.message,tone:'error'})}finally{setBusy(false)}}
 async function resetPassword(){setBusy(true);try{const r=await systemFetch(`/system/tenants/${tenantId}/reset-password`,{method:'POST'});setCredentials(r);toast({title:'Temporary password generated',tone:'success'});setModal(null)}catch(e:any){toast({title:'Password reset failed',message:e.message,tone:'error'})}finally{setBusy(false)}}
 const timeline=useMemo(()=>data?.activity?.map(e=>({id:e.id,time:new Date(e.occurredAt).toLocaleString(),title:e.action,description:[e.targetType,e.targetId,e.result].filter(Boolean).join(' · '),tone:activityTone(e.action)}))??[],[data]);
 if(loading)return <LoadingState label="Loading tenant control center…"/>; if(!data)return <ErrorState title="Tenant unavailable" message={error||'The tenant could not be loaded.'} onRetry={()=>void load()}/>;
 const t=data.tenant,m=data.metrics,healthy=data.health?.status==='healthy';
 return <div className="space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/system/tenants" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-950"><ArrowLeft size={16}/>Tenants</Link><Button variant="secondary" onClick={()=>void load()} loading={loading} icon={<RefreshCw size={15}/>}>Refresh</Button></div>
  <header className="panel overflow-hidden"><div className="bg-gradient-to-r from-slate-950 via-slate-900 to-slate-800 p-6 text-white"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white/10 ring-1 ring-white/10">{t.logoUrl?<img src={t.logoUrl} alt="" className="h-full w-full object-contain"/>:<Building2 size={28} className="text-slate-300"/>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="truncate text-2xl font-bold tracking-tight">{t.name}</h1><StatusBadge status={t.status}/></div><p className="mt-1 truncate text-sm text-slate-300">{t.slug} · {t.primaryEmail||'No primary login email'}</p></div></div><div className="flex flex-wrap gap-2"><Button variant="secondary" loading={busy&&modal==='reset'} icon={<KeyRound size={15}/>} onClick={()=>setModal('reset')}>Reset admin password</Button>{t.status==='active'?<Button variant="danger" loading={busy&&modal==='suspend'} icon={<PauseCircle size={15}/>} onClick={()=>setModal('suspend')}>Suspend tenant</Button>:<Button loading={busy} icon={<PlayCircle size={15}/>} onClick={()=>void activate()}>Activate tenant</Button>}</div></div></div><div className="grid gap-3 border-t border-slate-200 bg-slate-50 p-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Created" value={fmt(t.createdAt)} icon={<CalendarClock size={14}/>} /><Info label="Phone" value={t.phone} icon={<Activity size={14}/>} /><Info label="Website" value={t.website} icon={<Globe2 size={14}/>} /><Info label="Subscription ends" value={fmt(data.subscription?.endsAt)} icon={<CalendarClock size={14}/>} /></div></header>
  {credentials?<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-start gap-3"><CheckCircle2 size={20} className="mt-0.5 text-emerald-600"/><div className="min-w-0 flex-1"><p className="font-semibold text-emerald-950">Temporary administrator credentials</p><p className="mt-1 text-sm text-emerald-800">The administrator must change this password at next login.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><CopyField label="Login email" value={credentials.email}/><CopyField label="Temporary password" value={credentials.temporaryPassword}/></div></div><button type="button" onClick={()=>setCredentials(null)} className="text-emerald-700">×</button></div></section>:null}
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard tone="primary" label="Tenant users" value={m.users??0} hint={`${m.activeUsers??0} active`} icon={<Users size={18}/>} /><MetricCard tone="info" label="Assets" value={m.assets??0} hint={`${m.activeAssignments??0} currently assigned`} icon={<Boxes size={18}/>} /><MetricCard tone="success" label="Organization" value={m.companies??0} hint={`${m.sites??0} sites · ${m.locations??0} locations`} icon={<Building2 size={18}/>} /><MetricCard tone={m.overdueAssets>0?'warning':'success'} label="Attention" value={m.overdueAssets??0} hint="Lost/stolen/warranty expired" icon={<ShieldCheck size={18}/>} /></section>
  <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
   <section className="panel p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-950">Tenant activity</h2><p className="mt-1 text-xs text-slate-500">Latest audit events across this organization.</p></div><Link href="/system/audit" className="text-xs font-semibold text-blue-600 hover:underline">Open audit →</Link></div><div className="mt-6">{timeline.length?<ActivityTimeline items={timeline}/>:<EmptyState title="No tenant activity yet" text="Audit events will appear here as the tenant is used."/>}</div></section>
   <section className="panel p-6"><div className="flex items-center gap-3"><div className={`grid h-10 w-10 place-items-center rounded-xl ${healthy?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}`}>{healthy?<CheckCircle2 size={18}/>:<ShieldCheck size={18}/>}</div><div><h2 className="text-base font-semibold text-slate-950">Tenant health</h2><p className="text-xs text-slate-500">Live platform signals.</p></div></div><div className="mt-5 space-y-3"><HealthRow label="Tenant access" ok={t.status==='active'}/><HealthRow label="Subscription" ok={!!data.subscription&&data.subscription.status==='active'}/><HealthRow label="SSO" ok={m.activeSsoProviders>0}/><HealthRow label="SCIM" ok={m.activeScimTokens>0}/><HealthRow label="Sessions" ok={data.health?.checks?.sessions!==false}/></div></section>
  </div>
  <div className="grid gap-5 xl:grid-cols-[1fr_1fr]">
   <section className="panel overflow-hidden"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4"><h2 className="text-sm font-semibold text-slate-950">Tenant users</h2><p className="mt-1 text-xs text-slate-500">Identity and account state.</p></div><div className="divide-y divide-slate-100">{data.users.slice(0,12).map((u:any)=><div key={u.id} className="flex items-center justify-between gap-3 px-5 py-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{u.name||u.email}</p><p className="truncate text-xs text-slate-500">{u.email}</p></div><div className="flex flex-wrap justify-end gap-1.5"><StatusBadge status={u.isActive?'ACTIVE':'DISABLED'}/><span className="rounded-full bg-violet-50 px-2 py-1 text-[10px] font-semibold text-violet-700">{u.authSource||'LOCAL'}</span></div></div>)}{!data.users.length?<EmptyState title="No users" text="This tenant has no user accounts yet."/>:null}</div></section>
   <section className="panel p-6"><h2 className="text-sm font-semibold text-slate-950">Platform links</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Link href={`/system/tenants/${tenantId}/entitlements`} className="ui-card-primary p-4"><p className="text-sm font-semibold text-slate-900">Entitlements</p><p className="mt-1 text-xs text-slate-500">Review effective plan capabilities.</p></Link><Link href={`/system/tenants/${tenantId}/primary-login-email`} className="ui-card-info p-4"><p className="text-sm font-semibold text-slate-900">Primary login</p><p className="mt-1 text-xs text-slate-500">Change the tenant's primary login email.</p></Link><Link href="/system/security" className="ui-card-identity p-4"><p className="text-sm font-semibold text-slate-900">Security sessions</p><p className="mt-1 text-xs text-slate-500">Review platform security activity.</p></Link><Link href="/system/analytics" className="ui-card-success p-4"><p className="text-sm font-semibold text-slate-900">Platform analytics</p><p className="mt-1 text-xs text-slate-500">Compare this tenant at platform level.</p></Link></div></section>
  </div>
  <Modal open={modal==='suspend'} onClose={()=>!busy&&setModal(null)} title="Suspend tenant" description={`This will block access for ${t.name}.`} size="md"><ModalBody><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Active tenant sessions will be revoked.</div><FormTextarea label="Suspension reason" id="tenant-suspension-reason" value={reason} onChange={e=>setReason(e.target.value)} rows={4} className="mt-4"/><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setModal(null)}>Cancel</Button><Button variant="danger" loading={busy} onClick={()=>void suspend()}>Suspend tenant</Button></div></ModalBody></Modal>
  <Modal open={modal==='reset'} onClose={()=>!busy&&setModal(null)} title="Reset administrator password" description="A new temporary password will be generated and all current administrator sessions will be revoked." size="md"><ModalBody><div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">The tenant administrator must change the temporary password at the next login.</div><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setModal(null)}>Cancel</Button><Button loading={busy} onClick={()=>void resetPassword()}>Generate temporary password</Button></div></ModalBody></Modal>
 </div>
}
function Info({icon,label,value}:{icon?:React.ReactNode;label:string;value?:string|null}){return <div className="rounded-xl border border-slate-200 bg-white p-3"><p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">{icon}{label}</p><p className="mt-1 truncate text-sm font-semibold text-slate-900">{value||'—'}</p></div>}
function HealthRow({label,ok}:{label:string;ok:boolean}){return <div className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 px-3 py-2.5"><span className="text-sm font-medium text-slate-700">{label}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${ok?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{ok?'Healthy':'Attention'}</span></div>}
function CopyField({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-emerald-200 bg-white p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><button type="button" onClick={()=>{void navigator.clipboard.writeText(value)}} className="mt-1 block max-w-full truncate font-mono text-sm font-semibold text-slate-900 hover:text-blue-600">{value}</button></div>}
