'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Building2, CalendarClock, CheckCircle2, Copy, Globe2, KeyRound, Mail, PauseCircle, Phone, PlayCircle, RefreshCw, ShieldCheck, Users, X } from 'lucide-react';
import { useParams } from 'next/navigation';
import { systemFetch } from '../../../../lib/system-api';

type Tenant={id:string;name:string;slug:string;status:string;primaryEmail?:string|null;phone?:string|null;website?:string|null;logoFileId?:string|null;logoUrl?:string|null};
type User={id:string;email:string;name:string;isActive:boolean;forcePasswordReset:boolean};
type Subscription={id:string;planId:string;status:string;startedAt?:string;endsAt?:string|null};
type Data={tenant:Tenant;subscription:Subscription|null;users:User[];companies:{id:string;name:string;code:string}[]};
type Usage={users?:number;assets?:number;companies?:number;storage?:number|string};

function statusClass(status:string){if(status==='active')return 'bg-emerald-50 text-emerald-700 border-emerald-200';if(status==='suspended')return 'bg-amber-50 text-amber-700 border-amber-200';return 'bg-slate-100 text-slate-600 border-slate-200'}
function fmtDate(value?:string|null){return value?new Date(value).toLocaleDateString(): '—'}

export default function TenantControlCenter(){
 const params=useParams<{tenantId:string}>(); const tenantId=params.tenantId;
 const [data,setData]=useState<Data|null>(null); const [usage,setUsage]=useState<Usage|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState(''); const [credentials,setCredentials]=useState<{email:string;temporaryPassword:string}|null>(null); const [tab,setTab]=useState<'overview'|'users'|'subscription'|'security'>('overview');
 async function load(){setLoading(true);setError('');try{const [d,u]=await Promise.all([systemFetch(`/system/tenants/${tenantId}`),systemFetch(`/system/tenants/${tenantId}/usage`)]);setData(d);setUsage(u??null)}catch(e:any){setError(e?.message??'Unable to load tenant.')}finally{setLoading(false)}}
 useEffect(()=>{if(tenantId)void load()},[tenantId]);
 const admin=useMemo(()=>data?.users?.find(u=>u.isActive)||data?.users?.[0], [data]);
 async function resetPassword(){if(!data)return; if(!window.confirm(`Reset the tenant administrator password for ${admin?.email??data.tenant.primaryEmail}?`))return;setBusy('reset');setError('');try{const r=await systemFetch(`/system/tenants/${tenantId}/reset-password`,{method:'POST'});setCredentials({email:r.email,temporaryPassword:r.temporaryPassword});await load()}catch(e:any){setError(e?.message??'Unable to reset password.')}finally{setBusy('')}}
 async function setStatus(active:boolean){if(!data)return;let reason='';if(!active){reason=window.prompt('Suspension reason:','Suspended by platform administrator')??'';if(!reason)return}setBusy(active?'activate':'suspend');setError('');try{await systemFetch(`/system/tenants/${tenantId}/${active?'activate':'suspend'}`,{method:'PATCH',...(reason?{body:JSON.stringify({reason})}:{})});await load()}catch(e:any){setError(e?.message??`Unable to ${active?'activate':'suspend'} tenant.`)}finally{setBusy('')}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value)}catch{}}
 if(loading)return <div className="space-y-5"><div className="h-8 w-56 animate-pulse rounded-lg bg-slate-200"/><div className="h-36 animate-pulse rounded-3xl bg-slate-100"/><div className="grid gap-4 md:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="h-28 animate-pulse rounded-2xl bg-slate-100"/>)}</div></div>;
 if(!data)return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error||'Tenant not found.'}</div>;
 const t=data.tenant; const tabs=[['overview','Overview'],['users','Users'],['subscription','Subscription'],['security','Security']] as const;
 return <div className="space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/system/tenants" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-950"><ArrowLeft size={16}/>Tenants</Link><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"><RefreshCw size={15}/>Refresh</button></div>
  {error&&<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <header className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-2xl border border-slate-200 bg-slate-50">{t.logoUrl?<img src={t.logoUrl} alt="" className="h-full w-full object-contain"/>:<Building2 className="text-slate-400" size={28}/>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="truncate text-2xl font-bold text-slate-950">{t.name}</h1><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${statusClass(t.status)}`}>{t.status}</span></div><p className="mt-1 text-sm text-slate-500">{t.slug}.assethub · {t.primaryEmail??'No primary email'}</p></div></div><div className="flex flex-wrap gap-2"><button disabled={busy!==''} onClick={()=>void resetPassword()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-700 disabled:opacity-50"><KeyRound size={16}/>{busy==='reset'?'Resetting…':'Reset admin password'}</button>{t.status==='active'?<button disabled={busy!==''} onClick={()=>void setStatus(false)} className="inline-flex items-center gap-2 rounded-xl border border-amber-200 px-3 py-2.5 text-sm font-semibold text-amber-700 disabled:opacity-50"><PauseCircle size={16}/>{busy==='suspend'?'Suspending…':'Suspend tenant'}</button>:<button disabled={busy!==''} onClick={()=>void setStatus(true)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-3 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><PlayCircle size={16}/>{busy==='activate'?'Activating…':'Activate tenant'}</button>}</div></div></header>
  {credentials&&<section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 font-semibold text-emerald-900"><CheckCircle2 size={18}/>Temporary administrator credentials</p><p className="mt-1 text-sm text-emerald-800">The tenant administrator must change this password at the next login. This password will not be shown again after closing this panel.</p></div><button onClick={()=>setCredentials(null)} className="rounded-lg p-1 text-emerald-700"><X size={18}/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Credential label="Login email" value={credentials.email} onCopy={copy}/><Credential label="Temporary password" value={credentials.temporaryPassword} onCopy={copy}/></div></section>}
  <nav className="flex gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-slate-100 p-1">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2.5 text-sm font-semibold transition ${tab===key?'bg-white text-slate-950 shadow-sm':'text-slate-500 hover:text-slate-900'}`}>{label}</button>)}<Link href={`/system/tenants/${tenantId}/entitlements`} className="ml-auto shrink-0 rounded-xl px-4 py-2.5 text-sm font-semibold text-blue-700 hover:bg-white">Entitlements →</Link></nav>
  {tab==='overview'&&<Overview data={data} usage={usage}/>} {tab==='users'&&<UsersPanel users={data.users}/>} {tab==='subscription'&&<SubscriptionPanel subscription={data.subscription} tenantId={tenantId}/>} {tab==='security'&&<SecurityPanel admin={admin} onReset={resetPassword}/>} 
 </div>
}

function Overview({data,usage}:{data:Data;usage:Usage|null}){const t=data.tenant;return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users size={18}/>} label="Tenant users" value={usage?.users??data.users.length}/><Metric icon={<Building2 size={18}/>} label="Companies" value={usage?.companies??data.companies.length}/><Metric icon={<ShieldCheck size={18}/>} label="Subscription" value={data.subscription?.status??'Unlicensed'}/><Metric icon={<CalendarClock size={18}/>} label="Expires" value={fmtDate(data.subscription?.endsAt)}/></div><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Tenant profile</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><Info icon={<Mail size={16}/>} label="Primary email" value={t.primaryEmail}/><Info icon={<Phone size={16}/>} label="Phone" value={t.phone}/><Info icon={<Globe2 size={16}/>} label="Website" value={t.website}/><Info icon={<Building2 size={16}/>} label="Tenant slug" value={t.slug}/></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Subscription snapshot</h2>{data.subscription?<div className="mt-5 space-y-4"><Info label="Plan" value={data.subscription.planId}/><Info label="Status" value={data.subscription.status}/><Info label="Started" value={fmtDate(data.subscription.startedAt)}/><Info label="Ends" value={fmtDate(data.subscription.endsAt)}/></div>:<Empty text="No subscription is assigned."/>}</section></div></div>}
function UsersPanel({users}:{users:User[]}){return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold text-slate-950">Tenant users</h2><p className="mt-1 text-sm text-slate-500">Users currently associated with this tenant.</p></div>{users.length===0?<Empty text="No tenant users found."/>:<div className="divide-y divide-slate-100">{users.map(u=><div key={u.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">{u.name||'Tenant user'}</p><p className="mt-1 text-sm text-slate-500">{u.email}</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${u.isActive?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{u.isActive?'Active':'Inactive'}</span>{u.forcePasswordReset&&<span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700">Password change required</span>}</div></div>)}</div>}</section>}
function SubscriptionPanel({subscription,tenantId}:{subscription:Subscription|null;tenantId:string}){return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{subscription?<><h2 className="font-semibold text-slate-950">Subscription</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Info label="Plan" value={subscription.planId}/><Info label="Status" value={subscription.status}/><Info label="Started" value={fmtDate(subscription.startedAt)}/><Info label="Ends" value={fmtDate(subscription.endsAt)}/></div><Link href={`/system/tenants/${tenantId}/entitlements`} className="mt-6 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">View effective entitlements</Link></>:<Empty text="This tenant has no active subscription."/>}</section>}
function SecurityPanel({admin,onReset}:{admin?:User;onReset:()=>void}){return <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Administrator access</h2><div className="mt-5 space-y-4"><Info label="Administrator" value={admin?.name}/><Info label="Email" value={admin?.email}/><Info label="Account" value={admin?.isActive?'Active':'Inactive'}/><Info label="Password state" value={admin?.forcePasswordReset?'Change required':'Normal'}/></div><button onClick={onReset} className="mt-6 inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700"><KeyRound size={16}/>Issue temporary password</button></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Security controls</h2><div className="mt-5 space-y-3 text-sm"><SecurityRow title="Tenant status enforcement" detail="Suspending a tenant revokes active tenant sessions."/><SecurityRow title="Password reset" detail="Platform reset forces a password change and revokes sessions."/><SecurityRow title="Audit trail" detail="Tenant lifecycle and password reset operations are audited."/></div></section></div>}
function SecurityRow({title,detail}:{title:string;detail:string}){return <div className="rounded-xl border border-slate-100 bg-slate-50 p-4"><p className="font-semibold text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-700">{icon}</div><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 truncate text-xl font-bold text-slate-950">{value}</p></div>}
function Info({icon,label,value}:{icon?:React.ReactNode;label:string;value?:string|null}){return <div><p className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-slate-400">{icon}{label}</p><p className="mt-1 break-words text-sm font-semibold text-slate-900">{value||'—'}</p></div>}
function Empty({text}:{text:string}){return <div className="p-10 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-slate-100 text-slate-400"><Building2 size={20}/></div><p className="mt-3 text-sm font-semibold text-slate-800">{text}</p></div>}
function Credential({label,value,onCopy}:{label:string;value:string;onCopy:(v:string)=>void}){return <div className="rounded-xl border border-emerald-200 bg-white p-3"><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><div className="mt-1 flex items-center gap-2"><code className="min-w-0 flex-1 truncate text-sm font-semibold text-slate-900">{value}</code><button onClick={()=>void onCopy(value)} className="rounded-lg border border-slate-200 p-1.5 text-slate-500" title="Copy"><Copy size={14}/></button></div></div>}
