'use client';
import { useEffect, useMemo, useState } from 'react';
import { RefreshCw, Search, ShieldCheck, Users, UserCheck, UserX, Check } from 'lucide-react';
import { systemFetch } from '../../../lib/system-api';

type Role={id:string;name:string;isSystem:boolean;permissions:{permissionId:string;permissionKey:string}[]};
type User={id:string;email:string;firstName:string;lastName:string;isActive:boolean;roleIds:string[]};

export default function SystemUsersPage(){
 const [items,setItems]=useState<User[]>([]); const [roles,setRoles]=useState<Role[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [status,setStatus]=useState<'all'|'active'|'inactive'>('all'); const [editing,setEditing]=useState<string|null>(null); const [saving,setSaving]=useState(false);
 async function load(){setLoading(true);setError('');try{const [usersData,rolesData]=await Promise.all([systemFetch('/system/users'),systemFetch('/system/roles')]);setItems(Array.isArray(usersData)?usersData:[]);setRoles(Array.isArray(rolesData)?rolesData:[])}catch(e:any){setError(e?.message??'Unable to load platform access.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>items.filter(u=>{const text=`${u.firstName} ${u.lastName} ${u.email}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(status==='all'||(status==='active'?u.isActive:!u.isActive))}),[items,query,status]);
 const active=items.filter(u=>u.isActive).length;
 async function saveRoles(userId:string, roleIds:string[]){setSaving(true);setError('');try{await systemFetch(`/system/users/${userId}/roles`,{method:'PATCH',body:JSON.stringify({roleIds})});setItems(current=>current.map(user=>user.id===userId?{...user,roleIds}:user));setEditing(null)}catch(e:any){setError(e?.message??'We could not update platform access.')}finally{setSaving(false)}}
 return <div className="space-y-6">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--theme-link,#2563eb)]">Platform</p><h2 className="mt-1 text-2xl font-bold text-slate-950">Platform Users</h2><p className="mt-2 text-sm text-slate-500">System administrator accounts and platform access.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex w-fit items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button></header>
  {error&&<div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span>{error}</span><button onClick={()=>void load()} className="font-semibold underline">Retry</button></div>}
  <div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Users size={18}/>} label="Total administrators" value={items.length}/><Metric icon={<UserCheck size={18}/>} label="Active" value={active}/><Metric icon={<UserX size={18}/>} label="Inactive" value={items.length-active}/></div>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row md:items-center md:justify-between"><div className="relative w-full max-w-md"><Search size={16} className="absolute left-3 top-2.5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email" className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-[var(--theme-link,#2563eb)]" aria-label="Search platform users"/></div><div className="flex rounded-xl border border-slate-200 bg-slate-50 p-1"><FilterButton active={status==='all'} onClick={()=>setStatus('all')}>All</FilterButton><FilterButton active={status==='active'} onClick={()=>setStatus('active')}>Active</FilterButton><FilterButton active={status==='inactive'} onClick={()=>setStatus('inactive')}>Inactive</FilterButton></div></div>
   {loading?<div className="divide-y divide-slate-100">{[1,2,3,4].map(i=><div key={i} className="h-20 animate-pulse bg-slate-50/70"/> )}</div>:filtered.length===0?<div className="p-14 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-slate-400"><Users size={22}/></div><p className="mt-4 font-semibold text-slate-800">No platform users found</p><p className="mt-1 text-sm text-slate-500">Try a different search or status filter.</p></div>:<div className="divide-y divide-slate-100">{filtered.map(u=><div key={u.id} className="flex flex-col gap-4 p-5 transition hover:bg-slate-50"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><ShieldCheck size={18}/></div><div className="min-w-0"><p className="truncate font-semibold text-slate-950">{u.firstName} {u.lastName}</p><p className="mt-1 truncate text-sm text-slate-500">{u.email}</p></div></div><div className="flex flex-wrap items-center gap-2 sm:justify-end"><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${u.isActive?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-slate-200 bg-slate-100 text-slate-600'}`}>{u.isActive?'Active':'Inactive'}</span><span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 text-xs font-semibold text-slate-500">{u.roleIds.length} role{u.roleIds.length===1?'':'s'}</span><button onClick={()=>setEditing(editing===u.id?null:u.id)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">Manage access</button></div></div>
   {editing===u.id&&<RoleEditor user={u} roles={roles} saving={saving} onCancel={()=>setEditing(null)} onSave={(roleIds)=>void saveRoles(u.id,roleIds)}/>}</div>)}</div>}
  </section>
 </div>
}
function RoleEditor({user,roles,saving,onCancel,onSave}:{user:User;roles:Role[];saving:boolean;onCancel:()=>void;onSave:(roleIds:string[])=>void}){const [selected,setSelected]=useState<string[]>(user.roleIds);return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-5"><div><p className="font-semibold text-slate-900">Platform access</p><p className="mt-1 text-sm text-slate-500">Choose the platform roles this administrator should have. Organization roles are separate.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{roles.map(role=>{const checked=selected.includes(role.id);return <button type="button" key={role.id} onClick={()=>setSelected(current=>checked?current.filter(id=>id!==role.id):[...current,role.id])} className={`flex items-start gap-3 rounded-xl border p-3 text-left transition ${checked?'border-blue-300 bg-white shadow-sm':'border-slate-200 bg-white hover:border-slate-300'}`}><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-md border ${checked?'border-blue-600 bg-blue-600 text-white':'border-slate-300 bg-white text-transparent'}`}><Check size={13}/></span><span className="min-w-0"><span className="block text-sm font-semibold text-slate-900">{role.name}</span><span className="mt-1 block text-xs text-slate-500">{role.permissions.length} platform permission{role.permissions.length===1?'':'s'}</span></span></button>})}</div><div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={onCancel} disabled={saving} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700">Cancel</button><button type="button" onClick={()=>onSave(selected)} disabled={saving||selected.length===0} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving&&<RefreshCw className="h-4 w-4 animate-spin"/>}Save access</button></div></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-700">{icon}</div><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold text-slate-950">{value}</p></div>}
function FilterButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition ${active?'bg-white text-slate-950 shadow-sm':'text-slate-500 hover:text-slate-900'}`}>{children}</button>}
