'use client';

import { useEffect, useMemo, useState } from 'react';
import { KeyRound, Pencil, Plus, RefreshCw, ShieldCheck, UserCheck, UserRound, UserX, Users, X } from 'lucide-react';
import { systemFetch } from '../../../lib/system-api';
import { Button, EmptyState, ErrorState, LoadingState } from '../../../components/ui';
import { ConfirmDialog } from '../../../components/confirm-dialog';
import { Modal, ModalBody } from '../../../components/modal';
import { useToast } from '../../../components/toast';

type Role={id:string;name:string;isSystem:boolean;permissions:{permissionId:string;permissionKey:string}[]};
type User={id:string;email:string;firstName:string;lastName:string;isActive:boolean;roleIds:string[];forcePasswordReset?:boolean};
type Form={email:string;firstName:string;lastName:string;roleIds:string[]};
const empty:Form={email:'',firstName:'',lastName:'',roleIds:[]};

export default function SystemUsersPage(){
 const {toast}=useToast();
 const [items,setItems]=useState<User[]>([]),[roles,setRoles]=useState<Role[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState<'all'|'active'|'inactive'>('all');
 const [modal,setModal]=useState<'create'|'edit'|'reset'|null>(null),[selected,setSelected]=useState<User|null>(null),[form,setForm]=useState<Form>(empty),[confirm,setConfirm]=useState<{kind:'deactivate'|'activate';user:User}|null>(null),[credentials,setCredentials]=useState<{email:string;temporaryPassword:string}|null>(null);
 async function load(){setLoading(true);setError('');try{const [u,r]=await Promise.all([systemFetch('/system/users'),systemFetch('/system/roles')]);setItems(Array.isArray(u)?u:[]);setRoles(Array.isArray(r)?r:[])}catch(e:any){setError(e?.message??'Unable to load platform users.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>items.filter(u=>{const text=`${u.firstName} ${u.lastName} ${u.email}`.toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(status==='all'||(status==='active'?u.isActive:!u.isActive))}),[items,query,status]);
 const active=items.filter(u=>u.isActive).length;
 function openCreate(){setSelected(null);setForm(empty);setCredentials(null);setModal('create')}
 function openEdit(u:User){setSelected(u);setForm({email:u.email,firstName:u.firstName,lastName:u.lastName,roleIds:u.roleIds});setModal('edit')}
 function toggleRole(id:string){setForm(f=>({...f,roleIds:f.roleIds.includes(id)?f.roleIds.filter(x=>x!==id):[...f.roleIds,id]}))}
 async function saveUser(){if(!form.email.trim()||!form.firstName.trim()||!form.lastName.trim()||!form.roleIds.length){setError('Email, first name, last name and at least one platform role are required.');return}setSaving(true);setError('');try{if(modal==='create'){const r=await systemFetch('/system/users',{method:'POST',body:JSON.stringify(form)});setCredentials({email:r.email,temporaryPassword:r.temporaryPassword});toast({title:'Platform user created',message:r.email,tone:'success'});}else if(selected){await systemFetch(`/system/users/${selected.id}`,{method:'PATCH',body:JSON.stringify({email:form.email,firstName:form.firstName,lastName:form.lastName})});await systemFetch(`/system/users/${selected.id}/roles`,{method:'PATCH',body:JSON.stringify({roleIds:form.roleIds})});toast({title:'Platform user updated',message:`${form.firstName} ${form.lastName}`,tone:'success'});setModal(null)}await load()}catch(e:any){setError(e?.message??'Unable to save platform user.');toast({title:'Update failed',message:e?.message??'Unable to save platform user.',tone:'error'})}finally{setSaving(false)}}
 async function changeStatus(){if(!confirm)return;setSaving(true);try{await systemFetch(`/system/users/${confirm.user.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:confirm.kind==='activate'})});toast({title:confirm.kind==='activate'?'Platform user activated':'Platform user deactivated',message:confirm.user.email,tone:'success'});setConfirm(null);await load()}catch(e:any){toast({title:'Status update failed',message:e?.message??'Unable to update user status.',tone:'error'})}finally{setSaving(false)}}
 async function resetPassword(u:User){setSaving(true);try{const r=await systemFetch(`/system/users/${u.id}/reset-password`,{method:'POST'});setCredentials({email:r.email,temporaryPassword:r.temporaryPassword});setModal('reset');toast({title:'Temporary password generated',message:u.email,tone:'success'})}catch(e:any){toast({title:'Password reset failed',message:e?.message??'Unable to reset password.',tone:'error'})}finally{setSaving(false)}}
 if(loading)return <LoadingState label="Loading platform users…"/>;
 if(error&&items.length===0)return <ErrorState title="Unable to load platform users" message={error} onRetry={()=>void load()}/>;
 return <div className="space-y-6">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--theme-link)]">Platform</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Platform Users</h1><p className="mt-2 text-sm text-slate-500">Manage platform administrator identity, access, lifecycle and credentials.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>void load()} loading={loading} icon={<RefreshCw size={15}/>}>Refresh</Button><Button onClick={openCreate} icon={<Plus size={16}/>}>Create platform user</Button></div></header>
  {error?<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
  <div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Users size={18}/>} label="Total administrators" value={items.length}/><Metric icon={<UserCheck size={18}/>} label="Active" value={active}/><Metric icon={<UserX size={18}/>} label="Inactive" value={items.length-active}/></div>
  <section className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row md:items-center md:justify-between"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email" className="field h-11 max-w-md" aria-label="Search platform users"/><div className="flex gap-1 rounded-xl border border-slate-200 bg-slate-50 p-1">{(['all','active','inactive'] as const).map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold transition ${status===s?'bg-white text-slate-900 shadow-sm':'text-slate-500'}`}>{s[0].toUpperCase()+s.slice(1)}</button>)}</div></div>
   {filtered.length===0?<EmptyState title="No platform users found" text={query?'Try another search term.':'Create your first platform administrator.'} action="Create platform user" onAction={openCreate}/>:<div className="divide-y divide-slate-100">{filtered.map(u=><div key={u.id} className="p-5 ui-table-row"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[var(--theme-primary-soft)] text-[var(--theme-link)]"><UserRound size={18}/></div><div className="min-w-0"><p className="truncate font-semibold text-slate-950">{u.firstName} {u.lastName}</p><p className="truncate text-sm text-slate-500">{u.email}</p>{u.forcePasswordReset?<p className="mt-1 text-[11px] font-semibold text-amber-600">Password change required</p>:null}</div></div><div className="flex flex-wrap items-center gap-2"><span className={u.isActive?'badge badge-success':'badge badge-neutral'}>{u.isActive?'Active':'Inactive'}</span><span className="badge badge-brand">{u.roleIds.length} role{u.roleIds.length===1?'':'s'}</span><Button size="sm" variant="secondary" onClick={()=>openEdit(u)} icon={<Pencil size={14}/>}>Edit</Button><Button size="sm" variant="secondary" onClick={()=>void resetPassword(u)} disabled={saving} icon={<KeyRound size={14}/>}>Reset password</Button><Button size="sm" variant={u.isActive?'danger':'primary'} onClick={()=>setConfirm({kind:u.isActive?'deactivate':'activate',user:u})} icon={u.isActive?<UserX size={14}/>:<UserCheck size={14}/>} >{u.isActive?'Deactivate':'Activate'}</Button></div></div><div className="mt-3 flex flex-wrap gap-2">{u.roleIds.map(id=><span key={id} className="badge badge-neutral">{roles.find(r=>r.id===id)?.name??'Assigned role'}</span>)}</div></div>)}</div>}
  </section>
  {(modal==='create'||modal==='edit')?<Modal open title={modal==='create'?'Create platform user':'Edit platform user'} description="Changes are saved to the System Admin backend." onClose={()=>!saving&&setModal(null)} size="lg"><ModalBody><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" value={form.firstName} onChange={v=>setForm(f=>({...f,firstName:v}))}/><Field label="Last name" value={form.lastName} onChange={v=>setForm(f=>({...f,lastName:v}))}/><Field label="Email" value={form.email} onChange={v=>setForm(f=>({...f,email:v}))} type="email"/></div><div className="mt-5"><p className="text-sm font-semibold text-slate-900">Platform roles</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{roles.map(r=><button type="button" key={r.id} onClick={()=>modal==='create'?toggleRole(r.id):toggleRole(r.id)} className={`rounded-xl border p-3 text-left transition ${form.roleIds.includes(r.id)?'border-[var(--theme-focus)] bg-[var(--theme-primary-soft)]':'border-slate-200 bg-white hover:bg-slate-50'}`}><div className="flex items-center justify-between"><span className="font-semibold text-sm text-slate-900">{r.name}</span><span className={form.roleIds.includes(r.id)?'text-[var(--theme-link)]':'text-slate-300'}>●</span></div><span className="mt-1 block text-xs text-slate-500">{r.permissions.length} permissions{r.isSystem?' · Built-in':''}</span></button>)}</div></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setModal(null)} disabled={saving}>Cancel</Button><Button loading={saving} disabled={!form.email||!form.firstName||!form.lastName||!form.roleIds.length} onClick={()=>void saveUser()}>{modal==='create'?'Create user':'Save changes'}</Button></div></ModalBody></Modal>:null}
  {credentials?<Modal open title={modal==='reset'?'Temporary password':'Platform user created'} description="This temporary password must be changed at first login." onClose={()=>{setCredentials(null);if(modal==='reset')setModal(null)}} size="md"><ModalBody><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-sm font-semibold text-amber-900">Login email</p><p className="mt-1 font-mono text-sm text-slate-900">{credentials.email}</p><p className="mt-4 text-sm font-semibold text-amber-900">Temporary password</p><code className="mt-1 block break-all rounded-xl bg-white p-3 text-sm text-slate-900">{credentials.temporaryPassword}</code></div><div className="mt-5 flex justify-end"><Button onClick={()=>{setCredentials(null);if(modal==='reset')setModal(null)}}>Done</Button></div></ModalBody></Modal>:null}
  <ConfirmDialog open={!!confirm} title={confirm?.kind==='deactivate'?'Deactivate platform user':'Activate platform user'} message={confirm?`${confirm.user.firstName} ${confirm.user.lastName} (${confirm.user.email})` : undefined} confirmLabel={confirm?.kind==='deactivate'?'Deactivate':'Activate'} danger={confirm?.kind==='deactivate'} loading={saving} onCancel={()=>!saving&&setConfirm(null)} onConfirm={()=>void changeStatus()}/>
 </div>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="panel p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--theme-primary-soft)] text-[var(--theme-link)]">{icon}</div><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-950">{value}</p></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="text-sm font-semibold text-slate-700">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="field mt-2 h-11 w-full" /></label>}
