'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Bell, Lock, ShieldCheck, Settings2, Building2, ChevronRight, Save } from 'lucide-react';
import { apiFetch } from '../../../lib/api-client';

type Prefs={notificationsEnabled:boolean;assetEvents:boolean;assignmentEvents:boolean;transferEvents:boolean;maintenanceEvents:boolean;warrantyEvents:boolean;securityEvents:boolean;systemEvents:boolean};
const defaults:Prefs={notificationsEnabled:true,assetEvents:true,assignmentEvents:true,transferEvents:true,maintenanceEvents:true,warrantyEvents:true,securityEvents:true,systemEvents:true};
export default function SettingsPage(){const [prefs,setPrefs]=useState(defaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState('');useEffect(()=>{void apiFetch('/ux/notification-preferences').then((d:any)=>setPrefs({...defaults,...d})).catch((e:any)=>setError(e.message??'Unable to load notification preferences.')).finally(()=>setLoading(false))},[]);async function save(){setSaving(true);setSaved(false);try{await apiFetch('/ux/notification-preferences',{method:'PATCH',body:JSON.stringify(prefs)});setSaved(true)}catch(e:any){setError(e.message??'Unable to save notification preferences.')}finally{setSaving(false)}}
return <div className="mx-auto max-w-4xl space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]">Account</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Settings</h1><p className="mt-2 text-sm text-slate-500">Manage tenant account preferences and security controls.</p></div>
<Link href="/settings/company" className="ui-interactive flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-[var(--theme-primary)]/30 hover:shadow-md"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--theme-primary-soft)] text-[var(--theme-primary)]"><Building2 size={19}/></div><div><p className="font-semibold text-slate-950">Company profile & branding</p><p className="mt-1 text-sm text-slate-500">Logo, company identity and contact details used across tenant documents.</p></div></div><ChevronRight size={18} className="text-slate-400"/></Link>
<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Settings2 size={19} className="text-[var(--theme-primary)]"/><div><h2 className="font-semibold text-slate-950">Notification preferences</h2><p className="mt-1 text-sm text-slate-500">Choose which operational notifications appear in your AssetHub bell.</p></div></div>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{loading?<div className="mt-5 text-sm text-slate-500">Loading preferences…</div>:<><div className="mt-5 rounded-xl bg-[var(--theme-primary-soft)]/55 p-4"><Toggle title="All notifications" description="Master switch for persistent in-app notifications." enabled={prefs.notificationsEnabled} onChange={v=>setPrefs(p=>({...p,notificationsEnabled:v}))}/></div><div className="mt-4 divide-y divide-slate-100">{[['assetEvents','Asset activity','Asset creation, updates, lifecycle changes'],['assignmentEvents','Assignments','Asset assignment and return activity'],['transferEvents','Transfers','Transfer requests, approvals and rejections'],['maintenanceEvents','Maintenance','Maintenance and repair activity'],['warrantyEvents','Warranty','Warranty-related warnings and changes'],['securityEvents','Security','Password, session and security-sensitive activity'],['systemEvents','System','General tenant configuration and platform activity']].map(([key,title,description])=><Toggle key={key} title={title} description={description} enabled={Boolean((prefs as any)[key])&&prefs.notificationsEnabled} onChange={v=>setPrefs(p=>({...p,[key]:v}))} disabled={!prefs.notificationsEnabled}/>)}</div><div className="mt-5 flex items-center justify-end gap-3">{saved&&<span className="text-xs font-semibold text-emerald-600">Saved</span>}<button type="button" disabled={saving} onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-xl bg-[var(--theme-primary)] px-4 py-2.5 text-sm font-semibold text-white shadow-sm disabled:opacity-50"><Save size={15}/>{saving?'Saving…':'Save preferences'}</button></div></>}</section>
<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Lock size={19} className="text-[var(--theme-primary)]"/><div><h2 className="font-semibold text-slate-950">Security</h2><p className="mt-1 text-sm text-slate-500">Your password, MFA, and active sessions are managed through the account security workflow.</p></div></div><div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><ShieldCheck size={16} className="mr-2 inline"/>Use your profile and user security controls for account access changes. Organization-wide SSO and SCIM settings remain under Identity & SSO.</div></section></div>;
}
function Toggle({title,description,enabled,onChange,disabled=false}:{title:string;description:string;enabled:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <div className={`flex items-center justify-between gap-4 py-5 ${disabled?'opacity-50':''}`}><div><p className="text-sm font-semibold text-slate-900">{title}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div><button type="button" aria-pressed={enabled} disabled={disabled} onClick={()=>onChange(!enabled)} className={`relative h-6 w-11 shrink-0 rounded-full transition ${enabled?'bg-[var(--theme-primary)]':'bg-slate-300'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${enabled?'left-6':'left-1'}`}/></button></div>}
