'use client';

import Link from 'next/link';
import { ArrowLeft, ShieldCheck, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { apiFetch } from '../../../../../../lib/api-client';
import { Badge, Button, LoadingState } from '../../../../../../components/ui';

type Employee = { id:string; employeeId:string; name?:string; email?:string; role?:'employee'|'tenant_admin'; authMode?:'local'|'sso'; scope?:string };
export default function PromotionsPage(){
 const [items,setItems]=useState<Employee[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);try{const data=await apiFetch('/identity/rbac/promotions');setItems(data?.employees??data??[])}catch(err:any){setError(err?.message??'Employee role data is unavailable.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function change(item:Employee,promote:boolean){setBusy(item.id);setError(null);setMessage(null);try{await apiFetch(`/identity/rbac/promotions/${encodeURIComponent(item.id)}`,{method:'PATCH',body:JSON.stringify({role:promote?'tenant_admin':'employee'})});setMessage(`${item.name??item.employeeId} ${promote?'is now a tenant admin':'is now an employee'}.`);await load()}catch(err:any){setError(err?.message??'Unable to change the employee role.')}finally{setBusy(null)}}
 return <div className="mx-auto max-w-6xl space-y-6 page-section-enter"><Link href="/settings/identity/rbac" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--theme-link)]"><ArrowLeft size={15}/>Back to RBAC</Link><header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]">Role lifecycle</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Promote employees to admins</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Promotion changes AssetHub authorization only. If the employee is SSO-linked, their existing provider login continues to work; the new admin role is applied by AssetHub.</p></header>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}{loading?<div className="panel p-8"><LoadingState label="Loading employees…"/></div>:<section className="panel overflow-hidden"><div className="divide-y divide-slate-100">{items.length===0?<div className="p-8 text-center text-sm text-slate-500">No employees returned.</div>:items.map(item=><div key={item.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--theme-primary-soft)] text-[var(--theme-primary)]"><UserRound size={18}/></div><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-950">{item.name??'Employee'}</p><Badge tone="neutral">{item.employeeId}</Badge><Badge tone={item.role==='tenant_admin'?'brand':'neutral'}>{item.role==='tenant_admin'?'Tenant admin':'Employee'}</Badge></div><p className="mt-1 text-sm text-slate-500">{item.email??'No email'} · {item.authMode==='sso'?'SSO linked':'Local authentication'}{item.scope?` · ${item.scope}`:''}</p></div></div><Button variant={item.role==='tenant_admin'?'secondary':'primary'} loading={busy===item.id} onClick={()=>void change(item,item.role!=='tenant_admin')} disabled={item.role==='tenant_admin'&&items.filter(x=>x.role==='tenant_admin').length<=1}>{item.role==='tenant_admin'?'Demote to employee':'Promote to tenant admin'}</Button></div>)}</div></section>}
 <div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5"><ShieldCheck size={19} className="mt-0.5 text-amber-600"/><div><p className="font-semibold text-amber-900">Last-admin protection</p><p className="mt-1 text-sm leading-6 text-amber-800">AssetHub prevents demoting the last tenant administrator. Keep a local emergency admin even when the normal admin uses SSO.</p></div></div></div>;
}
