-- Seed the standard subscription catalog for fresh and existing PostgreSQL deployments.
-- The demo tenant remains on Professional; these plans are available for assignment.

INSERT INTO plans (name, theme_preset, features, is_active)
VALUES
(
  'Starter',
  'starter',
  '{
    "max_assets": 500,
    "max_users": 25,
    "max_companies": 1,
    "max_sites": 10,
    "max_locations": 25,
    "max_departments": 50,
    "max_vendors": 100,
    "max_asset_documents": 1000,
    "max_saved_reports": 10,
    "max_api_keys": 2,
    "max_integrations": 2,
    "max_storage_gb": 10,
    "max_asset_document_size_mb": 25,
    "max_api_rate_limit_per_minute": 120,
    "session_max_days": 14,
    "max_concurrent_sessions": 3,
    "audit_retention_days": 90,
    "sso_enabled": false,
    "scim_enabled": false,
    "mfa_enabled": true,
    "audit_enabled": true,
    "advanced_reports_enabled": false,
    "scheduled_reports_enabled": false,
    "asset_documents_enabled": true,
    "bulk_import_enabled": false,
    "api_access_enabled": false,
    "webhooks_enabled": false,
    "custom_roles_enabled": false,
    "custom_fields_enabled": true,
    "approval_workflows_enabled": false
  }'::jsonb,
  true
),
(
  'Professional',
  'professional',
  '{
    "max_assets": 5000,
    "max_users": 100,
    "max_companies": 10,
    "max_sites": 100,
    "max_locations": 100,
    "max_departments": 500,
    "max_vendors": 500,
    "max_asset_documents": 10000,
    "max_saved_reports": 50,
    "max_api_keys": 10,
    "max_integrations": 10,
    "max_storage_gb": 50,
    "max_asset_document_size_mb": 50,
    "max_api_rate_limit_per_minute": 300,
    "session_max_days": 30,
    "max_concurrent_sessions": 10,
    "audit_retention_days": 365,
    "sso_enabled": true,
    "scim_enabled": false,
    "mfa_enabled": true,
    "audit_enabled": true,
    "advanced_reports_enabled": true,
    "scheduled_reports_enabled": true,
    "asset_documents_enabled": true,
    "bulk_import_enabled": true,
    "api_access_enabled": true,
    "webhooks_enabled": true,
    "custom_roles_enabled": true,
    "custom_fields_enabled": true,
    "approval_workflows_enabled": true
  }'::jsonb,
  true
),
(
  'Enterprise',
  'enterprise',
  '{
    "max_assets": 1000000,
    "max_users": 10000,
    "max_companies": 100,
    "max_sites": 1000,
    "max_locations": 5000,
    "max_departments": 10000,
    "max_vendors": 5000,
    "max_asset_documents": 100000,
    "max_saved_reports": 500,
    "max_api_keys": 100,
    "max_integrations": 100,
    "max_storage_gb": 1000,
    "max_asset_document_size_mb": 250,
    "max_api_rate_limit_per_minute": 1200,
    "session_max_days": 90,
    "max_concurrent_sessions": 50,
    "audit_retention_days": 2555,
    "sso_enabled": true,
    "scim_enabled": true,
    "mfa_enabled": true,
    "audit_enabled": true,
    "advanced_reports_enabled": true,
    "scheduled_reports_enabled": true,
    "asset_documents_enabled": true,
    "bulk_import_enabled": true,
    "api_access_enabled": true,
    "webhooks_enabled": true,
    "custom_roles_enabled": true,
    "custom_fields_enabled": true,
    "approval_workflows_enabled": true
  }'::jsonb,
  true
)
ON CONFLICT (name) DO UPDATE
SET theme_preset = EXCLUDED.theme_preset,
    features = EXCLUDED.features,
    is_active = EXCLUDED.is_active,
    updated_at = now();
