'use client';
import { useEffect, useState } from 'react';
import { apiFetch } from '../../../lib/api-client';
import { Boxes, Plus, RefreshCw, Search } from 'lucide-react';

type AssetType={id:string;name:string;prefix?:string;separator?:string;padding?:number};
export default function AssetTypesPage(){
 const [items,setItems]=useState<AssetType[]>([]); const [name,setName]=useState(''); const [prefix,setPrefix]=useState(''); const [q,setQ]=useState(''); const [busy,setBusy]=useState(true); const [error,setError]=useState<string|null>(null);
 const load=async()=>{setBusy(true);setError(null);try{const data=await apiFetch('/assets/types');setItems(Array.isArray(data)?data:[])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{await apiFetch('/assets/types',{method:'POST',body:JSON.stringify({name,prefix:prefix.toUpperCase()})});setName('');setPrefix('');load()}catch(e:any){setError(e.message)}};
 const filtered=items.filter(x=>`${x.name} ${x.prefix??''}`.toLowerCase().includes(q.toLowerCase()));
 return <div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-600">Inventory model</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Asset types</h1><p className="mt-1 text-sm text-slate-500">Define the identifiers used across your tenant inventory.</p></div><button onClick={load} className="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium shadow-sm hover:bg-slate-50"><RefreshCw size={16}/>Refresh</button></div>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><form onSubmit={create} className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Asset type name" className="h-10 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/><input required value={prefix} onChange={e=>setPrefix(e.target.value)} placeholder="Prefix e.g. LAP" className="h-10 rounded-xl border border-slate-200 px-3 text-sm uppercase outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/><button className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700"><Plus size={16}/>Create type</button></form></section>
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div className="relative w-full max-w-sm"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search asset types" className="h-9 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></div><span className="ml-4 text-xs text-slate-500">{filtered.length} types</span></div>{error&&<div className="m-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{busy?<div className="p-10 text-center text-sm text-slate-500">Loading asset types…</div>:filtered.length===0?<div className="p-12 text-center"><Boxes className="mx-auto text-slate-300" size={34}/><p className="mt-3 font-medium text-slate-700">No asset types found</p><p className="mt-1 text-sm text-slate-500">Create the first type above.</p></div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Prefix</th><th className="px-5 py-3">Format</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(x=><tr key={x.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-medium text-slate-900">{x.name}</td><td className="px-5 py-4"><span className="rounded-lg bg-blue-50 px-2 py-1 font-mono text-xs text-blue-700">{x.prefix??'—'}</span></td><td className="px-5 py-4 text-slate-500">{x.separator??''}{x.padding?` padded ${x.padding}`:'Default'}</td></tr>)}</tbody></table></div>}</section></div>;
}
