'use client';
import { useEffect, useMemo, useState } from 'react';
import { Boxes, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { apiFetch } from '../../../lib/api-client';
import { Button, EmptyState, ErrorState, LoadingState, Alert } from '../../../components/ui';
import { ConfirmDialog } from '../../../components/confirm-dialog';
import { FormField } from '../../../components/form-field';

type AssetType={id:string;name:string;prefix?:string;separator?:string;padding?:number};

export default function AssetTypesPage(){
 const [items,setItems]=useState<AssetType[]>([]); const [name,setName]=useState(''); const [prefix,setPrefix]=useState(''); const [separator,setSeparator]=useState('-'); const [padding,setPadding]=useState(6); const [q,setQ]=useState(''); const [busy,setBusy]=useState(true); const [saving,setSaving]=useState(false); const [editing,setEditing]=useState<AssetType|null>(null); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null); const [deleteTarget,setDeleteTarget]=useState<AssetType|null>(null); const [deleting,setDeleting]=useState(false);
 const load=async()=>{setBusy(true);setError(null);try{const data=await apiFetch('/assets/types');const raw=Array.isArray(data)?data:[];const normalized=raw.map((item:any)=>({id:String(item?.id??item?._id??''),name:String(item?.name??''),prefix:item?.prefix??item?.numberingRule?.prefix,separator:item?.separator??item?.numberingRule?.separator,padding:item?.padding??item?.numberingRule?.padding})).filter((item:AssetType)=>item.id&&item.name);setItems(normalized)}catch(e:any){setError(e?.message||'Unable to load asset types.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const resetForm=()=>{setEditing(null);setName('');setPrefix('');setSeparator('-');setPadding(6)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError(null);setMessage(null);try{const payload={name:name.trim(),prefix:prefix.trim().toUpperCase()||undefined,separator:separator||'-',padding:Number(padding)||6};if(editing){await apiFetch(`/assets/types/${editing.id}`,{method:'PATCH',body:JSON.stringify(payload)});setMessage('Asset type updated.')}else{await apiFetch('/assets/types',{method:'POST',body:JSON.stringify(payload)});setMessage('Asset type created.')}resetForm();await load()}catch(e:any){setError(e?.message||'Unable to save asset type.')}finally{setSaving(false)}};
 const remove=async()=>{if(!deleteTarget)return;setDeleting(true);setError(null);setMessage(null);try{await apiFetch(`/assets/types/${deleteTarget.id}`,{method:'DELETE'});setMessage('Asset type deleted.');setDeleteTarget(null);await load()}catch(e:any){setError(e?.message||'Unable to delete asset type.')}finally{setDeleting(false)}};
 const startEdit=(item:AssetType)=>{setEditing(item);setName(item.name);setPrefix(item.prefix??'');setSeparator(item.separator??'-');setPadding(item.padding??6);setError(null);setMessage(null)};
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.prefix??''}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 return <div className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--theme-link)]">Inventory model</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Asset types</h1><p className="mt-1 text-sm text-slate-500">Define the identifiers used across your tenant inventory.</p></div><Button variant="secondary" onClick={()=>void load()} loading={busy} icon={<RefreshCw size={16}/>}>Refresh</Button></header>
 {error&&<ErrorState title="Unable to load asset types" message={error} onRetry={()=>void load()}/>} {message&&<Alert tone="success" title={message}/>} 
 <section className="panel p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-slate-950">{editing?'Edit asset type':'Create asset type'}</h2>{editing&&<Button type="button" variant="ghost" size="sm" onClick={resetForm} icon={<X size={14}/>}>Cancel</Button>}</div><form onSubmit={save} className="mt-4 grid gap-3 md:grid-cols-[1fr_180px_120px_120px_auto]"><FormField label="Name" required value={name} onChange={e=>setName(e.target.value)} placeholder="Asset type name"/><FormField label="Prefix" value={prefix} onChange={e=>setPrefix(e.target.value)} placeholder="e.g. LAP"/><FormField label="Separator" value={separator} onChange={e=>setSeparator(e.target.value)} placeholder="-"/><FormField label="Padding" type="number" value={String(padding)} onChange={e=>setPadding(Number(e.target.value))}/><div className="flex items-end"><Button className="h-10 w-full" loading={saving} icon={<Plus size={16}/>}>{editing?'Save changes':'Create type'}</Button></div></form><p className="mt-2 text-xs text-slate-500">Leave Prefix empty to let AssetHub generate a short prefix automatically.</p></section>
 <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-4"><label className="flex min-h-10 w-full max-w-sm items-center gap-2 rounded-xl border border-slate-200 bg-white px-3"><Search className="text-slate-400" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search asset types" className="w-full bg-transparent py-2 text-sm outline-none"/></label><span className="ml-4 text-xs text-slate-500">{filtered.length} types</span></div>{busy?<LoadingState label="Loading asset types…"/>:filtered.length===0?<EmptyState title="No asset types found" text="Create the first type above."/>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Prefix</th><th className="px-5 py-3">Format</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(x=><tr key={x.id} className="hover:bg-[var(--theme-primary-soft)]/40"><td className="px-5 py-4 font-medium text-slate-900">{x.name}</td><td className="px-5 py-4"><span className="badge badge-brand">{x.prefix??'auto'}</span></td><td className="px-5 py-4 text-slate-500">{x.separator??'-'} padded {x.padding??6}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Button type="button" variant="secondary" size="sm" onClick={()=>startEdit(x)} icon={<Pencil size={14}/>}>Edit</Button><Button type="button" variant="danger" size="sm" onClick={()=>setDeleteTarget(x)} icon={<Trash2 size={14}/>}>Delete</Button></div></td></tr>)}</tbody></table></div>}</section>
 <ConfirmDialog open={Boolean(deleteTarget)} title="Delete asset type?" message={deleteTarget?`Delete “${deleteTarget.name}”? Existing assets may prevent deletion.`:undefined} confirmLabel="Delete type" danger loading={deleting} onCancel={()=>!deleting&&setDeleteTarget(null)} onConfirm={()=>void remove()}/>
 </div>;
}
