'use client';
import { useEffect, useMemo, useState } from 'react';
import { Boxes, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { apiFetch } from '../../../lib/api-client';

type AssetType={id:string;name:string;prefix?:string;separator?:string;padding?:number};

export default function AssetTypesPage(){
 const [items,setItems]=useState<AssetType[]>([]); const [name,setName]=useState(''); const [prefix,setPrefix]=useState(''); const [q,setQ]=useState(''); const [busy,setBusy]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const [editing,setEditing]=useState<AssetType|null>(null);
 const load=async()=>{setBusy(true);setError(null);try{const data=await apiFetch('/assets/types');setItems(Array.isArray(data)?data:[])}catch(e:any){setError(e.message||'Unable to load asset types.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 function resetForm(){setEditing(null);setName('');setPrefix('');}
 function startEdit(item:AssetType){setEditing(item);setName(item.name);setPrefix(item.prefix??'');setError(null)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError(null);try{if(editing){await apiFetch(`/assets/types/${editing.id}`,{method:'PATCH',body:JSON.stringify({name:name.trim(),prefix:prefix.trim().toUpperCase(),separator:editing.separator??'-',padding:editing.padding??6})})}else{await apiFetch('/assets/types',{method:'POST',body:JSON.stringify({name:name.trim(),prefix:prefix.trim().toUpperCase()})})}resetForm();await load()}catch(e:any){setError(e.message||'Unable to save asset type.')}finally{setSaving(false)}};
 const remove=async(item:AssetType)=>{if(!window.confirm(`Delete asset type “${item.name}”? This is only allowed when no assets use it.`))return;setError(null);try{await apiFetch(`/assets/types/${item.id}`,{method:'DELETE'});if(editing?.id===item.id)resetForm();await load()}catch(e:any){setError(e.message||'Unable to delete asset type.')}};
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.prefix??''}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
 return <div className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-600">Inventory model</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Asset types</h1><p className="mt-1 text-sm text-slate-500">Create, edit and remove the inventory types used by your tenant.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium shadow-sm hover:bg-slate-50"><RefreshCw size={16}/>Refresh</button></div>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold text-slate-900">{editing?'Edit asset type':'Add asset type'}</h2>{editing&&<button onClick={resetForm} className="inline-flex items-center gap-1 text-xs font-semibold text-slate-500"><X size={14}/>Cancel</button>}</div><form onSubmit={save} className="grid gap-3 md:grid-cols-[1fr_180px_auto]"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Asset type name" className="h-10 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/><input required value={prefix} onChange={e=>setPrefix(e.target.value)} placeholder="Prefix e.g. LAP" className="h-10 rounded-xl border border-slate-200 px-3 text-sm uppercase outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/><button disabled={saving} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-60"><Plus size={16}/>{saving?(editing?'Saving…':'Creating…'):(editing?'Save changes':'Create type')}</button></form>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}</section>
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div className="relative w-full max-w-sm"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search asset types" className="h-9 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></div><span className="ml-4 text-xs text-slate-500">{filtered.length} types</span></div>{busy?<div className="p-10 text-center text-sm text-slate-500">Loading asset types…</div>:filtered.length===0?<div className="p-12 text-center"><Boxes className="mx-auto text-slate-300" size={34}/><p className="mt-3 font-medium text-slate-700">No asset types found</p><p className="mt-1 text-sm text-slate-500">Create the first type above.</p></div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Prefix</th><th className="px-5 py-3">Format</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(x=><tr key={x.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-medium text-slate-900">{x.name}</td><td className="px-5 py-4"><span className="rounded-lg bg-blue-50 px-2 py-1 font-mono text-xs text-blue-700">{x.prefix??'—'}</span></td><td className="px-5 py-4 text-slate-500">{x.separator??''}{x.padding?` padded ${x.padding}`:'Default'}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={()=>startEdit(x)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-white"><Pencil size={14}/>Edit</button><button onClick={()=>void remove(x)} className="inline-flex items-center gap-1.5 rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700 hover:bg-red-50"><Trash2 size={14}/>Delete</button></div></td></tr>)}</tbody></table></div>}</section></div>;
}
