'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Boxes, CheckCircle2, ClipboardCheck, ClipboardList, History, Plus, RefreshCw, Search, UserRoundCheck, UserRoundX, X, type LucideIcon } from 'lucide-react';
import { apiFetch } from '../../../lib/api-client';
import { StatusBadge, Button, EmptyState } from '../../../components/ui';

type Asset = { id: string; assetNumber: string; status: string; condition?: string; assetType?: { name: string } };
type User = { id: string; email: string; firstName: string; lastName: string; isActive: boolean };
type Assignment = { id: string; assetId: string; userId?: string; assignedAt: string; returnedAt?: string; notes?: string; conditionAtReturn?: string; active: boolean; asset?: Asset | null; user?: User | null };
const RETURN_CONDITIONS = ['NEW','GOOD','FAIR','DAMAGED','NEEDS_INSPECTION'];
type Metric = { label: string; value: number; desc: string; iconClass: string; Icon: LucideIcon };

function getUserFacingError(error: unknown, fallback: string) {
  const message = error instanceof Error ? error.message : '';
  if (message.includes('Asset is already assigned')) return 'This asset is already assigned. Refresh the list and choose an available asset.';
  if (message.includes('cannot be assigned while in')) return message;
  if (message.includes('Damaged or inspection-required assets')) return 'This asset cannot be assigned because it is damaged or requires inspection.';
  if (message.includes('inactive user')) return 'That user is inactive and cannot receive an asset.';
  return message || fallback;
}

export default function AssignmentsPage() {
  const [assets,setAssets]=useState<Asset[]>([]); const [users,setUsers]=useState<User[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]);
  const [query,setQuery]=useState(''); const [assetId,setAssetId]=useState(''); const [userId,setUserId]=useState(''); const [notes,setNotes]=useState('');
  const [showAssign,setShowAssign]=useState(false); const [returning,setReturning]=useState<Assignment|null>(null); const [returnCondition,setReturnCondition]=useState('GOOD'); const [returnNotes,setReturnNotes]=useState('');
  const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);

  async function load(){setLoading(true);setError(null);try{const [assetData,userData,assignmentData]=await Promise.all([apiFetch('/assets?status=IN_STOCK&page=1&pageSize=100'),apiFetch('/users'),apiFetch('/assets/assignments')]);setAssets(Array.isArray(assetData?.items)?assetData.items:[]);setUsers(Array.isArray(userData)?userData:[]);setAssignments(Array.isArray(assignmentData)?assignmentData:[]);}catch(err:unknown){setError(getUserFacingError(err,'Unable to load assignment data.'));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const activeAssignments=useMemo(()=>assignments.filter(item=>item.active),[assignments]);
  const returnedAssignments=useMemo(()=>assignments.filter(item=>!item.active),[assignments]);
  const activeAssetIds=useMemo(()=>new Set(activeAssignments.map(item=>item.assetId)),[activeAssignments]);
  const availableAssets=useMemo(()=>assets.filter(asset=>!activeAssetIds.has(asset.id)),[assets,activeAssetIds]);
  const assignableAssets=useMemo(()=>availableAssets.filter(a=>a.condition!=='DAMAGED'&&a.condition!=='NEEDS_INSPECTION'),[availableAssets]);
  const filteredActive=useMemo(()=>{const value=query.trim().toLowerCase();if(!value)return activeAssignments;return activeAssignments.filter(item=>`${item.asset?.assetNumber??''} ${item.asset?.assetType?.name??''} ${item.user?.firstName??''} ${item.user?.lastName??''} ${item.user?.email??''} ${item.notes??''}`.toLowerCase().includes(value));},[activeAssignments,query]);
  const metrics: Metric[]=[
    {label:'Active custody',value:activeAssignments.length,desc:'Employees currently holding assets',iconClass:'text-emerald-600 bg-emerald-50',Icon:UserRoundCheck},
    {label:'Ready to issue',value:assignableAssets.length,desc:'Eligible assets awaiting custody',iconClass:'text-blue-600 bg-blue-50',Icon:Boxes},
    {label:'Returned',value:returnedAssignments.length,desc:'Closed custody records',iconClass:'text-slate-600 bg-slate-100',Icon:UserRoundX},
    {label:'Total records',value:assignments.length,desc:'Complete assignment history',iconClass:'text-violet-600 bg-violet-50',Icon:History},
  ];
  async function assign(){if(!assetId||!userId)return;setSubmitting(true);setError(null);setSuccess(null);try{await apiFetch(`/assets/${assetId}/assign`,{method:'POST',body:JSON.stringify({userId,notes:notes.trim()||undefined})});setAssetId('');setUserId('');setNotes('');setShowAssign(false);setSuccess('Asset assigned successfully.');await load();}catch(err:unknown){setError(getUserFacingError(err,'Unable to assign asset. Refresh the list and try again.'));await load();}finally{setSubmitting(false);}}
  async function unassign(){if(!returning)return;setSubmitting(true);setError(null);setSuccess(null);try{await apiFetch(`/assets/${returning.assetId}/unassign`,{method:'POST',body:JSON.stringify({condition:returnCondition,notes:returnNotes.trim()||undefined})});setSuccess('Asset returned successfully and custody has been closed.');setReturning(null);setReturnNotes('');setReturnCondition('GOOD');await load();}catch(err:unknown){setError(getUserFacingError(err,'Unable to return asset. Please refresh the list and try again.'));}finally{setSubmitting(false);}}
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]">Operations · Custody</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Asset custody</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">One workflow for issuing, acknowledging, returning and auditing physical asset ownership.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => void load()} loading={loading} icon={<RefreshCw size={16}/>}>Refresh</Button><Button onClick={()=>setShowAssign(v=>!v)} icon={showAssign?<X size={16}/>:<Plus size={16}/>}>{showAssign?'Close':'Assign asset'}</Button></div></header>
    {success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800" role="status"><div className="flex items-center gap-2 font-semibold"><CheckCircle2 size={17}/> {success}</div></div>}
    {error&&<div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900" role="alert"><div className="flex items-center justify-between gap-4"><span>{error}</span><button onClick={()=>setError(null)} aria-label="Dismiss error" className="rounded-lg p-1 hover:bg-amber-100"><X size={16}/></button></div></div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Custody lifecycle</p><h2 className="mt-1 text-base font-semibold text-slate-950">From available asset to closed custody record</h2></div><ClipboardCheck className="text-[var(--theme-primary)]" size={22}/></div><div className="mt-5 grid gap-3 md:grid-cols-5">{[['01','Available',String(assignableAssets.length),'Ready to issue'],['02','Assigned',String(activeAssignments.length),'Current custody'],['03','Acknowledgement','—','Recorded from employee'],['04','Returned',String(returnedAssignments.length),'Closed custody'],['05','History',String(assignments.length),'Audit trail']].map(([step,label,value,desc],i)=><div key={label} className="relative rounded-xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-center justify-between"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[var(--theme-primary-soft)] text-xs font-bold text-[var(--theme-primary)]">{step}</span>{i<4&&<ArrowRight className="hidden text-slate-300 md:block" size={16}/>}</div><p className="mt-3 text-sm font-semibold text-slate-900">{label}</p><p className="mt-1 text-xl font-bold text-slate-950">{value}</p><p className="mt-1 text-[11px] text-slate-500">{desc}</p></div>)}</div></section>
    {showAssign&&<section className="rounded-2xl border border-[var(--theme-primary)]/25 bg-[var(--theme-primary-soft)] p-5 shadow-sm"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-[var(--theme-primary)] shadow-sm"><ClipboardList size={19}/></div><div><h2 className="font-semibold text-slate-950">Issue an asset</h2><p className="mt-1 text-sm text-slate-500">Select an eligible asset and an active employee. The assignment becomes the current custody record.</p></div></div><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_1fr_1.3fr_auto]"><select value={assetId} onChange={e=>setAssetId(e.target.value)} className="field h-11"><option value="">Select available asset</option>{assignableAssets.map(asset=><option key={asset.id} value={asset.id}>{asset.assetNumber}{asset.assetType?.name?` · ${asset.assetType.name}`:''}</option>)}</select><select value={userId} onChange={e=>setUserId(e.target.value)} className="field h-11"><option value="">Select active employee</option>{users.filter(user=>user.isActive).map(user=><option key={user.id} value={user.id}>{user.firstName} {user.lastName} · {user.email}</option>)}</select><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional assignment notes" className="field h-11"/><Button disabled={!assetId||!userId||submitting} loading={submitting} onClick={()=>void assign()} icon={<CheckCircle2 size={16}/>}>Issue asset</Button></div>{assignableAssets.length===0&&<p className="mt-3 text-xs font-medium text-amber-700">No eligible in-stock assets are currently available.</p>}</section>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,desc,iconClass,Icon})=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`grid h-10 w-10 place-items-center rounded-xl ${iconClass}`}><Icon size={18}/></div><p className="mt-4 text-sm font-semibold text-slate-800">{label}</p><p className="mt-1 text-2xl font-bold text-slate-950">{loading?'—':value}</p><p className="mt-1 text-xs text-slate-500">{desc}</p></div>)}</section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-semibold text-slate-950">Current custody</h2><p className="mt-1 text-xs text-slate-500">Every row represents one asset currently held by an employee.</p></div><div className="relative w-full max-w-md"><Search size={16} className="absolute left-3 top-2.5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search asset, employee, email or notes" className="field h-10 pl-9" aria-label="Search current custody"/></div></div>{loading?<div className="space-y-3 p-5">{[1,2,3,4,5].map(i=><div key={i} className="h-16 animate-pulse rounded-xl bg-slate-100"/>)}</div>:filteredActive.length===0?<EmptyState title={query?'No custody records match your search':'No active custody records'} text={query?'Try another employee, asset number or note.':'Issue an asset to an employee to start tracking custody.'} action={query?'Clear search':'Issue an asset'} onAction={()=>query?setQuery(''):setShowAssign(true)}/>:<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Asset</th><th className="px-5 py-3">Custodian</th><th className="px-5 py-3">Issued</th><th className="px-5 py-3">Condition</th><th className="px-5 py-3">Notes</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filteredActive.map(item=><tr key={item.id} className="transition-colors hover:bg-[var(--theme-primary-soft)]/50"><td className="px-5 py-4"><Link href={`/assets/${item.assetId}`} className="font-semibold text-slate-900 hover:text-[var(--theme-link)]">{item.asset?.assetNumber??item.assetId}</Link><div className="mt-1 text-xs text-slate-400">{item.asset?.assetType?.name??'Asset'}</div></td><td className="px-5 py-4"><div className="font-medium text-slate-900">{item.user?`${item.user.firstName} ${item.user.lastName}`:'—'}</div><div className="text-xs text-slate-500">{item.user?.email??'Unknown employee'}</div></td><td className="px-5 py-4 text-slate-700">{new Date(item.assignedAt).toLocaleDateString()}</td><td className="px-5 py-4"><StatusBadge status={item.asset?.condition??'UNKNOWN'}/></td><td className="max-w-xs px-5 py-4 text-slate-500">{item.notes||'—'}</td><td className="px-5 py-4 text-right"><Button variant="secondary" size="sm" disabled={submitting} onClick={()=>{setReturning(item);setReturnCondition(item.asset?.condition&&RETURN_CONDITIONS.includes(item.asset.condition)?item.asset.condition:'GOOD');setReturnNotes('')}} icon={<ArrowRight size={14}/>}>Return</Button></td></tr>)}</tbody></table></div>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="flex items-center gap-2"><History size={18} className="text-violet-600"/><div><h2 className="font-semibold text-slate-950">Recent custody history</h2><p className="mt-1 text-xs text-slate-500">Recently closed assignments remain available for audit.</p></div></div></div>{returnedAssignments.length===0?<div className="p-8 text-center text-sm text-slate-500">No returned custody records yet.</div>:<div className="divide-y divide-slate-100">{returnedAssignments.slice(0,10).map(item=><div key={item.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Link href={`/assets/${item.assetId}`} className="font-semibold text-slate-900 hover:text-[var(--theme-link)]">{item.asset?.assetNumber??item.assetId}</Link><StatusBadge status={item.conditionAtReturn??'RETURNED'}/></div><p className="mt-1 text-xs text-slate-500">{item.user?`${item.user.firstName} ${item.user.lastName}`:'Unknown employee'} · issued {new Date(item.assignedAt).toLocaleDateString()}</p></div><span className="shrink-0 text-xs font-medium text-slate-500">Returned {item.returnedAt?new Date(item.returnedAt).toLocaleDateString():'—'}</span></div>)}</div>}</section>
    {returning&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="return-dialog-title"><div className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--theme-link)]">Close custody</p><h2 id="return-dialog-title" className="mt-1 text-xl font-bold text-slate-950">Return {returning.asset?.assetNumber??'asset'}</h2><p className="mt-1 text-sm text-slate-500">Record the condition at return before closing this assignment.</p></div><button onClick={()=>setReturning(null)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Close"><X size={18}/></button></div><div className="mt-5 space-y-4"><label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-700">Condition at return</span><select value={returnCondition} onChange={e=>setReturnCondition(e.target.value)} className="field h-11 w-full">{RETURN_CONDITIONS.map(condition=><option key={condition} value={condition}>{condition.replaceAll('_',' ')}</option>)}</select></label><label className="block"><span className="mb-1.5 block text-sm font-semibold text-slate-700">Return notes <span className="font-normal text-slate-400">(optional)</span></span><textarea value={returnNotes} onChange={e=>setReturnNotes(e.target.value)} rows={4} placeholder="Condition details, accessories returned, damage, etc." className="field w-full resize-none"/></label></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setReturning(null)}>Cancel</Button><Button onClick={()=>void unassign()} loading={submitting} icon={<CheckCircle2 size={16}/>}>Complete return</Button></div></div></div>}
  </div>;
}
