'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { apiFetch } from '../../../lib/api-client';
import { ArrowRight, Boxes, CheckCircle2, ClipboardList, History, Plus, RefreshCw, Search, UserRoundCheck, UserRoundX, type LucideIcon } from 'lucide-react';

type Asset = { id: string; assetNumber: string; status: string; condition?: string; assetType?: { name: string } };
type User = { id: string; email: string; firstName: string; lastName: string; isActive: boolean };
type Assignment = { id: string; assetId: string; userId?: string; assignedAt: string; returnedAt?: string; notes?: string; conditionAtReturn?: string; active: boolean; asset?: Asset | null; user?: User | null };
const RETURN_CONDITIONS = ['NEW','GOOD','FAIR','DAMAGED','NEEDS_INSPECTION'];

type AssignmentMetric = { label: string; value: number; icon: LucideIcon; iconClass: string };

function getUserFacingError(error: unknown, fallback: string) {
  const message = error instanceof Error ? error.message : '';
  if (message.includes('Asset is already assigned')) return 'This asset is already assigned. Refresh the list and choose an available asset.';
  if (message.includes('cannot be assigned while in')) return message;
  if (message.includes('Damaged or inspection-required assets')) return 'This asset cannot be assigned because it is damaged or requires inspection.';
  if (message.includes('inactive user')) return 'That user is inactive and cannot receive an asset.';
  return message || fallback;
}

export default function AssignmentsPage() {
  const [assets,setAssets]=useState<Asset[]>([]); const [users,setUsers]=useState<User[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]); const [query,setQuery]=useState(''); const [assetId,setAssetId]=useState(''); const [userId,setUserId]=useState(''); const [notes,setNotes]=useState(''); const [showAssign,setShowAssign]=useState(false); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);
  async function load(){setLoading(true);setError(null);try{const [assetData,userData,assignmentData]=await Promise.all([apiFetch('/assets?status=IN_STOCK&page=1&pageSize=100'),apiFetch('/users'),apiFetch('/assets/assignments')]);setAssets(Array.isArray(assetData?.items)?assetData.items:[]);setUsers(Array.isArray(userData)?userData:[]);setAssignments(Array.isArray(assignmentData)?assignmentData:[]);}catch(err:unknown){setError(getUserFacingError(err,'Unable to load assignment data.'));}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  const activeAssignments=useMemo(()=>assignments.filter(item=>item.active),[assignments]); const returnedAssignments=useMemo(()=>assignments.filter(item=>!item.active),[assignments]); const activeAssetIds=useMemo(()=>new Set(activeAssignments.map(item=>item.assetId)),[activeAssignments]); const availableAssets=useMemo(()=>assets.filter(asset=>!activeAssetIds.has(asset.id)),[assets,activeAssetIds]);
  const filteredActive=useMemo(()=>{const value=query.trim().toLowerCase();if(!value)return activeAssignments;return activeAssignments.filter(item=>`${item.asset?.assetNumber??''} ${item.asset?.assetType?.name??''} ${item.user?.firstName??''} ${item.user?.lastName??''} ${item.user?.email??''} ${item.notes??''}`.toLowerCase().includes(value));},[activeAssignments,query]);
  async function assign(){if(!assetId||!userId)return;setSubmitting(true);setError(null);setSuccess(null);try{await apiFetch(`/assets/${assetId}/assign`,{method:'POST',body:JSON.stringify({userId,notes:notes.trim()||undefined})});setAssetId('');setUserId('');setNotes('');setShowAssign(false);setSuccess('Asset assigned successfully.');await load();}catch(err:unknown){setError(getUserFacingError(err,'Unable to assign asset. Refresh the list and try again.'));await load();}finally{setSubmitting(false);}}
  async function unassign(item:Assignment){if(!item.assetId)return;const condition=window.prompt(`Return condition (${RETURN_CONDITIONS.join(', ')}):`,item.asset?.condition??'GOOD')?.trim().toUpperCase();if(!condition||!RETURN_CONDITIONS.includes(condition))return;const note=window.prompt('Return notes (optional):','Returned from assignment workspace.')?.trim();setSubmitting(true);setError(null);setSuccess(null);try{await apiFetch(`/assets/${item.assetId}/unassign`,{method:'POST',body:JSON.stringify({condition,notes:note||undefined})});setSuccess('Asset returned successfully.');await load();}catch(err:unknown){setError(getUserFacingError(err,'Unable to return asset. Please refresh and try again.'));}finally{setSubmitting(false);}}
  const metrics: AssignmentMetric[] = [
    { label: 'Active assignments', value: activeAssignments.length, icon: UserRoundCheck, iconClass: 'text-emerald-600 bg-emerald-50' },
    { label: 'Available assets', value: availableAssets.length, icon: Boxes, iconClass: 'text-blue-600 bg-blue-50' },
    { label: 'Returned records', value: returnedAssignments.length, icon: UserRoundX, iconClass: 'text-slate-600 bg-slate-100' },
    { label: 'Assignment history', value: assignments.length, icon: History, iconClass: 'text-violet-600 bg-violet-50' },
  ];
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]">Operations</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Assignments</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Assign assets to active users, process formal returns, and keep a complete ownership history.</p></div><div className="flex flex-wrap gap-2"><button onClick={load} disabled={loading} className="ui-interactive inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-700 shadow-sm"><RefreshCw size={16} className={loading?'animate-spin':''}/>Refresh</button><button onClick={()=>setShowAssign(v=>!v)} className="ui-interactive inline-flex items-center gap-2 rounded-xl bg-[var(--theme-primary)] px-4 py-2.5 text-sm font-semibold text-white shadow-sm"><Plus size={16}/>Assign asset</button></div></div>
    {success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700" role="status">{success}</div>}{error&&<div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800" role="alert">{error}</div>}
    {showAssign&&<section className="rounded-2xl border border-[var(--theme-primary)]/20 bg-[var(--theme-primary-soft)] p-5 shadow-sm"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-[var(--theme-primary)] shadow-sm"><ClipboardList size={19}/></div><div><h2 className="font-semibold text-slate-950">Create assignment</h2><p className="mt-1 text-sm text-slate-500">Only unassigned, assignable assets and active tenant users are eligible.</p></div></div><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_1fr_1.3fr_auto]"><select value={assetId} onChange={e=>setAssetId(e.target.value)} className="field h-11"><option value="">Select asset</option>{availableAssets.filter(a=>a.condition!=='DAMAGED'&&a.condition!=='NEEDS_INSPECTION').map(asset=><option key={asset.id} value={asset.id}>{asset.assetNumber}{asset.assetType?.name?` · ${asset.assetType.name}`:''}</option>)}</select><select value={userId} onChange={e=>setUserId(e.target.value)} className="field h-11"><option value="">Select user</option>{users.filter(user=>user.isActive).map(user=><option key={user.id} value={user.id}>{user.firstName} {user.lastName} · {user.email}</option>)}</select><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional assignment notes" className="field h-11"/><button disabled={!assetId||!userId||submitting} onClick={assign} className="ui-interactive inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-semibold text-white disabled:opacity-50">{submitting?<RefreshCw size={16} className="animate-spin"/>:<CheckCircle2 size={16}/>}Assign</button></div></section>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,icon:Icon,iconClass})=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`grid h-10 w-10 place-items-center rounded-xl ${iconClass}`}><Icon size={18}/></div><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-950">{loading?'—':value}</p></div>)}</div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-semibold text-slate-950">Active assignments</h2><p className="mt-1 text-xs text-slate-500">Current custody records only.</p></div><div className="relative w-full max-w-md"><Search size={16} className="absolute left-3 top-2.5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search asset, user, or notes" className="field h-10 pl-9" aria-label="Search assignments"/></div></div>{loading?<div className="space-y-3 p-5">{[1,2,3,4,5].map(i=><div key={i} className="h-14 animate-pulse rounded-xl bg-slate-100"/>)}</div>:filteredActive.length===0?<div className="p-14 text-center"><ClipboardList className="mx-auto text-slate-300" size={38}/><p className="mt-4 font-semibold text-slate-800">No active assignments</p><p className="mt-1 text-sm text-slate-500">Assign an asset to a user to start tracking ownership.</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Asset</th><th className="px-5 py-3">Assigned to</th><th className="px-5 py-3">Assigned</th><th className="px-5 py-3">Condition</th><th className="px-5 py-3">Notes</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filteredActive.map(item=><tr key={item.id} className="hover:bg-[var(--theme-primary-soft)]/50"><td className="px-5 py-4"><Link href={`/assets/${item.assetId}`} className="font-semibold text-slate-900 hover:text-[var(--theme-link)]">{item.asset?.assetNumber??item.assetId}</Link><div className="mt-1 text-xs text-slate-400">{item.asset?.assetType?.name??'Asset'}</div></td><td className="px-5 py-4"><div className="font-medium text-slate-900">{item.user?`${item.user.firstName} ${item.user.lastName}`:'—'}</div><div className="text-xs text-slate-500">{item.user?.email??'Unknown user'}</div></td><td className="px-5 py-4 text-slate-700">{new Date(item.assignedAt).toLocaleDateString()}</td><td className="px-5 py-4 text-xs text-slate-600">{item.asset?.condition?.replace('_',' ')??'—'}</td><td className="max-w-xs px-5 py-4 text-slate-500">{item.notes||'—'}</td><td className="px-5 py-4 text-right"><button disabled={submitting} onClick={()=>void unassign(item)} className="ui-interactive inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 disabled:opacity-50">Return <ArrowRight size={14}/></button></td></tr>)}</tbody></table></div>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><History size={18} className="text-violet-600"/><h2 className="font-semibold text-slate-950">Recent returned records</h2></div>{returnedAssignments.length===0?<p className="mt-4 text-sm text-slate-500">No returned assignment records yet.</p>:<div className="mt-4 divide-y divide-slate-100">{returnedAssignments.slice(0,10).map(item=><div key={item.id} className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-slate-900">{item.asset?.assetNumber??item.assetId}</p><p className="text-xs text-slate-500">{item.user?`${item.user.firstName} ${item.user.lastName}`:'Unknown user'} · assigned {new Date(item.assignedAt).toLocaleDateString()}</p></div><span className="text-xs font-medium text-slate-500">Returned {item.returnedAt?new Date(item.returnedAt).toLocaleDateString():'—'}{item.conditionAtReturn?` · ${item.conditionAtReturn.replace('_',' ')}`:''}</span></div>)}</div>}</section>
  </div>;
}
