'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, RefreshCw, Search, ShieldCheck, Users } from 'lucide-react';
import { systemFetch } from '../../../lib/system-api';
import { permissionMeta } from '../../../components/rbac/PermissionPresentation';

type Role={id:string;name?:string;isSystem?:boolean;permissions?:Array<{permissionKey?:string|null}>};
type User={id:string;email:string;firstName:string;lastName:string;isActive:boolean;roleIds?:string[]};

export default function AccessReview(){
 const [users,setUsers]=useState<User[]>([]),[roles,setRoles]=useState<Role[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const [u,r]=await Promise.all([systemFetch('/system/users'),systemFetch('/system/roles')]);setUsers(Array.isArray(u)?u:[]);setRoles(Array.isArray(r)?r:[])}catch(e:any){setError(e?.message??'Unable to load access review.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const roleMap=useMemo(()=>new Map(roles.map(r=>[r.id,r])),[roles]);
 const filtered=useMemo(()=>users.filter(u=>`${u.firstName} ${u.lastName} ${u.email}`.toLowerCase().includes(query.toLowerCase())),[users,query]);
 const permissionCount=(u:User)=>new Set((u.roleIds??[]).flatMap(id=>(roleMap.get(id)?.permissions??[]).map(p=>p.permissionKey).filter(Boolean) as string[])).size;
 return <div className="space-y-6">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-600">Security & Access</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Access Review</h1><p className="mt-2 text-sm text-slate-500">Read-only central view of platform administrators, roles and effective capabilities.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-semibold text-slate-700 disabled:opacity-50"><RefreshCw size={15} className={loading?'animate-spin':''}/>Refresh</button></header>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  <section className="grid gap-4 sm:grid-cols-3"><Metric icon={<Users size={18}/>} label="Platform users" value={users.length}/><Metric icon={<ShieldCheck size={18}/>} label="Roles" value={roles.length}/><Metric icon={<ShieldCheck size={18}/>} label="Active users" value={users.filter(u=>u.isActive).length}/></section>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-4"><div className="relative max-w-md"><Search size={16} className="absolute left-3 top-2.5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search platform users" className="h-10 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-violet-400"/></div></div>{loading?<div className="p-8 text-sm text-slate-500">Loading access data…</div>:filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">No platform users found.</div>:<div className="divide-y divide-slate-100">{filtered.map(u=>{const assigned=(u.roleIds??[]).map(id=>roleMap.get(id)).filter(Boolean) as Role[];const pCount=permissionCount(u);return <div key={u.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700"><ShieldCheck size={18}/></div><div className="min-w-0"><p className="truncate font-semibold text-slate-950">{u.firstName} {u.lastName}</p><p className="truncate text-sm text-slate-500">{u.email}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${u.isActive?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-slate-200 bg-slate-100 text-slate-600'}`}>{u.isActive?'Active':'Inactive'}</span><span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 text-xs font-semibold text-slate-600">{assigned.length} role{assigned.length===1?'':'s'}</span><span className="rounded-full border border-slate-200 bg-white px-2.5 py-1 text-xs font-semibold text-slate-600">{pCount} capabilities</span><Link href={`/system/user-control?userId=${encodeURIComponent(u.id)}`} className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">View 360<ArrowRight size={13}/></Link></div></div><div className="mt-4 flex flex-wrap gap-2">{assigned.length?assigned.map(r=><span key={r.id} className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${r.isSystem?'border-amber-200 bg-amber-50 text-amber-700':'border-violet-200 bg-violet-50 text-violet-700'}`}>{r.name||'Unnamed role'}</span>):<span className="text-xs text-slate-400">No roles assigned</span>}</div><div className="mt-3 flex flex-wrap gap-2">{[...new Set(assigned.flatMap(r=>(r.permissions??[]).map(p=>p.permissionKey).filter(Boolean) as string[]))].slice(0,6).map(key=><span key={key} title={key} className="rounded-full border border-slate-200 bg-slate-50 px-2 py-1 text-[11px] font-semibold text-slate-600">{permissionMeta(key).label}</span>)}</div></div>})}</div>}</section>
 </div>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-700">{icon}</div><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-xl font-bold text-slate-950">{value}</p></div>}
