'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Copy, KeyRound, Pencil, Plus, RefreshCw, Search, ShieldCheck, UserCheck, UserRound, UserX, Users, X } from 'lucide-react';
import { apiFetch } from '../../../lib/api-client';
import { Button, Badge, EmptyState, ErrorState, LoadingState, StatusBadge } from '../../../components/ui';
import { FormField, FormSelect } from '../../../components/form-field';
import { ConfirmDialog } from '../../../components/confirm-dialog';
import { Modal, ModalBody } from '../../../components/modal';

type User={id:string;employeeId?:string;email:string;firstName:string;lastName:string;jobTitle?:string;phone?:string;departmentId?:string;locationId?:string;isActive:boolean;forcePasswordReset?:boolean;roleIds?:string[]};
type Role={id:string;name:string;isSystem:boolean;permissions?:{permissionKey?:string}[]};
type ModalKind='create'|'edit'|'roles'|'invite'|null;
const emptyForm={employeeId:'',email:'',firstName:'',lastName:'',jobTitle:'',phone:'',departmentId:'',locationId:''};

export default function UsersPage(){
 const [users,setUsers]=useState<User[]>([]),[roles,setRoles]=useState<Role[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState<'ALL'|'ACTIVE'|'INACTIVE'>('ALL'),[roleFilter,setRoleFilter]=useState('ALL');
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[modal,setModal]=useState<ModalKind>(null),[selected,setSelected]=useState<User|null>(null),[form,setForm]=useState(emptyForm),[roleIds,setRoleIds]=useState<string[]>([]),[inviteUrl,setInviteUrl]=useState(''),[confirm,setConfirm]=useState<User|null>(null);
 async function load(){setLoading(true);setError(null);try{const[u,r]=await Promise.all([apiFetch('/users'),apiFetch('/roles')]);setUsers(Array.isArray(u)?u:[]);setRoles(Array.isArray(r)?r:[])}catch(e:any){setError(e?.message??'Unable to load users.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function openCreate(){setSelected(null);setForm(emptyForm);setError(null);setModal('create')}
 function openEdit(u:User){setSelected(u);setForm({employeeId:u.employeeId??'',email:u.email,firstName:u.firstName,lastName:u.lastName,jobTitle:u.jobTitle??'',phone:u.phone??'',departmentId:u.departmentId??'',locationId:u.locationId??''});setError(null);setModal('edit')}
 function openRoles(u:User){setSelected(u);setRoleIds(u.roleIds??[]);setError(null);setModal('roles')}
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setError(null);try{await apiFetch('/users',{method:'POST',body:JSON.stringify(form)});setModal(null);setForm(emptyForm);setMessage('User created. Generate an invite so they can set their password.');await load()}catch(e:any){setError(e?.message??'Unable to create user.')}finally{setSaving(false)}}
 async function edit(e:FormEvent){e.preventDefault();if(!selected)return;setSaving(true);setError(null);try{await apiFetch(`/users/${selected.id}`,{method:'PATCH',body:JSON.stringify(form)});setModal(null);setMessage('Employee profile updated.');await load()}catch(e:any){setError(e?.message??'Unable to update user.')}finally{setSaving(false)}}
 async function saveRoles(){if(!selected)return;setSaving(true);setError(null);try{await apiFetch(`/users/${selected.id}/roles`,{method:'PUT',body:JSON.stringify({roleIds})});setModal(null);setMessage('Roles and access updated.');await load()}catch(e:any){setError(e?.message??'Unable to update roles.')}finally{setSaving(false)}}
 async function invite(u:User){setSaving(true);setError(null);try{const r=await apiFetch(`/users/${u.id}/access-email`,{method:'POST',body:JSON.stringify({action:u.forcePasswordReset?'invite':'reset'})});setSelected(u);setInviteUrl(r.setupUrl??'');setModal('invite');setMessage('Secure access link generated.')}catch(e:any){setError(e?.message??'Unable to generate access link.')}finally{setSaving(false)}}
 async function toggle(u:User){setSaving(true);setError(null);try{await apiFetch(`/users/${u.id}/${u.isActive?'deactivate':'activate'}`,{method:'PATCH'});setMessage(u.isActive?'User deactivated.':'User activated.');await load()}catch(e:any){setError(e?.message??'Unable to update account status.')}finally{setSaving(false)}}
 const roleName=(id:string)=>roles.find(r=>r.id===id)?.name;
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return users.filter(u=>{const text=`${u.employeeId??''} ${u.firstName} ${u.lastName} ${u.email} ${u.jobTitle??''} ${u.departmentId??''} ${u.locationId??''}`.toLowerCase();return(!q||text.includes(q))&&(status==='ALL'||(status==='ACTIVE'?u.isActive:!u.isActive))&&(roleFilter==='ALL'||(u.roleIds??[]).includes(roleFilter))})},[users,query,status,roleFilter]);
 const active=users.filter(u=>u.isActive).length;
 return <div className="mx-auto max-w-[1500px] space-y-6 page-section-enter">
  <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]"><Users size={14}/>Access &amp; workforce</div><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Employees</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Manage employee identities, account status, roles, secure access and asset ownership from one workspace.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" loading={loading} onClick={()=>void load()} icon={<RefreshCw size={15}/>}>Refresh</Button><Button onClick={openCreate} icon={<Plus size={16}/>}>Add employee</Button></div></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Users size={17}/>} label="Total employees" value={users.length} hint="All tenant identities"/><Stat icon={<UserCheck size={17}/>} label="Active" value={active} hint="Can access the console" tone="success"/><Stat icon={<KeyRound size={17}/>} label="Setup required" value={users.filter(u=>u.forcePasswordReset).length} hint="Password setup pending" tone="warning"/><Stat icon={<UserX size={17}/>} label="Inactive" value={users.length-active} hint="Access currently disabled" tone="neutral"/></section>
  {error?<ErrorState title="Unable to complete the request" message={error} onRetry={()=>void load()}/>:message?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3.5 text-sm text-emerald-700" role="status">{message}</div>:null}
  <section className="panel overflow-hidden"><div className="border-b border-slate-100 p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[1fr_180px_220px]"><FormField label="Search employees" id="tenant-user-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, employee ID, email…"/><FormSelect label="Status" id="tenant-user-status" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="ALL">All status</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></FormSelect><FormSelect label="Role" id="tenant-user-role" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="ALL">All roles</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</FormSelect></div></div>{loading?<LoadingState label="Loading employees…"/>:filtered.length===0?<EmptyState title="No employees found" text={query||status!=='ALL'||roleFilter!=='ALL'?'Try changing your search or filters.':'Add your first employee to get started.'} action="Add employee" onAction={openCreate}/>:<div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-slate-50/80 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3.5">Employee</th><th className="px-5 py-3.5">Role &amp; access</th><th className="px-5 py-3.5">Status</th><th className="px-5 py-3.5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(u=><UserRow key={u.id} user={u} roles={roles} onEdit={openEdit} onRoles={openRoles} onAccess={invite} onToggle={u=>setConfirm(u)}/>)}</tbody></table></div>}</section>
  {confirm?<ConfirmDialog open title={confirm.isActive?'Deactivate employee':'Activate employee'} message={`${confirm.firstName} ${confirm.lastName} (${confirm.email})`} confirmLabel={confirm.isActive?'Deactivate':'Activate'} danger={confirm.isActive} loading={saving} onCancel={()=>!saving&&setConfirm(null)} onConfirm={async()=>{const u=confirm;setConfirm(null);await toggle(u)}}/>:null}
  {modal==='create'||modal==='edit'?<Modal open title={modal==='create'?'Add employee':'Edit employee'} description="Changes are saved to the Tenant backend." onClose={()=>!saving&&setModal(null)} size="lg"><ModalBody><form onSubmit={modal==='create'?create:edit} className="grid gap-4 sm:grid-cols-2"><FormField label="First name" id="tenant-user-first-name" required value={form.firstName} onChange={e=>setForm(f=>({...f,firstName:e.target.value}))} placeholder="First name"/><FormField label="Last name" id="tenant-user-last-name" required value={form.lastName} onChange={e=>setForm(f=>({...f,lastName:e.target.value}))} placeholder="Last name"/><FormField label="Work email" id="tenant-user-email" required type="email" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))} placeholder="name@company.com" className="sm:col-span-2"/><FormField label="Employee ID" id="tenant-user-employee-id" value={form.employeeId} onChange={e=>setForm(f=>({...f,employeeId:e.target.value}))} placeholder="Employee ID"/><FormField label="Job title" id="tenant-user-job-title" value={form.jobTitle} onChange={e=>setForm(f=>({...f,jobTitle:e.target.value}))} placeholder="Job title"/><FormField label="Phone" id="tenant-user-phone" value={form.phone} onChange={e=>setForm(f=>({...f,phone:e.target.value}))} placeholder="Phone"/><FormField label="Department" id="tenant-user-department" value={form.departmentId} onChange={e=>setForm(f=>({...f,departmentId:e.target.value}))} placeholder="Department ID"/><FormField label="Location" id="tenant-user-location" value={form.locationId} onChange={e=>setForm(f=>({...f,locationId:e.target.value}))} placeholder="Location ID"/><div className="sm:col-span-2 flex justify-end gap-2 pt-2"><Button variant="secondary" type="button" onClick={()=>setModal(null)} disabled={saving}>Cancel</Button><Button type="submit" loading={saving}>{modal==='create'?'Create employee':'Save changes'}</Button></div></form></ModalBody></Modal>:null}
  {modal==='roles'&&selected?<Modal open title="Manage roles" description={`${selected.firstName} ${selected.lastName}`} onClose={()=>!saving&&setModal(null)} size="md"><ModalBody><div className="max-h-80 space-y-2 overflow-y-auto">{roles.map(r=>{const checked=roleIds.includes(r.id);return <label key={r.id} className={`flex cursor-pointer items-center justify-between rounded-xl border p-3 transition ${checked?'border-[var(--theme-primary)] bg-[var(--theme-primary-soft)]':'border-slate-200 hover:bg-slate-50'}`}><span><span className="block text-sm font-semibold text-slate-900">{r.name}</span><span className="text-xs text-slate-500">{r.permissions?.length??0} permissions{r.isSystem?' · system role':''}</span></span><input type="checkbox" checked={checked} onChange={()=>setRoleIds(checked?roleIds.filter(id=>id!==r.id):[...roleIds,r.id])} className="h-4 w-4 accent-[var(--theme-primary)]"/></label>})}</div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setModal(null)}>Cancel</Button><Button loading={saving} onClick={()=>void saveRoles()}>Save roles</Button></div></ModalBody></Modal>:null}
  {modal==='invite'&&selected?<Modal open title="Invite / reset access" description={selected.email} onClose={()=>setModal(null)} size="md"><ModalBody><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><strong>One-time access link.</strong> It expires in 24 hours.</div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto] items-end"><FormField label="Secure access link" id="tenant-user-invite-url" readOnly value={inviteUrl}/><Button variant="secondary" onClick={()=>void navigator.clipboard.writeText(inviteUrl)} icon={<Copy size={14}/>}>Copy</Button></div><div className="mt-6 flex justify-end"><Button onClick={()=>setModal(null)}>Done</Button></div></ModalBody></Modal>:null}
 </div>;
}
function Stat({icon,label,value,hint,tone='brand'}:{icon:React.ReactNode;label:string;value:number;hint:string;tone?:'brand'|'success'|'warning'|'neutral'}){const cls={brand:'bg-[var(--theme-primary-soft)] text-[var(--theme-primary)]',success:'bg-emerald-50 text-emerald-600',warning:'bg-amber-50 text-amber-600',neutral:'bg-slate-100 text-slate-600'}[tone];return <div className="panel p-4 sm:p-5"><div className="flex items-start justify-between"><div className={`grid h-9 w-9 place-items-center rounded-xl ${cls}`}>{icon}</div><span className="text-2xl font-bold tracking-tight text-slate-950">{value}</span></div><p className="mt-4 text-sm font-semibold text-slate-800">{label}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></div>}
function UserRow({user,roles,onEdit,onRoles,onAccess,onToggle}:{user:User;roles:Role[];onEdit:(u:User)=>void;onRoles:(u:User)=>void;onAccess:(u:User)=>void;onToggle:(u:User)=>void}){const names=(user.roleIds??[]).map(id=>roles.find(r=>r.id===id)?.name).filter(Boolean) as string[];return <tr className="group transition-colors hover:bg-[var(--theme-primary-soft)]/35"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-500"><UserRound size={18}/></div><div className="min-w-0"><Link href={`/users/${user.id}`} className="block truncate font-semibold text-slate-900 hover:text-[var(--theme-link)]">{user.firstName} {user.lastName}</Link><div className="mt-0.5 truncate text-xs text-slate-500">{user.email}</div><div className="mt-0.5 font-mono text-[11px] text-slate-400">{user.employeeId||'Employee ID not set'}</div></div></div></td><td className="px-5 py-4"><button type="button" onClick={()=>onRoles(user)} className="ui-interactive text-left"><div className="flex flex-wrap gap-1.5">{names.slice(0,2).map(n=><Badge key={n} tone="neutral">{n}</Badge>)}{names.length>2?<Badge tone="neutral">+{names.length-2}</Badge>:null}{names.length===0?<Badge tone="warning">No role</Badge>:null}</div><span className="mt-1 block text-[11px] text-slate-400">{names.length} assigned role{names.length===1?'':'s'}</span></button></td><td className="px-5 py-4"><div className="flex flex-col gap-1.5"><StatusBadge status={user.isActive?'ACTIVE':'INACTIVE'}/>{user.forcePasswordReset?<Badge tone="warning">Setup required</Badge>:null}</div></td><td className="px-5 py-4"><div className="flex justify-end gap-1.5"><Button size="sm" variant="secondary" onClick={()=>onEdit(user)} icon={<Pencil size={14}/>}>Edit</Button><Button size="sm" variant="secondary" onClick={()=>void onAccess(user)} disabled={savingState()} icon={<KeyRound size={14}/>}>Access</Button><Button size="sm" variant="secondary" onClick={()=>onToggle(user)} icon={user.isActive?<UserX size={14}/>:<UserCheck size={14}/>}>{user.isActive?'Deactivate':'Activate'}</Button><Link href={`/users/${user.id}`} className="btn-primary btn-sm ui-interactive">Open</Link></div></td></tr>}
function savingState(){return false}
