'use client';
import Link from 'next/link';
import { ArrowLeft, CheckCircle2, Clock3, ShieldCheck, XCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { apiFetch } from '../../../../../../lib/api-client';
import { Badge, LoadingState } from '../../../../../../components/ui';
type Event={id:string;provider?:string;eventType?:string;status?:string;receivedAt?:string;processedAt?:string;resourceId?:string;sequence?:number;detail?:string};
export default function ScimEventsPage(){const [events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);useEffect(()=>{void(async()=>{try{const d=await apiFetch('/identity/scim/events');setEvents(d?.events??[])}catch(e:any){setError(e?.message??'SCIM event data is unavailable.')}finally{setLoading(false)}})()},[]);if(loading)return <div className="mx-auto max-w-5xl py-10"><LoadingState label="Loading SCIM events…"/></div>;return <div className="mx-auto max-w-5xl space-y-6 page-section-enter"><Link href="/settings/identity" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--theme-link)]"><ArrowLeft size={15}/>Back to Identity & SSO</Link><header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]">SCIM reliability</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Event processing</h1><p className="mt-2 text-sm text-slate-500">Duplicate provider events are safely ignored, while out-of-order updates are prevented from overwriting newer state.</p></header>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}<section className="panel overflow-hidden"><div className="divide-y divide-slate-100">{events.length===0?<div className="p-8 text-center text-sm text-slate-500">No SCIM events recorded.</div>:events.map(e=><div key={e.id} className="grid gap-3 p-5 md:grid-cols-[1.2fr_1fr_1fr_1.5fr] md:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-950">{e.eventType??'SCIM event'}</p><Status value={e.status}/></div><p className="mt-1 text-xs text-slate-500">{e.provider??'Provider'} · {e.resourceId??'No resource ID'}</p></div><div className="text-sm text-slate-500"><span className="font-medium text-slate-700">Received:</span> {e.receivedAt??'—'}<br/><span className="font-medium text-slate-700">Processed:</span> {e.processedAt??'—'}</div><div className="text-sm text-slate-500"><span className="font-medium text-slate-700">Sequence:</span> {e.sequence??'—'}</div><p className="text-sm text-slate-500">{e.detail??'Idempotency check passed.'}</p></div>)}</div></section><div className="flex items-start gap-3 rounded-2xl border border-[var(--theme-primary)]/15 bg-[var(--theme-primary-soft)] p-5"><ShieldCheck size={19} className="mt-0.5 text-[var(--theme-primary)]"/><div><p className="font-semibold text-slate-900">Provider events never become database truth</p><p className="mt-1 text-sm text-slate-600">Each event is deduplicated by provider/event identity and checked against the latest known resource version before applying changes. Replayed or stale events are recorded but do not mutate employee state.</p></div></div></div>}
function Status({value}:{value?:string}){return <Badge tone={value==='processed'?'success':value==='failed'?'danger':'neutral'}>{value==='processed'?<CheckCircle2 size={13}/>:value==='failed'?<XCircle size={13}/>:<Clock3 size={13}/>} {value??'pending'}</Badge>}
