'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Building2, Plus, RefreshCw, Search, ShieldCheck, UserRound, Users, X } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import { apiFetch } from '../../../lib/api-client';
import CompanyScopeControl from '../../../components/company-scope-control';
import { Alert, Badge, Button, EmptyState, ErrorState, LoadingState, StatusBadge } from '../../../components/ui';
import { ConfirmDialog } from '../../../components/confirm-dialog';

type AdminLevel='EMPLOYEE'|'COMPANY_ADMIN'|'TENANT_ADMIN';
type Employee={id:string;employeeId?:string;email:string;firstName:string;lastName:string;companyId?:string;jobTitle?:string;isActive:boolean;adminLevel?:AdminLevel};
type Company={id:string;name:string;code?:string};
type Role={id:string;name:string};
const LEVEL_LABEL:Record<AdminLevel,string>={EMPLOYEE:'Employee',COMPANY_ADMIN:'Company Admin',TENANT_ADMIN:'Tenant Admin'};

export default function EmployeesPage(){
 const searchParams=useSearchParams();const companyFilter=searchParams.get('companyId');
 const [employees,setEmployees]=useState<Employee[]>([]),[companies,setCompanies]=useState<Company[]>([]),[roles,setRoles]=useState<Role[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[promoteTarget,setPromoteTarget]=useState<Employee|null>(null),[showCreate,setShowCreate]=useState(false),[creating,setCreating]=useState(false),[form,setForm]=useState({firstName:'',lastName:'',email:'',employeeId:'',companyId:'',jobTitle:'',adminLevel:'EMPLOYEE' as AdminLevel,roleId:''});
 async function load(){setLoading(true);setError(null);try{const [rows,org,roleData]=await Promise.all([apiFetch('/users/employees'),apiFetch('/companies/hierarchy'),apiFetch('/roles')]);setEmployees(Array.isArray(rows)?rows:[]);setCompanies(Array.isArray(org)?org.map((c:any)=>({id:String(c.id),name:String(c.name),code:c.code?String(c.code):undefined})):[]);setRoles(Array.isArray(roleData)?roleData.map((r:any)=>({id:String(r.id),name:String(r.name)})):[])}catch(e:any){setError(e?.message??'Unable to load employees.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const companyName=(id?:string)=>companies.find(c=>c.id===id)?.name??(id||'Not assigned');const scoped=useMemo(()=>companyFilter&&companyFilter!=='all'?employees.filter(u=>u.companyId===companyFilter):employees,[employees,companyFilter]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return !q?scoped:scoped.filter(u=>`${u.firstName} ${u.lastName} ${u.email} ${u.employeeId??''} ${u.jobTitle??''} ${companyName(u.companyId)}`.toLowerCase().includes(q))},[scoped,query,companies]);
 function resetCreate(){setForm({firstName:'',lastName:'',email:'',employeeId:'',companyId:companyFilter&&companyFilter!=='all'?companyFilter:(companies[0]?.id??''),jobTitle:'',adminLevel:'EMPLOYEE',roleId:''})}
 async function createUser(e:React.FormEvent){e.preventDefault();setCreating(true);setError(null);setMessage(null);try{await apiFetch('/users',{method:'POST',body:JSON.stringify({firstName:form.firstName,lastName:form.lastName,email:form.email,employeeId:form.employeeId||undefined,companyId:form.companyId||undefined,jobTitle:form.jobTitle||undefined,adminLevel:form.adminLevel,roleIds:form.roleId?[form.roleId]:undefined})});setShowCreate(false);resetCreate();setMessage('User created successfully. Send the access email from User 360 when ready.');await load()}catch(e:any){setError(e?.message??'Unable to create user.')}finally{setCreating(false)}}
 async function promote(){if(!promoteTarget)return;const user=promoteTarget;setBusy(user.id);setError(null);setMessage(null);try{await apiFetch(`/users/${user.id}/admin-level`,{method:'PATCH',body:JSON.stringify({adminLevel:'TENANT_ADMIN'})});setMessage(`${user.firstName} ${user.lastName} is now a Tenant Administrator.`);setPromoteTarget(null);await load()}catch(e:any){setError(e?.message??'Unable to promote employee.')}finally{setBusy(null)}}
 const scopeText=companyFilter&&companyFilter!=='all'?companyName(companyFilter):'All companies';
 return <div className="mx-auto max-w-[1500px] space-y-6 page-section-enter">
  <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]"><Users size={14}/>People & Organization</div><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold tracking-tight text-slate-950">Employees</h1><Badge tone="neutral">{scoped.length} in scope</Badge><CompanyScopeControl/></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">One central workflow for employee creation, access profile, roles, company scope and User 360.</p></div><div className="flex flex-wrap gap-2"><Button variant="primary" onClick={()=>{resetCreate();setShowCreate(true)}} icon={<Plus size={15}/>}>Create user</Button><Button variant="secondary" loading={loading} onClick={()=>void load()} icon={<RefreshCw size={15}/>}>Refresh</Button></div></header>
  <div className="grid gap-3 sm:grid-cols-3"><div className="panel p-4"><div className="text-xs font-medium text-slate-500">Current scope</div><div className="mt-1 flex items-center gap-2 font-semibold text-slate-900"><Building2 size={15} className="text-[var(--theme-link)]"/>{scopeText}</div></div><div className="panel p-4"><div className="text-xs font-medium text-slate-500">Active employees</div><div className="mt-1 text-xl font-bold text-slate-950">{scoped.filter(u=>u.isActive).length}</div></div><div className="panel p-4"><div className="text-xs font-medium text-slate-500">Administrators in view</div><div className="mt-1 text-xl font-bold text-slate-950">{scoped.filter(u=>u.adminLevel==='COMPANY_ADMIN'||u.adminLevel==='TENANT_ADMIN').length}</div></div></div>
  {error?<ErrorState title="Unable to load employees" message={error} onRetry={()=>void load()}/>:message?<Alert title="Access updated" message={message} tone="success"/>:null}
  <section className="panel overflow-hidden"><div className="border-b border-slate-100 p-4 sm:p-5"><label className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 shadow-sm"><Search size={16} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, employee ID or company…" className="w-full bg-transparent py-2 text-sm outline-none"/></label></div>{loading?<LoadingState label="Loading employees…"/>:filtered.length===0?<EmptyState title="No employees found in this scope" text="Create a user or change the company scope."/>:<div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Company</th><th className="px-5 py-3">Job title</th><th className="px-5 py-3">Access level</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(u=><tr key={u.id} className="hover:bg-[var(--theme-primary-soft)]/35"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><UserRound size={17}/></span><div><Link href={`/users/user-control?userId=${encodeURIComponent(u.id)}`} className="font-semibold text-slate-900 hover:text-[var(--theme-link)]">{u.firstName} {u.lastName}</Link><div className="mt-0.5 text-xs text-slate-500">{u.email}</div><div className="mt-0.5 font-mono text-[11px] text-slate-400">{u.employeeId||'Employee ID not set'}</div></div></div></td><td className="px-5 py-4"><div className="font-medium text-slate-700">{companyName(u.companyId)}</div></td><td className="px-5 py-4 text-slate-600">{u.jobTitle||'—'}</td><td className="px-5 py-4"><Badge tone={u.adminLevel==='TENANT_ADMIN'||u.adminLevel==='COMPANY_ADMIN'?'brand':'neutral'}>{LEVEL_LABEL[u.adminLevel??'EMPLOYEE']}</Badge></td><td className="px-5 py-4"><StatusBadge status={u.isActive?'ACTIVE':'INACTIVE'}/></td><td className="px-5 py-4 text-right"><div className="inline-flex flex-wrap justify-end gap-2"><Link href={`/users/user-control?userId=${encodeURIComponent(u.id)}`} className="inline-flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 hover:bg-slate-50">User 360 <ArrowUpRight size={13}/></Link>{u.adminLevel==='TENANT_ADMIN'?<span className="inline-flex h-9 items-center rounded-lg bg-slate-50 px-3 text-xs font-semibold text-slate-400">Tenant Admin</span>:<Button variant="secondary" size="sm" loading={busy===u.id} disabled={!u.isActive||!!busy} onClick={()=>setPromoteTarget(u)} icon={<ShieldCheck size={14}/>}>Promote to Tenant Admin</Button>}</div></td></tr>)}</tbody></table></div>}</section>
  {showCreate&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="text-xl font-semibold text-slate-950">Create tenant user</h2><p className="mt-1 text-sm text-slate-500">Create the identity once, then manage access from User 360.</p></div><button onClick={()=>{if(!creating)setShowCreate(false)}} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18}/></button></div><form onSubmit={createUser} className="space-y-5 p-6"><div className="grid gap-4 sm:grid-cols-2"><input required placeholder="First name" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} className="field"/><input required placeholder="Last name" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} className="field"/><input required type="email" placeholder="Work email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="field sm:col-span-2"/><input placeholder="Employee ID" value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})} className="field"/><input placeholder="Job title" value={form.jobTitle} onChange={e=>setForm({...form,jobTitle:e.target.value})} className="field"/></div><div className="grid gap-4 sm:grid-cols-2"><select value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value})} className="field"><option value="">Company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={form.adminLevel} onChange={e=>setForm({...form,adminLevel:e.target.value as AdminLevel})} className="field"><option value="EMPLOYEE">Employee</option><option value="COMPANY_ADMIN">Company Admin</option><option value="TENANT_ADMIN">Tenant Admin</option></select><select value={form.roleId} onChange={e=>setForm({...form,roleId:e.target.value})} className="field sm:col-span-2"><option value="">Use default role for access level</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><p className="font-semibold text-slate-800">First login</p><p className="mt-1">The user is created with a forced password change. Send the invitation/reset link from User 360.</p></div><div className="flex justify-end gap-2"><Button variant="secondary" type="button" onClick={()=>setShowCreate(false)} disabled={creating}>Cancel</Button><Button variant="primary" type="submit" loading={creating}>Create user</Button></div></form></div></div>}
  <ConfirmDialog open={!!promoteTarget} title="Promote to Tenant Administrator" message={promoteTarget?`Give ${promoteTarget.firstName} ${promoteTarget.lastName} tenant-wide administrative access?`:undefined} confirmLabel="Promote" loading={!!busy} onConfirm={()=>void promote()} onCancel={()=>{if(!busy)setPromoteTarget(null)}} />
 </div>;
}
