'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Search, RefreshCw, UserRound, ShieldCheck } from 'lucide-react';
import { apiFetch } from '../../../lib/api-client';

type Employee = { id:string; employeeId?:string; email:string; firstName:string; lastName:string; companyId?:string; jobTitle?:string; isActive:boolean; adminLevel?:'EMPLOYEE'|'COMPANY_ADMIN'|'TENANT_ADMIN' };

export default function EmployeesPage(){
 const [employees,setEmployees]=useState<Employee[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);try{const rows=await apiFetch('/users/employees');setEmployees(Array.isArray(rows)?rows:[]);}catch(e:any){setError(e?.message??'Unable to load employees.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return !q?employees:employees.filter((u)=>`${u.firstName} ${u.lastName} ${u.email} ${u.employeeId??''} ${u.jobTitle??''} ${u.companyId??''}`.toLowerCase().includes(q))},[employees,query]);
 async function promote(user:Employee){if(!window.confirm(`Promote ${user.firstName} ${user.lastName} to Tenant Administrator?`))return;setBusy(user.id);setError(null);setMessage(null);try{await apiFetch(`/users/${user.id}/admin-level`,{method:'PATCH',body:JSON.stringify({adminLevel:'TENANT_ADMIN'})});setMessage(`${user.firstName} ${user.lastName} is now a Tenant Administrator.`);await load()}catch(e:any){setError(e?.message??'Unable to promote employee.')}finally{setBusy(null)}}
 return <div className="mx-auto max-w-[1500px] space-y-6 page-section-enter">
  <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-[var(--theme-link)]"><UserRound size={14}/>People</div><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Employees</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Manage normal workforce identities. Each employee belongs to a company; administrative authority is managed separately.</p></div><button onClick={()=>void load()} disabled={loading} className="btn-secondary ui-interactive"><RefreshCw size={15} className={loading?'animate-spin':''}/>Refresh</button></header>
  {error?<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><b>Unable to complete the request</b><div className="mt-1">{error}</div></div>:null}{message?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>:null}
  <section className="panel overflow-hidden"><div className="border-b border-slate-100 p-4 sm:p-5"><label className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 shadow-sm"><Search size={16} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, email, company…" className="w-full bg-transparent py-2 text-sm outline-none"/></label></div>
   {loading?<div className="p-8 text-sm text-slate-500">Loading employees…</div>:filtered.length===0?<div className="p-8 text-sm text-slate-500">No employees found.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Company</th><th className="px-5 py-3">Job title</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((u)=><tr key={u.id} className="hover:bg-[var(--theme-primary-soft)]/35"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><UserRound size={17}/></span><div><Link href={`/users/${u.id}`} className="font-semibold text-slate-900 hover:text-[var(--theme-link)]">{u.firstName} {u.lastName}</Link><div className="mt-0.5 text-xs text-slate-500">{u.email}</div><div className="mt-0.5 font-mono text-[11px] text-slate-400">{u.employeeId||'Employee ID not set'}</div></div></div></td><td className="px-5 py-4 font-mono text-xs text-slate-600">{u.companyId||'—'}</td><td className="px-5 py-4 text-slate-600">{u.jobTitle||'—'}</td><td className="px-5 py-4"><span className={u.isActive?'badge badge-success':'badge badge-neutral'}>{u.isActive?'Active':'Inactive'}</span></td><td className="px-5 py-4 text-right"><button onClick={()=>void promote(u)} disabled={!u.isActive||busy===u.id} className="btn-secondary btn-sm ui-interactive"><ShieldCheck size={14}/>{busy===u.id?'Promoting…':'Promote to Tenant Admin'}</button></td></tr>)}</tbody></table></div>}
  </section>
 </div>
}
