import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { AuthContext } from '../../common/guards/tenant-context.guard';
type SiteType='plant'|'branch_office'|'head_office'|'other';
@Injectable()
export class OrganizationManagementService {
 constructor(private readonly db:PrismaService){}
 private async assertCompany(auth:AuthContext,companyId:string){const company=await this.db.company.findFirst({where:{id:companyId,tenantId:auth.tenantId}});if(!company)throw new NotFoundException('Company not found');if(!auth.crossCompany&&company.id!==auth.companyId)throw new ForbiddenException('Company out of scope for this user');return company;}
 private async assertSite(auth:AuthContext,siteId:string){const site=await this.db.site.findUnique({where:{id:siteId}});if(!site)throw new NotFoundException('Site not found');await this.assertCompany(auth,site.companyId);return site;}
 private async assertLocation(auth:AuthContext,locationId:string){const location=await this.db.location.findUnique({where:{id:locationId}});if(!location)throw new NotFoundException('Location not found');await this.assertSite(auth,location.siteId);return location;}
 async updateCompany(auth:AuthContext,companyId:string,name:string,code:string){await this.assertCompany(auth,companyId);const normalizedName=name.trim(),normalizedCode=code.trim().toUpperCase();const duplicate=await this.db.company.findFirst({where:{tenantId:auth.tenantId,code:normalizedCode,id:{not:companyId}}});if(duplicate)throw new ConflictException('Company code already exists');const updated=await this.db.company.update({where:{id:companyId},data:{name:normalizedName,code:normalizedCode}});return{id:updated.id,name:updated.name,code:updated.code};}
 async deleteCompany(auth:AuthContext,companyId:string){await this.assertCompany(auth,companyId);const [sites,assets,users]=await Promise.all([this.db.site.count({where:{companyId}}),this.db.asset.count({where:{companyId}}),this.db.user.count({where:{tenantId:auth.tenantId,companyId}})]);if(sites||assets||users)throw new ConflictException('Company cannot be deleted while it contains sites, assets, or users. Remove or reassign them first.');await this.db.company.delete({where:{id:companyId}});return{ok:true};}
 async updateSite(auth:AuthContext,siteId:string,name:string,type:SiteType){await this.assertSite(auth,siteId);const normalizedName=name.trim();if(!normalizedName)throw new ConflictException('Site name is required');const normalizedType=['plant','branch_office','head_office','other'].includes(type)?type:'plant';const updated=await this.db.site.update({where:{id:siteId},data:{name:normalizedName,type:normalizedType}});return{id:updated.id,name:updated.name,type:updated.type};}
 async deleteSite(auth:AuthContext,siteId:string){await this.assertSite(auth,siteId);const locations=await this.db.location.count({where:{siteId}});if(locations)throw new ConflictException('Site cannot be deleted while it contains locations.');await this.db.site.delete({where:{id:siteId}});return{ok:true};}
 async updateLocation(auth:AuthContext,locationId:string,name:string){await this.assertLocation(auth,locationId);const updated=await this.db.location.update({where:{id:locationId},data:{name:name.trim()}});return{id:updated.id,name:updated.name};}
 async deleteLocation(auth:AuthContext,locationId:string){await this.assertLocation(auth,locationId);const departments=await this.db.department.count({where:{locationId}});if(departments)throw new ConflictException('Location cannot be deleted while it contains departments.');await this.db.location.delete({where:{id:locationId}});return{ok:true};}
 async updateDepartment(auth:AuthContext,departmentId:string,name:string){const department=await this.db.department.findUnique({where:{id:departmentId}});if(!department)throw new NotFoundException('Department not found');await this.assertLocation(auth,department.locationId);const updated=await this.db.department.update({where:{id:departmentId},data:{name:name.trim()}});return{id:updated.id,name:updated.name};}
 async deleteDepartment(auth:AuthContext,departmentId:string){const department=await this.db.department.findUnique({where:{id:departmentId}});if(!department)throw new NotFoundException('Department not found');await this.assertLocation(auth,department.locationId);await this.db.department.delete({where:{id:departmentId}});return{ok:true};}
}
