'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, Clock3, RefreshCw, Search, X, ArrowRight, UserRound, MapPin } from 'lucide-react';
import { apiFetch } from '../../../../lib/api-client';
import { Alert, Button, Card, EmptyState, LoadingState, MetricCard, StatusBadge } from '../../../../components/ui';

type Transfer = { id: string; assetId: string; fromUserId?: string; fromLocationId?: string; fromDepartmentId?: string; toUserId?: string; toLocationId?: string; toDepartmentId?: string; status: string; requestedByUserId: string; requestedAt: string; reason?: string };
const STATUS_OPTIONS = ['', 'PENDING', 'APPROVED', 'COMPLETED', 'REJECTED', 'CANCELLED'];
function endpoint(userId?: string, locationId?: string, departmentId?: string) { if (userId) return <span className="inline-flex items-center gap-1.5"><UserRound size={14}/>User <span className="font-mono text-[11px]">{userId.slice(0, 8)}</span></span>; if (locationId) return <span className="inline-flex items-center gap-1.5"><MapPin size={14}/>Location <span className="font-mono text-[11px]">{locationId.slice(0, 8)}</span></span>; if (departmentId) return <span className="inline-flex items-center gap-1.5"><MapPin size={14}/>Department <span className="font-mono text-[11px]">{departmentId.slice(0, 8)}</span></span>; return <span className="text-slate-400">Not specified</span>; }

export default function AssetTransfersPage() {
  const [items, setItems] = useState<Transfer[]>([]); const [status, setStatus] = useState(''); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [actionId, setActionId] = useState<string | null>(null);
  async function load() { setBusy(true); setError(''); try { const params = status ? `?status=${encodeURIComponent(status)}` : ''; const data = await apiFetch(`/assets/transfers${params}`); setItems(Array.isArray(data) ? data : []); } catch (e: any) { setError(e?.message ?? 'Unable to load transfers.'); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, [status]);
  async function action(id: string, type: 'approve' | 'reject' | 'complete' | 'cancel') { setError(''); setActionId(id); try { await apiFetch(`/assets/transfers/${id}/${type}`, { method: 'POST', body: JSON.stringify({}) }); await load(); } catch (e: any) { setError(e?.message ?? `Unable to ${type} transfer.`); } finally { setActionId(null); } }
  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); if (!value) return items; return items.filter(item => [item.assetId, item.reason, item.fromUserId, item.toUserId, item.fromLocationId, item.toLocationId].filter(Boolean).some(v => String(v).toLowerCase().includes(value))); }, [items, query]);
  const counts = useMemo(() => ({ pending: items.filter(i => i.status === 'PENDING').length, approved: items.filter(i => i.status === 'APPROVED').length, completed: items.filter(i => i.status === 'COMPLETED').length }), [items]);

  return <div className="mx-auto max-w-[1320px] space-y-6">
    <div className="flex items-center justify-between gap-3"><Link href="/assets" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-[var(--theme-link)]"><ArrowLeft size={16}/>Back to assets</Link></div>
    <header className="panel overflow-hidden p-6 sm:p-7">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow text-[var(--theme-link)]">Inventory operations</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Asset transfers</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Review and process custody transfers in one place. Approval and completion remain separate so every movement is traceable.</p></div><Button variant="secondary" loading={busy} icon={<RefreshCw size={16}/>} onClick={() => void load()}>Refresh</Button></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-3"><MetricCard label="Awaiting approval" value={counts.pending} hint="Needs an approval decision" tone="warning"/><MetricCard label="Ready to complete" value={counts.approved} hint="Approved custody changes" tone="info"/><MetricCard label="Completed" value={counts.completed} hint="Completed transfers in this view" tone="success"/></div>
    </header>
    <Card className="overflow-hidden">
      <div className="border-b border-slate-100 p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><label className="flex min-h-11 min-w-0 flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 shadow-sm transition focus-within:border-[var(--theme-focus)] focus-within:bg-white"><Search size={16} className="shrink-0 text-slate-400"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search asset, user, location, or reason" className="w-full bg-transparent py-2 text-sm outline-none placeholder:text-slate-400"/></label><select value={status} onChange={e => setStatus(e.target.value)} className="field min-h-11 sm:w-48"><option value="">All statuses</option>{STATUS_OPTIONS.slice(1).map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></div></div>
      {error ? <div className="p-4 sm:p-5"><Alert tone="danger" title="Transfer operation failed" message={error} onClose={() => setError('')}/></div> : null}
      {busy ? <div className="p-4 sm:p-5"><LoadingState label="Loading transfer requests…"/></div> : filtered.length === 0 ? <div className="p-4 sm:p-5"><EmptyState title="No transfer requests found" text={query || status ? 'Try a different status or search term.' : 'Transfer requests will appear here when custody changes are requested.'}/></div> : <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr><th className="px-5 py-3">Asset</th><th className="px-5 py-3">From</th><th className="px-5 py-3">To</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Requested</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody>{filtered.map(item => { const acting = actionId === item.id; return <tr key={item.id}><td className="px-5 py-4 align-top"><Link href={`/assets/${item.assetId}`} className="font-semibold text-[var(--theme-link)] hover:underline">{item.assetId.slice(0, 12)}</Link><div className="mt-1 max-w-xs truncate text-xs text-slate-500" title={item.reason}>{item.reason || 'No reason provided'}</div></td><td className="px-5 py-4 align-top text-xs text-slate-600">{endpoint(item.fromUserId, item.fromLocationId, item.fromDepartmentId)}</td><td className="px-5 py-4 align-top text-xs text-slate-600"><span className="mb-1 inline-block text-slate-400"><ArrowRight size={14}/></span>{endpoint(item.toUserId, item.toLocationId, item.toDepartmentId)}</td><td className="px-5 py-4 align-top"><StatusBadge status={item.status}/></td><td className="px-5 py-4 align-top text-xs text-slate-500">{new Date(item.requestedAt).toLocaleString()}</td><td className="px-5 py-4 align-top"><div className="flex justify-end gap-2">{item.status === 'PENDING' && <><Button size="sm" loading={acting} icon={<Check size={14}/>} onClick={() => void action(item.id, 'approve')}>Approve</Button><Button size="sm" variant="danger" disabled={acting} icon={<X size={14}/>} onClick={() => void action(item.id, 'reject')}>Reject</Button></>}{item.status === 'APPROVED' && <><Button size="sm" loading={acting} icon={<Check size={14}/>} onClick={() => void action(item.id, 'complete')}>Complete</Button><Button size="sm" variant="secondary" disabled={acting} icon={<X size={14}/>} onClick={() => void action(item.id, 'cancel')}>Cancel</Button></>}</div></td></tr>; })}</tbody></table></div>}
      {filtered.length > 0 ? <div className="border-t border-slate-100 px-4 py-3 text-xs text-slate-500 sm:px-5">Showing <span className="font-semibold text-slate-700">{filtered.length}</span> of <span className="font-semibold text-slate-700">{items.length}</span> transfer requests</div> : null}
    </Card>
  </div>;
}
