'use client';
import { createContext, useContext, useEffect, useRef, useState, ReactNode, CSSProperties } from 'react';
import { useRouter } from 'next/navigation';
import { apiFetch, login as apiLogin, logout as apiLogout, setSessionEstablished } from './api-client';
export type TenantFeatures=Record<string,boolean|number|string|null|undefined>; type ThemeVars=CSSProperties&Record<`--theme-${string}`,string>; export type TenantProfile={id:string;name:string;slug:string;logoFileId:string|null;logoUrl:string|null;primaryEmail:string|null;phone:string|null;website:string|null;status:string;company:{id:string;name:string;code:string}|null};
export type TenantAdminLevel='EMPLOYEE'|'COMPANY_ADMIN'|'TENANT_ADMIN';
interface AuthState{status:'loading'|'authenticated'|'unauthenticated';adminLevel:TenantAdminLevel;themePreset:string;features:TenantFeatures;forcePasswordReset:boolean;tenantProfile:TenantProfile|null;hasFeature:(key:string)=>boolean;login:(email:string,password:string)=>Promise<void>;logout:()=>Promise<void>;refreshAuth:()=>Promise<void>;refreshLicense:()=>Promise<void>;refreshTenantProfile:()=>Promise<void>}
const AuthContext=createContext<AuthState|null>(null);const API_BASE=process.env.NEXT_PUBLIC_API_BASE??'http://localhost:3001/api/v1';
const PRESETS:Record<string,Record<string,string>>={trial:{primary:'#64748b',primaryHover:'#475569',primarySoft:'#f1f5f9',sidebar:'#1e293b',sidebarText:'#cbd5e1',sidebarHover:'#334155',sidebarActive:'#64748b',focus:'#64748b',link:'#475569'},starter:{primary:'#2563eb',primaryHover:'#1d4ed8',primarySoft:'#eff6ff',sidebar:'#0f172a',sidebarText:'#cbd5e1',sidebarHover:'#1e293b',sidebarActive:'#2563eb',focus:'#3b82f6',link:'#2563eb'},professional:{primary:'#7c3aed',primaryHover:'#6d28d9',primarySoft:'#f5f3ff',sidebar:'#21133f',sidebarText:'#ddd6fe',sidebarHover:'#31205b',sidebarActive:'#7c3aed',focus:'#8b5cf6',link:'#7c3aed'},enterprise:{primary:'#b7791f',primaryHover:'#975a16',primarySoft:'#fffbeb',sidebar:'#292215',sidebarText:'#f3e8c8',sidebarHover:'#3b311f',sidebarActive:'#b7791f',focus:'#d69e2e',link:'#a16207'},restricted:{primary:'#dc2626',primaryHover:'#b91c1c',primarySoft:'#fef2f2',sidebar:'#2b1215',sidebarText:'#fecaca',sidebarHover:'#451a1d',sidebarActive:'#dc2626',focus:'#ef4444',link:'#dc2626'}};
function themeVars(preset:string):ThemeVars{const values=PRESETS[preset]??PRESETS.starter;return Object.fromEntries(Object.entries(values).map(([key,value])=>[`--theme-${key}`,value])) as ThemeVars;} function isFeatureEnabled(features:TenantFeatures,key:string){return features[key]===true;}
export function AuthProvider({children}:{children:ReactNode}){const[status,setStatus]=useState<AuthState['status']>('loading');const[adminLevel,setAdminLevel]=useState<TenantAdminLevel>('EMPLOYEE');const[themePreset,setThemePreset]=useState('starter');const[features,setFeatures]=useState<TenantFeatures>({});const[forcePasswordReset,setForcePasswordReset]=useState(false);const[tenantProfile,setTenantProfile]=useState<TenantProfile|null>(null);const authGeneration=useRef(0);const router=useRouter();
 async function loadTheme(){try{const license=await apiFetch('/billing/license');const preset=typeof license?.themePreset==='string'?license.themePreset:'starter';const nextFeatures=license?.features&&typeof license.features==='object'?license.features as TenantFeatures:{};setThemePreset(preset);setFeatures(nextFeatures);return license;}catch{setThemePreset('starter');setFeatures({});return null;}}
 async function refreshTenantProfile(){try{const profile=await apiFetch('/companies/tenant-profile');setTenantProfile(profile);}catch{setTenantProfile(null);}}
 async function refreshAuth(){const generation=authGeneration.current;const res=await fetch(`${API_BASE}/auth/session`,{method:'GET',headers:{'X-Auth-Scope':'tenant'},credentials:'include'});if(generation!==authGeneration.current)return;if(!res.ok){setStatus('unauthenticated');return;}const data=await res.json();if(generation!==authGeneration.current)return;if(!data.authenticated||data.accountType!=='TENANT'){setSessionEstablished(false);setStatus('unauthenticated');setAdminLevel('EMPLOYEE');setForcePasswordReset(false);return;}setSessionEstablished(true);setAdminLevel((data.adminLevel??'EMPLOYEE') as TenantAdminLevel);setForcePasswordReset(data.forcePasswordReset===true);setStatus('authenticated');await Promise.all([loadTheme(),refreshTenantProfile()]);}
 useEffect(()=>{let active=true;const generation=authGeneration.current;void refreshAuth().catch(()=>{if(active&&generation===authGeneration.current){setSessionEstablished(false);setStatus('unauthenticated');}});return()=>{active=false;};},[]);
 useEffect(()=>{if(status==='authenticated'&&forcePasswordReset&&typeof window!=='undefined'&&!window.location.pathname.endsWith('/change-password'))router.replace('/change-password');},[status,forcePasswordReset,router]);
 async function login(email:string,password:string){authGeneration.current+=1;const result=await apiLogin(email,password);setSessionEstablished(true);setAdminLevel((result?.adminLevel??'EMPLOYEE') as TenantAdminLevel);setForcePasswordReset(result?.forcePasswordReset===true);setStatus('authenticated');await Promise.all([loadTheme(),refreshTenantProfile()]);if(result?.forcePasswordReset)router.replace('/change-password');}
 async function logout(){authGeneration.current+=1;await apiLogout();setSessionEstablished(false);setStatus('unauthenticated');setAdminLevel('EMPLOYEE');setThemePreset('starter');setFeatures({});setForcePasswordReset(false);setTenantProfile(null);router.replace('/login');}
 async function refreshLicense(){await loadTheme();}
 const hasFeature=(key:string)=>isFeatureEnabled(features,key);
 return <div className="min-h-screen" data-tenant-theme={themePreset} style={themeVars(themePreset)}><AuthContext.Provider value={{status,adminLevel,themePreset,features,forcePasswordReset,tenantProfile,hasFeature,login,logout,refreshAuth,refreshLicense,refreshTenantProfile}}>{children}</AuthContext.Provider></div>;
}
export function useAuth(){const ctx=useContext(AuthContext);if(!ctx)throw new Error('useAuth must be used within AuthProvider');return ctx;}
